// A1-A2 Basic Vocabulary (~600 words)
module.exports=[
["the","/ðə/","art. 这；那","The sun rises in the east.","The book is on the table.","","","",""],
["be","/biː/","v. 是；存在","I am a student.","She is very happy today.","be able to","","being","been"],
["have","/hæv/","v. 有；经历","I have two brothers.","Have you had lunch yet?","have to","have a good time","",""],
["do","/duː/","v. 做；行动","What do you do?","I did my homework.","do well","do business","doing","done"],
["say","/seɪ/","v. 说；讲","What did you say?","She said she would come.","say goodbye","that is to say","saying",""],
["go","/ɡəʊ/","v. 去；走","Lets go to the park.","How is your project going?","go on","go through","going","gone"],
["get","/ɡet/","v. 得到；变得","I need to get some sleep.","It is getting dark outside.","get up","get along with","getting",""],
["make","/meɪk/","v. 做；制造；使","She makes her own clothes.","The news made me very happy.","make sure","make a difference","maker","making"],
["know","/nəʊ/","v. 知道；认识","Do you know the answer?","Ive known her for ten years.","know about","as far as I know","knowledge","known"],
["think","/θɪŋk/","v. 想；认为","What do you think about this?","I think its a great idea.","think about","think over","thought","thinker"],
["see","/siː/","v. 看见；理解","I can see the mountains.","See you tomorrow!","see off","see through","seeing","sight"],
["come","/kʌm/","v. 来；到达","Come here please.","The best is yet to come.","come from","come up with","coming","become"],
["want","/wɒnt/","v. 想要；需要","I want a cup of coffee.","What do you want to do?","want to do","","wanted","unwanted"],
["look","/lʊk/","v. 看；看起来","Look at that beautiful sunset.","You look tired today.","look for","look after","looking","outlook"],
["use","/juːz/","v. 使用；利用","May I use your phone?","This tool is easy to use.","use up","make use of","useful","user"],
["find","/faɪnd/","v. 找到；发现","I cannot find my keys.","She found a great job.","find out","find fault with","finding","finder"],
["give","/ɡɪv/","v. 给；提供","Give me a hand please.","She gave a wonderful speech.","give up","give away","given","giver"],
["tell","/tel/","v. 告诉；讲述","Tell me a story.","I told him the truth.","tell apart","tell the truth","teller","telling"],
["work","/wɜːk/","v./n. 工作；运转","I work in a hospital.","The machine works perfectly.","work out","work on","worker","working"],
["call","/kɔːl/","v. 打电话；称呼","Call me when you arrive.","They called him a hero.","call for","call off","caller","calling"],
["try","/traɪ/","v. 尝试；努力","Try this dish it is delicious.","I will try my best.","try on","try out","trial","trying"],
["ask","/ɑːsk/","v. 问；请求","May I ask a question?","She asked me for help.","ask for","ask about","asking",""],
["need","/niːd/","v./n. 需要","I need your help.","There is a great need for change.","in need of","","needy","needless"],
["feel","/fiːl/","v. 感觉；触摸","I feel much better now.","Feel this fabric it is so soft.","feel like","feel free to","feeling","felt"],
["become","/bɪˈkʌm/","v. 成为；变得","She became a doctor.","It is becoming more difficult.","become of","","becoming",""],
["leave","/liːv/","v. 离开；留下","I leave for work at 8 AM.","Leave the door open please.","leave behind","leave out","leaver","leaving"],
["put","/pʊt/","v. 放；放置；表达","Put the book on the shelf.","How should I put this?","put off","put up with","putting",""],
["mean","/miːn/","v. 意味着 a.吝啬的","What does this word mean?","He is too mean to share.","mean to do","","meaning","meaningful"],
["keep","/kiːp/","v. 保持；保留；继续","Keep quiet please.","She keeps a diary.","keep on","keep up with","keeper","keeping"],
["let","/let/","v. 让；允许","Let me help you.","Do not let the fire go out.","let down","let go of","letting",""],
["begin","/bɪˈɡɪn/","v. 开始","Let us begin the meeting.","The story begins in a small town.","begin with","to begin with","beginner","beginning"],
["seem","/siːm/","v. 似乎；好像","You seem happy today.","It seems like a good idea.","seem to be","","seeming","seemingly"],
["help","/help/","v./n. 帮助；救助","Can you help me please?","I need some help with this.","help out","cannot help doing","helper","helpful"],
["talk","/tɔːk/","v./n. 说话；交谈","We need to talk.","She gave a brilliant talk.","talk about","talk over","talker","talkative"],
["turn","/tɜːn/","v./n. 转动；变成","Turn left at the corner.","The leaves turned red.","turn on","turn out","turning","return"],
["start","/stɑːt/","v./n. 开始；启动","Let us start the game.","The car will not start.","start over","start up","starter","starting"],
["show","/ʃəʊ/","v. 展示；表明 n.演出","Show me your passport.","The data shows a clear trend.","show off","show up","shower","showing"],
["hear","/hɪər/","v. 听见；听说","I can hear music playing.","Did you hear about the news?","hear from","hear of","hearing","heard"],
["play","/pleɪ/","v./n. 玩；演奏；扮演","Children love to play outside.","She plays the piano beautifully.","play with","play a role","player","playful"],
["run","/rʌn/","v. 跑；经营；运行","She runs every morning.","He runs a small business.","run out of","run into","runner","running"],
["move","/muːv/","v. 移动；搬家；感动","Please move your car.","The story moved me to tears.","move on","move in","movement","moving"],
["like","/laɪk/","prep. 像 v.喜欢","She looks like her mother.","I like reading books.","feel like","look like","likely","likeness"],
["live","/lɪv/","v. 生活；居住 a.活的","I live in Beijing.","We watched a live performance.","live on","live up to","lively","livelihood"],
["believe","/bɪˈliːv/","v. 相信；认为","I believe in you.","Do you believe in ghosts?","believe in","make believe","belief","believer"],
["hold","/həʊld/","v. 握住；容纳；举行","Hold my hand.","The room holds 200 people.","hold on","hold back","holder","holding"],
["bring","/brɪŋ/","v. 带来；引起","Bring your friend along.","The storm brought heavy rain.","bring up","bring about","bringing",""],
["happen","/ˈhæpən/","v. 发生；碰巧","What happened here?","I happened to meet her.","happen to","","happening","happenstance"],
["write","/raɪt/","v. 写；写作","Write your name here.","She writes for a newspaper.","write down","write back","writer","writing"],
["provide","/prəˈvaɪd/","v. 提供；供给","The hotel provides free breakfast.","We provide quality service.","provide with","provide for","provider","provision"],
["sit","/sɪt/","v. 坐；位于","Please sit down.","The house sits on a hill.","sit down","sit back","sitting",""],
["stand","/stænd/","v. 站立；忍受","Stand up straight.","I cannot stand the noise.","stand for","stand out","standing","outstanding"],
["lose","/luːz/","v. 失去；输掉","I lost my wallet.","Our team lost the game.","lose weight","lose track of","loser","loss"],
["pay","/peɪ/","v. 支付；付出","How much did you pay?","Hard work pays off.","pay for","pay attention","payment","payable"],
["meet","/miːt/","v. 遇见；会面；满足","Nice to meet you.","We need to meet the deadline.","meet with","meet up","meeting",""],
["include","/ɪnˈkluːd/","v. 包括；包含","The price includes tax.","Breakfast is included.","include in","","including","inclusive"],
["continue","/kənˈtɪnjuː/","v. 继续；持续","Please continue your story.","The rain continued all day.","continue to do","","continuation","continuous"],
["set","/set/","v. 放置；设定 n.一套","Set the table for dinner.","The sun set behind the hills.","set up","set off","setting","reset"],
["learn","/lɜːn/","v. 学习；学会","I want to learn Spanish.","We learn from our mistakes.","learn from","learn about","learner","learning"],
["change","/tʃeɪndʒ/","v./n. 改变；变化","Things have changed a lot.","I need a change of scenery.","change into","","changeable","unchanged"],
["lead","/liːd/","v. 引导；导致；领先","Lead the way please.","This road leads to the city.","lead to","take the lead","leader","leadership"],
["understand","/ˌʌndəˈstænd/","v. 理解；明白","Do you understand the question?","I fully understand your concern.","understand each other","","understanding","misunderstand"],
["watch","/wɒtʃ/","v. 观看；注视 n.手表","Watch the movie with me.","Keep a close watch on the kids.","watch out","watch over","watcher","watchful"],
["follow","/ˈfɒləʊ/","v. 跟随；遵循","Follow me please.","You should follow the rules.","follow up","follow through","follower","following"],
["stop","/stɒp/","v. 停止；阻止","Stop talking please.","The rain has stopped.","stop doing","stop from","stopper","unstoppable"],
["create","/kriˈeɪt/","v. 创造；创建","She created a beautiful painting.","We aim to create value.","create opportunities","","creator","creative"],
["speak","/spiːk/","v. 说话；讲","Do you speak English?","She spoke at the conference.","speak up","speak of","speaker","spoken"],
["read","/riːd/","v. 阅读；读懂","I love to read novels.","Can you read the sign?","read through","read between lines","reader","reading"],
["allow","/əˈlaʊ/","v. 允许；准许","Smoking is not allowed here.","Allow me to introduce myself.","allow for","","allowance","allowable"],
["add","/æd/","v. 添加；增加","Add some sugar to the tea.","The new wing was added to the building.","add up","add to","addition","additional"],
["spend","/spend/","v. 花费；度过","I spent 50 dollars on books.","We spent the summer in France.","spend time","spend money","spender","spending"],
["grow","/ɡrəʊ/","v. 生长；增长；种植","Plants need water to grow.","The company is growing fast.","grow up","grow into","growth","growing"],
["open","/ˈəʊpən/","v. 打开 a.开放的","Open the window please.","The store is open until 9 PM.","open up","open to","opener","opening"],
["walk","/wɔːk/","v./n. 走；散步","Let us walk to the park.","I take a walk every morning.","walk away","walk through","walker","walking"],
["win","/wɪn/","v. 赢得；获胜","Our team won the game.","She won first prize.","win over","win back","winner","winning"],
["offer","/ˈɒfər/","v./n. 提供；提议","He offered me a job.","I appreciate your kind offer.","offer to do","","offering",""],
["remember","/rɪˈmembər/","v. 记住；回忆","Remember to lock the door.","I remember my first day of school.","remember doing","","remembrance","memorable"],
["love","/lʌv/","v./n. 爱；热爱","I love my family.","She has a deep love for music.","fall in love","love for","lover","lovely"],
["consider","/kənˈsɪdər/","v. 考虑；认为","Please consider my proposal.","She is considered an expert.","consider doing","","consideration","considerate"],
["appear","/əˈpɪər/","v. 出现；似乎","A rainbow appeared in the sky.","He appears to be upset.","appear to","","appearance","disappear"],
["buy","/baɪ/","v. 购买","I want to buy a new phone.","She bought some groceries.","buy into","","buyer","buying"],
["wait","/weɪt/","v. 等待；等候","Wait for me please.","I cannot wait to see you.","wait for","wait up","waiter","waiting"],
["serve","/sɜːv/","v. 服务；提供；服役","Breakfast is served at 7 AM.","He served in the army for 5 years.","serve as","serve the purpose","server","service"],
["die","/daɪ/","v. 死；消失","Many soldiers died in the war.","The sound slowly died away.","die of","die out","death","deadly"],
["send","/send/","v. 发送；派遣","Send me an email.","They sent a rescue team.","send out","send for","sender","sending"],
["expect","/ɪkˈspekt/","v. 期望；预期","I expect to arrive by noon.","What did you expect?","expect to","","expectation","unexpected"],
["build","/bɪld/","v. 建造；建立","They built a new hospital.","We need to build trust.","build up","build on","builder","building"],
["stay","/steɪ/","v. 停留；保持","Stay here please.","The weather stayed sunny.","stay up","stay in touch","staying",""],
["fall","/fɔːl/","v./n. 落下；跌倒；秋天","The leaves fall in autumn.","He fell off his bike.","fall apart","fall in love","fallen","waterfall"],
["cut","/kʌt/","v. 切；削减；剪","Cut the cake into pieces.","The budget was cut by 20 percent.","cut down","cut off","cutter","cutting"],
["reach","/riːtʃ/","v. 到达；够到；联系","We reached the top of the mountain.","How can I reach you?","reach out","reach for","reachable",""],
["kill","/kɪl/","v. 杀死；扼杀","The frost killed the flowers.","Time to kill before the movie.","kill time","kill off","killer","killing"],
["remain","/rɪˈmeɪn/","v. 保持；剩余","Please remain seated.","Only a few tickets remain.","remain silent","","remainder","remaining"],
["suggest","/səˈdʒest/","v. 建议；暗示","I suggest we take a break.","What are you suggesting?","suggest doing","","suggestion","suggestive"],
["raise","/reɪz/","v. 举起；提高；抚养","Raise your hand if you know.","She raised three children.","raise money","raise awareness","raiser","raising"],
["pass","/pɑːs/","v. 通过；传递；经过","Please pass the salt.","Time passes quickly.","pass away","pass on","passer","passing"],
["sell","/sel/","v. 卖；出售","They sell fresh bread here.","The book sold a million copies.","sell out","sell off","seller","selling"],
["require","/rɪˈkwaɪər/","v. 需要；要求","This job requires experience.","What is required of me?","require to","","requirement","required"],
["report","/rɪˈpɔːt/","v./n. 报告；报道","Report the incident to the police.","The report shows progress.","report on","report back","reporter","reportedly"],
["decide","/dɪˈsaɪd/","v. 决定；裁决","We decided to go by train.","The judge will decide the case.","decide on","decide against","decision","decisive"],
["pull","/pʊl/","v./n. 拉；拖；吸引","Pull the door to open it.","The film pulled huge crowds.","pull off","pull through","puller","pulling"],
["develop","/dɪˈveləp/","v. 发展；开发；培养","The city developed rapidly.","She developed a new skill.","develop into","","development","developing"],
["produce","/prəˈdjuːs/","v. 生产；产生；制作","The factory produces cars.","The film produced by a small studio.","produce results","","producer","production"]
];