backend:
  name: github
  repo: Zero-light/my-electronic-blog
  branch: main

media_folder: public/images/uploads
public_folder: /images/uploads

site_url: https://www.zerolight.fun
locale: zh_Hans

collections:
  - name: profile
    label: 个人档案
    files:
      - name: profile_data
        label: 个人档案
        file: content/data/profile.json
        fields:
          - { label: 姓名, name: name, widget: string }
          - { label: 邮箱, name: email, widget: string }
          - { label: 个人简介, name: summary, widget: text }
