/**
 * Add example sentences to kaoyan_basic.json words
 * Run: node scripts/add_examples.js
 */
const fs = require('fs');

const examples = {
  'abandon': 'They had to abandon the sinking ship.',
  'absorb': 'Plants absorb nutrients from the soil.',
  'abstract': 'The concept is too abstract for beginners to understand.',
  'abuse': 'The system can be easily abused by dishonest users.',
  'academic': 'Her academic performance has improved significantly this semester.',
  'accelerate': 'The government plans to accelerate the economic reform.',
  'access': 'Students need access to the library resources.',
  'accommodate': 'The hotel can accommodate up to 500 guests.',
  'accompany': 'She will accompany me to the conference tomorrow.',
  'accomplish': 'We managed to accomplish the task ahead of schedule.',
  'account': 'You need to account for every expense in the report.',
  'accumulate': 'Dust tends to accumulate in unused rooms.',
  'accurate': 'We need more accurate data before making a decision.',
  'achieve': 'He worked hard to achieve his career goals.',
  'acknowledge': 'She refused to acknowledge her mistake in public.',
  'acquire': 'It takes years to acquire a new language fluently.',
  'adapt': 'Animals must adapt to their changing environment.',
  'adequate': 'The current measures are not adequate to solve the crisis.',
  'adjust': 'You may need to adjust your expectations accordingly.',
  'administer': 'The nurse will administer the medication every four hours.',
  'adopt': 'Many couples choose to adopt children from overseas.',
  'advocate': 'He is a strong advocate of renewable energy.',
  'affect': 'The new policy will affect millions of workers.',
  'aggressive': 'The company adopted an aggressive marketing strategy.',
  'allocate': 'The government will allocate more funds to education.',
  'alternative': 'We need to find an alternative solution to this problem.',
  'ambiguous': 'The contract language is ambiguous and open to interpretation.',
  'ambitious': 'She is an ambitious young entrepreneur with big dreams.',
  'analysis': 'A careful analysis of the data reveals interesting patterns.',
  'anticipate': 'We anticipate that sales will increase by 20% next quarter.',
  'apparent': 'It became apparent that the project was falling behind schedule.',
  'appeal': 'The charity launched an appeal for donations after the disaster.',
  'apply': 'You should apply for the scholarship before the deadline.',
  'approach': 'We need a completely new approach to tackle climate change.',
  'appropriate': 'Make sure to wear appropriate clothing for the interview.',
  'approve': 'The board is expected to approve the proposal next week.',
  'arise': 'Unexpected problems may arise during the construction.',
  'artificial': 'Artificial intelligence is transforming every industry.',
  'aspect': 'This is the most challenging aspect of the project.',
  'assemble': 'The team will assemble in the conference room at 9 AM.',
  'assess': 'We need to assess the potential risks before investing.',
  'assign': 'The manager will assign specific tasks to each team member.',
  'assist': 'Our staff will be happy to assist you with any questions.',
  'associate': 'People often associate success with hard work.',
  'assume': 'You should not assume that everyone agrees with you.',
  'assure': 'I can assure you that the product is completely safe.',
  'atmosphere': 'The restaurant has a warm and welcoming atmosphere.',
  'attach': 'Please attach your resume to the application form.',
  'attain': 'Few people attain true mastery in their field.',
  'attempt': 'This is our last attempt to resolve the dispute peacefully.',
  'attribute': 'She attributes her success to perseverance and luck.',
  'authority': 'The local authority is responsible for waste management.',
  'available': 'The report will be available to the public next Monday.',
  'aware': 'Are you aware of the potential dangers involved?',
  'barrier': 'Language barriers can make communication very difficult.',
  'behalf': 'I am speaking on behalf of the entire team.',
  'behave': 'Children are expected to behave well in public places.',
  'benefit': 'Regular exercise has numerous health benefits.',
  'boom': 'The tech industry experienced a massive boom in the 1990s.',
  'bound': 'The train is bound for London, departing in ten minutes.',
  'budget': 'We need to stay within the budget for this fiscal year.',
  'burden': 'The new tax will place a heavy burden on small businesses.',
  'campaign': 'The election campaign lasted for over six months.',
  'capacity': 'The stadium has a seating capacity of 50,000.',
  'capture': 'The photograph manages to capture the beauty of the moment.',
  'career': 'She decided to pursue a career in medicine.',
  'challenge': 'Learning a new language is a rewarding challenge.',
  'channel': 'We need to find better communication channels.',
  'characteristic': 'Patience is a key characteristic of a good teacher.',
  'circumstance': 'Under no circumstance should you reveal this information.',
  'claim': 'The company claims that their product is the most efficient.',
  'classify': 'It is difficult to classify this species of plant.',
  'collapse': 'The bridge could collapse under such heavy weight.',
  'combine': 'Combine the flour and sugar in a large bowl.',
  'comment': 'The official refused to comment on the ongoing investigation.',
  'commission': 'The commission will publish its findings next month.',
  'commit': 'We are fully committed to providing excellent service.',
  'communicate': 'It is essential to communicate your ideas clearly.',
  'community': 'The local community came together to help the victims.',
  'companion': 'A dog can be a loyal companion for many years.',
  'compare': 'You should compare prices before making a purchase.',
  'compensate': 'The company will compensate you for any damages.',
  'compete': 'Small businesses struggle to compete with large corporations.',
  'competitive': 'The industry is highly competitive and fast-moving.',
  'complain': 'Customers often complain about the long waiting time.',
  'complex': 'The human brain is an incredibly complex organ.',
  'component': 'Trust is an essential component of any relationship.',
  'comprehensive': 'The report provides a comprehensive overview of the market.',
  'concentrate': 'It is hard to concentrate with so much noise around.',
  'concept': 'The concept of time varies across different cultures.',
  'concern': 'Environmental protection is a major concern for many people.',
  'conclude': 'The meeting will conclude with a brief Q&A session.',
  'conduct': 'The scientist will conduct a series of experiments.',
  'conference': 'Over 1000 delegates attended the international conference.',
  'confident': 'She felt confident about passing the exam.',
  'confirm': 'Please confirm your attendance by the end of this week.',
  'conflict': 'The two countries have been in conflict for decades.',
  'confront': 'You need to confront your fears in order to overcome them.',
  'conscious': 'He was barely conscious after the accident.',
  'consequence': 'Every action has a consequence that must be considered.',
  'conserve': 'We should all try to conserve water and electricity.',
  'considerable': 'A considerable amount of money was spent on the project.',
  'consistent': 'Her performance has been remarkably consistent this season.',
  'constant': 'The constant noise from the construction site was unbearable.',
  'constitute': 'Women constitute nearly half of the workforce.',
  'construct': 'They plan to construct a new bridge across the river.',
  'consume': 'The average family consumes about 300 liters of water daily.',
  'contact': 'Please contact our customer service for further assistance.',
  'contemporary': 'The museum exhibits contemporary art from around the world.',
  'contribute': 'Everyone should contribute to keeping the environment clean.',
  'controversial': 'The new law remains highly controversial among citizens.',
  'convenient': 'Online shopping is far more convenient than going to stores.',
  'conventional': 'She chose an unconventional path instead of a conventional career.',
  'convince': 'He tried to convince me to invest in his startup.',
  'cooperate': 'The two companies agreed to cooperate on the research.',
  'coordinate': 'You need to coordinate your efforts with the rest of the team.',
  'corporation': 'The multinational corporation has offices in 30 countries.',
  'correspond': 'The results correspond closely with our initial predictions.',
  'create': 'Artists create works that inspire and provoke thought.',
  'crisis': 'The country is facing a severe economic crisis.',
  'critical': 'Your support is critical to the success of this project.',
  'crucial': 'The next 48 hours are crucial for the patient\'s recovery.',
  'cultivate': 'Reading widely helps to cultivate a rich vocabulary.',
  'current': 'The current situation requires immediate action.',
  'debate': 'There is an ongoing debate about climate change policy.',
  'decline': 'The company\'s profits have been in steady decline.',
  'defend': 'Every citizen has the right to defend themselves in court.',
  'define': 'How do you define success in your personal life?',
  'definitely': 'I will definitely attend your wedding next month.',
  'deliver': 'The courier will deliver the package by noon tomorrow.',
  'demand': 'There is a growing demand for renewable energy sources.',
  'demonstrate': 'The study demonstrates a clear link between diet and health.',
  'deny': 'The company continues to deny any wrongdoing.',
  'depend': 'The outcome will depend on various external factors.',
  'derive': 'Many English words derive from Latin and Greek roots.',
  'deserve': 'She deserves recognition for her years of hard work.',
  'desire': 'The desire for knowledge is a fundamental human trait.',
  'desperate': 'The refugees were in desperate need of food and shelter.',
  'despite': 'Despite the rain, the outdoor concert was a huge success.',
  'destroy': 'The fire managed to destroy over 200 hectares of forest.',
  'detect': 'The sensor can detect even the slightest movement.',
  'determine': 'A blood test will help determine the cause of the illness.',
  'device': 'This device can translate speech in real time.',
  'devote': 'He decided to devote his life to scientific research.',
  'digital': 'The digital revolution has changed how we work and live.',
  'discipline': 'Self-discipline is essential for academic achievement.',
  'display': 'The museum will display the artifacts for the first time.',
  'distinct': 'There is a distinct difference between the two proposals.',
  'distinguish': 'Color blindness makes it hard to distinguish red from green.',
  'distribute': 'Volunteers helped distribute food to the homeless.',
  'diverse': 'The city has a diverse population from many different cultures.',
  'domestic': 'The government focuses on both domestic and foreign affairs.',
  'dominate': 'One company continues to dominate the smartphone market.',
  'dramatic': 'There has been a dramatic increase in online learning.',
  'economic': 'The country is experiencing rapid economic growth.',
  'efficient': 'The new system is far more efficient than the old one.',
  'eliminate': 'The goal is to eliminate poverty within the next decade.',
  'embrace': 'We should embrace change rather than resist it.',
  'emerge': 'New evidence has emerged that could change the verdict.',
  'emergency': 'In case of emergency, please use the fire exit.',
  'emphasize': 'The teacher emphasized the importance of regular practice.',
  'employ': 'The factory plans to employ an additional 200 workers.',
  'enable': 'This scholarship will enable her to attend university.',
  'encounter': 'You may encounter unexpected challenges along the way.',
  'encourage': 'Parents should encourage their children to read more.',
  'enforce': 'The police are there to enforce the law fairly.',
  'engage': 'The speaker managed to engage the audience throughout.',
  'enhance': 'Regular exercise can enhance both physical and mental health.',
  'enormous': 'The project required an enormous amount of time and money.',
  'ensure': 'Please ensure that all doors are locked before leaving.',
  'enterprise': 'She started her own enterprise at the age of 25.',
  'environment': 'We must protect the environment for future generations.',
  'equip': 'The laboratory is fully equipped with modern instruments.',
  'essential': 'Water is absolutely essential for all forms of life.',
  'establish': 'The company was established in Boston in 1995.',
  'estimate': 'The total cost is estimated to be around $2 million.',
  'evaluate': 'The teacher will evaluate your progress every month.',
  'evidence': 'There is strong evidence linking smoking to lung cancer.',
  'evolution': 'The theory of evolution explains the diversity of life.',
  'exceed': 'The final cost should not exceed our original budget.',
  'exchange': 'The two leaders exchanged views on the trade agreement.',
  'exclude': 'The price excludes tax and delivery charges.',
  'execute': 'The plan was carefully thought out but poorly executed.',
  'exhibit': 'The gallery will exhibit paintings by local artists.',
  'expand': 'The company plans to expand into the Asian market next year.',
  'expectation': 'The product failed to meet customer expectations.',
  'exploit': 'We should exploit every opportunity to learn something new.',
  'explore': 'The team went to explore the uncharted region.',
  'export': 'The country exports coffee to over 50 countries worldwide.',
  'expose': 'The report exposes serious flaws in the current system.',
  'extend': 'We decided to extend our stay by another three days.',
  'extensive': 'She has extensive experience in the financial sector.',
  'external': 'External factors like weather can affect the results.',
  'extreme': 'The extreme weather conditions forced the event to be cancelled.',
  'facilitate': 'The new software is designed to facilitate online collaboration.',
  'factor': 'Price is just one factor to consider when buying a house.',
  'feature': 'The smartphone features an advanced facial recognition system.',
  'figure': 'A tall figure appeared at the doorway.',
  'finance': 'She works in the finance department of a large bank.',
  'flexible': 'The company offers flexible working hours to all employees.',
  'flourish': 'Small businesses can flourish with the right support.',
  'focus': 'We need to focus our efforts on the most urgent problems.',
  'forbid': 'The school rules forbid students from using phones in class.',
  'formal': 'Please use formal language when writing business emails.',
  'former': 'The former president made a rare public appearance.',
  'foundation': 'A solid educational foundation is crucial for future success.',
  'framework': 'The agreement provides a framework for future cooperation.',
  'frequent': 'Frequent exercise can significantly improve your health.',
  'fulfill': 'We strive to fulfill the needs of all our customers.',
  'function': 'The main function of the heart is to pump blood.',
  'fundamental': 'Freedom of speech is a fundamental human right.',
  'generate': 'The wind turbines generate enough electricity for the town.',
  'generous': 'She made a generous donation to the children\'s hospital.',
  'global': 'Climate change is a global issue that affects everyone.',
  'govern': 'New regulations govern the use of artificial intelligence.',
  'guarantee': 'The product comes with a one-year guarantee.',
  'handle': 'She knows how to handle difficult customers with patience.',
  'highlight': 'The report highlights several areas for improvement.',
  'identical': 'The two samples were found to be almost identical.',
  'identify': 'Police were able to identify the suspect from CCTV footage.',
  'ignore': 'You cannot simply ignore the warning signs.',
  'illustrate': 'Let me give an example to illustrate my point.',
  'impact': 'The pandemic had a massive impact on the global economy.',
  'implement': 'It will take months to implement the new policy properly.',
  'imply': 'His silence seemed to imply that he agreed with the decision.',
  'impose': 'The court may impose heavy fines on the company.',
  'income': 'She has a steady income from her freelance work.',
  'indicate': 'Recent polls indicate a shift in public opinion.',
  'individual': 'Each individual has the right to express their views.',
  'industrial': 'The city was once a major industrial center.',
  'inevitable': 'Some degree of change is inevitable in any organization.',
  'influence': 'Her work has had a profound influence on modern art.',
  'initial': 'The initial results of the experiment were very promising.',
  'innovation': 'Technological innovation is driving rapid social change.',
  'insight': 'The book provides valuable insight into human psychology.',
  'institution': 'Universities are institutions of higher learning and research.',
  'integrate': 'We need to integrate new technologies into our daily work.',
  'intellectual': 'Reading books is an excellent intellectual exercise.',
  'intense': 'The competition for the scholarship is extremely intense.',
  'interact': 'Children learn best when they interact with their environment.',
  'interpret': 'How do you interpret the poet\'s final message?',
  'invest': 'Many people choose to invest their savings in the stock market.',
  'investigate': 'The police are investigating the cause of the fire.',
  'involve': 'The project will involve a lot of teamwork and collaboration.',
  'isolate': 'The patient was isolated from others to prevent infection.',
  'issue': 'Climate change is one of the most pressing issues of our time.',
  'justify': 'How can you justify spending so much on a single item?',
  'keen': 'She has always been keen on learning new languages.',
  'launch': 'The company will launch its new product line next week.',
  'leading': 'She is one of the leading experts in her field.',
  'legal': 'You should seek legal advice before signing anything.',
  'liberal': 'He holds fairly liberal views on social issues.',
  'limitation': 'Every study has its limitations that must be acknowledged.',
  'maintain': 'It is important to maintain a healthy work-life balance.',
  'manipulate': 'Politicians often manipulate statistics to support their claims.',
  'manufacture': 'The factory manufactures parts for the automotive industry.',
  'massive': 'The earthquake caused massive destruction across the region.',
  'mechanism': 'Scientists are still studying the mechanism of the disease.',
  'mental': 'Mental health is just as important as physical health.',
  'military': 'The government increased military spending by 15%.',
  'moderate': 'Moderate exercise three times a week is best for health.',
  'monitor': 'Doctors will monitor the patient\'s condition overnight.',
  'motivate': 'A good leader knows how to motivate their team.',
  'negative': 'Try to turn negative experiences into learning opportunities.',
  'negotiate': 'The union is negotiating with management for better wages.',
  'nevertheless': 'It was raining hard; nevertheless, the match continued.',
  'notion': 'She rejected the notion that women are inferior to men.',
  'numerous': 'There are numerous reasons to start saving early.',
  'objective': 'The main objective of the meeting is to agree on a budget.',
  'obtain': 'You need a license to obtain certain chemicals.',
  'obvious': 'The solution to the problem seems obvious in retrospect.',
  'occupy': 'The protestors plan to occupy the square indefinitely.',
  'offend': 'He didn\'t mean to offend you with his comments.',
  'opponent': 'She defeated her opponent in the final round.',
  'opportunity': 'This internship is a great opportunity to gain experience.',
  'oppose': 'I strongly oppose any form of discrimination.',
  'option': 'We have no option but to cancel the event.',
  'original': 'The original version of the song is far better.',
  'outcome': 'The outcome of the election surprised many analysts.',
  'outline': 'Let me briefly outline the main points of the proposal.',
  'overcome': 'She managed to overcome her fear of public speaking.',
  'overseas': 'He worked overseas for five years before returning home.',
  'participate': 'All students are encouraged to participate in the discussion.',
  'particularly': 'I am particularly interested in modern Chinese history.',
  'passion': 'She has a genuine passion for teaching young children.',
  'peculiar': 'There was a peculiar smell coming from the basement.',
  'perform': 'The band will perform their latest songs at the concert.',
  'permanent': 'Are you looking for a permanent or temporary position?',
  'perspective': 'Traveling abroad gives you a new perspective on life.',
  'phenomenon': 'Globalization is a complex phenomenon with many facets.',
  'platform': 'The candidates outlined their policies on a public platform.',
  'policy': 'The new policy will take effect from January 1st.',
  'portion': 'A large portion of the budget goes to healthcare.',
  'potential': 'The young athlete shows great potential for the future.',
  'poverty': 'The organization works to alleviate poverty in rural areas.',
  'practical': 'We need a practical solution, not just theoretical ideas.',
  'precise': 'Can you give a more precise estimate of the cost?',
  'predict': 'It is impossible to predict the future with certainty.',
  'prejudice': 'We must fight against prejudice in all its forms.',
  'preserve': 'We should preserve these ancient buildings for future generations.',
  'pressure': 'Many students feel intense pressure to get good grades.',
  'previous': 'My previous job involved a lot of international travel.',
  'primary': 'The primary goal of education is to develop critical thinking.',
  'principle': 'He refused to compromise his principles for money.',
  'priority': 'Safety must always be our top priority.',
  'procedure': 'Please follow the standard procedure for filing a complaint.',
  'proceed': 'The meeting cannot proceed without the chairperson.',
  'process': 'Learning a new language is a slow and gradual process.',
  'productive': 'The meeting was highly productive and achieved its goals.',
  'profession': 'Teaching is a noble profession that shapes future generations.',
  'profit': 'The company reported a record profit for the third quarter.',
  'profound': 'The experience had a profound impact on her worldview.',
  'progress': 'We have made significant progress on the project.',
  'project': 'The construction project is expected to take three years.',
  'promote': 'The campaign aims to promote healthy eating habits.',
  'proper': 'Make sure you follow the proper channels for complaints.',
  'property': 'Intellectual property rights must be respected.',
  'proportion': 'A large proportion of the population lives in urban areas.',
  'propose': 'I propose that we postpone the meeting until next week.',
  'prospect': 'The prospect of working abroad is very exciting.',
  'prosperity': 'Economic prosperity benefits all members of society.',
  'purchase': 'You can purchase tickets online or at the door.',
  'pursue': 'She decided to pursue a career in scientific research.',
  'qualify': 'This degree will qualify you to work as a licensed engineer.',
  'range': 'The store offers a wide range of electronic products.',
  'rapid': 'The rapid development of AI raises important ethical questions.',
  'rational': 'Let\'s try to make a rational decision based on the facts.',
  'reality': 'The reality of the situation is far more complex.',
  'reasonable': 'We expect everyone to act in a reasonable manner.',
  'recognize': 'I didn\'t recognize her after all these years.',
  'recommend': 'I would highly recommend this restaurant to anyone.',
  'recover': 'It will take weeks for the patient to fully recover.',
  'reduce': 'We need to reduce our carbon emissions immediately.',
  'reflect': 'Your actions should reflect your values and beliefs.',
  'reform': 'The government promised to reform the education system.',
  'regard': 'I regard her as one of the finest writers of our time.',
  'register': 'Please register for the course before the deadline.',
  'regulate': 'The agency is responsible for regulating food safety.',
  'reinforce': 'Positive feedback can reinforce good behavior in children.',
  'reject': 'The committee decided to reject his application.',
  'release': 'The company will release its new software next month.',
  'relevant': 'Please only include information that is relevant to the topic.',
  'reliable': 'We need a reliable source of renewable energy.',
  'relieve': 'A warm bath can help relieve stress after a long day.',
  'rely': 'You should not rely too heavily on one source of income.',
  'remain': 'The situation remains tense after the failed negotiations.',
  'remarkable': 'She has made remarkable progress in just six months.',
  'remote': 'The village is located in a remote part of the mountains.',
  'replace': 'Machines cannot fully replace human creativity.',
  'represent': 'The lawyer will represent you in court.',
  'reputation': 'The company has built a solid reputation over the years.',
  'require': 'The job requires at least three years of experience.',
  'research': 'The research findings were published in a leading journal.',
  'resolve': 'We need to resolve this issue as quickly as possible.',
  'resource': 'Water is a precious resource that should not be wasted.',
  'respond': 'Please respond to the invitation by Friday.',
  'responsible': 'Who is responsible for making the final decision?',
  'restore': 'The church was carefully restored to its original condition.',
  'restrict': 'New laws restrict the use of plastic bags in supermarkets.',
  'reveal': 'The investigation may reveal new information about the case.',
  'revenue': 'Advertising revenue accounts for 80% of their income.',
  'reverse': 'The court decided to reverse the previous ruling.',
  'revolution': 'The internet has caused a revolution in communication.',
  'rival': 'The two companies are fierce rivals in the tech industry.',
  'route': 'What is the shortest route to the airport?',
  'routine': 'A morning routine can help you start the day productively.',
  'satellite': 'The satellite was launched into orbit last week.',
  'scale': 'The company plans to scale up its operations next year.',
  'schedule': 'The meeting has been scheduled for next Tuesday.',
  'security': 'Airport security has been significantly tightened.',
  'sensitive': 'She is very sensitive to criticism from others.',
  'severe': 'The region suffered severe flooding last summer.',
  'shift': 'There has been a significant shift in public attitudes.',
  'significant': 'There has been no significant improvement in his condition.',
  'similar': 'The two paintings are remarkably similar in style.',
  'source': 'Always cite your sources when writing academic papers.',
  'specific': 'Can you be more specific about your requirements?',
  'stable': 'The patient\'s condition is now stable after surgery.',
  'standard': 'We must maintain high standards of quality at all times.',
  'statistics': 'Official statistics show a decline in unemployment.',
  'status': 'Her status as a leading expert is widely recognized.',
  'strategy': 'The company needs a new strategy to stay competitive.',
  'stress': 'Learning to manage stress is an important life skill.',
  'structure': 'The organizational structure needs to be simplified.',
  'substantial': 'A substantial number of people voted against the proposal.',
  'sufficient': 'We have sufficient evidence to support our claim.',
  'supervise': 'An experienced engineer will supervise the construction.',
  'survey': 'A recent survey shows growing support for the policy.',
  'survive': 'Only a few species can survive in such extreme conditions.',
  'suspend': 'The company decided to suspend operations temporarily.',
  'sustain': 'The economy cannot sustain this level of growth forever.',
  'symbol': 'The dove is a universal symbol of peace.',
  'target': 'The government has set a target of zero emissions by 2050.',
  'technique': 'She uses a special technique to paint with watercolors.',
  'technology': 'Modern technology has changed the way we communicate.',
  'temporary': 'This is only a temporary solution to the problem.',
  'tendency': 'She has a tendency to worry too much about small things.',
  'terminal': 'The patient has been diagnosed with a terminal illness.',
  'threat': 'Cyber attacks pose a serious threat to national security.',
  'tolerate': 'We cannot tolerate any form of harassment in the workplace.',
  'trace': 'Police have been unable to trace the source of the call.',
  'tradition': 'It is a Chinese tradition to give red envelopes during New Year.',
  'transfer': 'You can transfer money between accounts online.',
  'transform': 'The new CEO plans to transform the company culture.',
  'transition': 'The country is in transition from a planned to a market economy.',
  'transport': 'Public transport is the most efficient way to get around the city.',
  'trend': 'The latest fashion trend seems to be minimalism.',
  'trigger': 'Certain foods can trigger allergic reactions in some people.',
  'ultimate': 'The ultimate goal is to create a sustainable future.',
  'undergo': 'The building will undergo major renovations next year.',
  'underline': 'The teacher underlined the key points on the board.',
  'undertake': 'The company will undertake a complete review of its policies.',
  'unique': 'Each person has a unique set of skills and experiences.',
  'urban': 'Urban areas are growing faster than rural areas.',
  'urge': 'I urge you to reconsider your decision carefully.',
  'utilize': 'We should utilize all available resources efficiently.',
  'valid': 'Your passport must be valid for at least six more months.',
  'variety': 'The shop offers a wide variety of fresh produce.',
  'version': 'The latest version of the app includes several new features.',
  'victim': 'The charity provides support for victims of domestic violence.',
  'virtue': 'Patience is a virtue that few people truly possess.',
  'visible': 'The mountain is clearly visible from the hotel window.',
  'vision': 'The company has a clear vision for the future.',
  'volume': 'Please turn down the volume on the television.',
  'volunteer': 'Many people volunteer at local charities on weekends.',
  'welfare': 'The government is responsible for the welfare of its citizens.',
  'widespread': 'There is widespread concern about the state of the economy.',
  'witness': 'Several people were called to testify as witnesses in court.',
  'worthwhile': 'The effort was definitely worthwhile in the end.',
  'yield': 'The negotiations failed to yield any significant results.',
};

// Load and patch
const data = JSON.parse(fs.readFileSync('public/assets/words/kaoyan_basic.json', 'utf-8'));
let count = 0;
for (const w of data.words) {
  if (examples[w.word] && !w.example) {
    w.example = examples[w.word];
    count++;
  }
}

fs.writeFileSync('public/assets/words/kaoyan_basic.json', JSON.stringify(data, null, 2), 'utf-8');
console.log(`Added ${count} example sentences to kaoyan_basic.json`);
