// Extra 2000+ advanced words (CET6/TOEFL/IELTS/GRE) with POS info
// Format: word|POS|meaning
module.exports=`
abbreviate|v|缩写，缩短
abide|v|忍受；遵守
abolish|v|废除
abortion|n|流产；失败
abound|v|大量存在
abrasion|n|磨损
abreast|adv|并排
abridge|v|删节
abrupt|a|突然的
abstain|v|戒除
absurd|a|荒谬的
acclaim|v|欢呼
accomplice|n|共犯
accost|v|搭话
accountable|a|有责任的
accrue|v|积累
accusation|n|指控
acquaint|v|使熟悉
acquit|v|宣判无罪
acrimony|n|尖刻
activate|v|激活
activist|n|活动家
acumen|n|敏锐
adamant|a|坚决的
addict|n|上瘾者
adhere|v|粘附；坚持
adjacent|a|邻近的
adjoin|v|毗邻
adjourn|v|休会
adjudicate|v|裁决
adjunct|n|附属物
administer|v|管理
adolescent|n|青少年
adorn|v|装饰
adroit|a|灵巧的
adulate|v|谄媚
adulterate|v|掺假
advent|n|到来
adversary|n|对手
adversity|n|逆境
advocate|v|提倡 n.倡导者
aerial|a|空中的
aesthetic|a|美学的
affable|a|和蔼的
affidavit|n|宣誓书
affiliate|v|附属
affinity|n|密切关系
affirm|v|肯定
afflict|v|折磨
affluent|a|富裕的
agenda|n|议程
aggravate|v|加重
aggregate|v|聚集 n.合计
agitate|v|鼓动
agony|n|极大痛苦
albeit|conj|虽然
alien|a|外国的 n.外星人
alienate|v|疏远
allege|v|指控
allegiance|n|忠诚
alleviate|v|减轻
allot|v|分配
allude|v|暗示
allure|v|诱惑
ally|n|盟友
aloft|adv|在高处
altercation|n|争吵
altruism|n|利他主义
amass|v|积聚
ambience|n|氛围
ambivalent|a|矛盾的
ameliorate|v|改善
amenable|a|顺从的
amiable|a|友好的
amid|prep|在...之中
amnesia|n|健忘症
amnesty|n|大赦
amorphous|a|无定形的
ample|a|充足的
amplify|v|放大
anagram|n|变位词
analogy|n|类比
anarchist|n|无政府主义者
ancestor|n|祖先
ancillary|a|辅助的
anecdote|n|轶事
anguish|n|痛苦
animate|v|使活泼
annex|v|吞并
annotate|v|注释
anomaly|n|异常
anonymous|a|匿名的
antagonism|n|对抗
anthology|n|选集
anticipate|v|预期
antidote|n|解毒剂
antipathy|n|反感
antiquated|a|过时的
antithesis|n|对立面
apathetic|a|冷漠的
apex|n|顶点
appall|v|使惊骇
apparel|n|服装
appease|v|安抚
applaud|v|鼓掌
appraise|v|评价
appreciable|a|可感知的
apprehend|v|逮捕；理解
apprentice|n|学徒
apt|a|恰当的
arbitrary|a|武断的
arbitrate|v|仲裁
arcane|a|神秘的
archive|n|档案
ardent|a|热情的
arduous|a|艰巨的
aristocrat|n|贵族
armament|n|军备
aroma|n|芳香
arouse|v|唤起
arraign|v|传讯
array|n|阵列
arrogant|a|傲慢的
articulate|v|清楚表达 a.口齿伶俐的
artifact|n|手工艺品
ascend|v|上升
ascertain|v|查明
ascribe|v|归因于
aspiration|n|抱负
aspire|v|渴望
assail|v|攻击
assassinate|v|暗杀
assent|v|同意
assert|v|断言
assiduous|a|勤奋的
assimilate|v|同化
astound|v|使震惊
astute|a|精明的
asylum|n|庇护
atrocity|n|暴行
attentive|a|注意的
attenuate|v|减弱
attest|v|证明
audacious|a|大胆的
audit|v|审计 n.查账
augment|v|增加
auspicious|a|吉利的
austere|a|朴素的
authentic|a|真正的
authoritarian|a|专制的
autonomous|a|自治的
avail|v|有利于
avalanche|n|雪崩
avant-garde|n|先锋派
avarice|n|贪婪
avenge|v|为...报仇
averse|a|反对的
avid|a|渴望的
avow|v|承认
awe|n|敬畏
baffle|v|使困惑
bail|n|保释
balk|v|犹豫
ballot|n|投票
banal|a|平庸的
bane|n|祸根
banish|v|放逐
bankrupt|a|破产的
barbaric|a|野蛮的
barren|a|贫瘠的
bastion|n|堡垒
beacon|n|灯塔
beguile|v|欺骗
behold|v|看见
belligerent|a|好战的
bemoan|v|哀叹
benevolent|a|慈善的
benign|a|良性的
bequeath|v|遗赠
berate|v|严厉指责
bereave|v|使丧失
beset|v|困扰
bestow|v|授予
betray|v|背叛
bewilder|v|使困惑
bias|n|偏见 v.使有偏见
bifurcate|v|分叉
bilateral|a|双边的
bizarre|a|奇异的
bland|a|温和的
blandishment|n|奉承
blasphemy|n|亵渎
blatant|a|公然的
bleak|a|暗淡的
blemish|n|瑕疵
bless|v|祝福
blight|n|枯萎病
bliss|n|极乐
blithe|a|快乐的
blunder|n|大错
blunt|a|钝的
blur|v|模糊
bolster|v|支持
bombard|v|轰炸
bond|n|纽带；债券
bonus|n|奖金
boom|n|繁荣
boon|n|恩惠
bourgeois|a|资产阶级的
bout|n|一阵
boycott|v|抵制
brace|v|支撑
brazen|a|厚颜无耻的
breach|n|违反 v.打破
breathtaking|a|惊人的
brew|v|酿造
brink|n|边缘
brisk|a|轻快的
bristle|v|发怒
brittle|a|易碎的
broach|v|提出
brood|v|沉思
browse|v|浏览
bruise|n|淤伤
brunt|n|冲击
brusque|a|唐突的
budge|v|让步
buoyant|a|有浮力的；乐观的
bureaucracy|n|官僚机构
burgeon|v|迅速生长
burrow|v|挖掘
bustle|v|忙碌
buttress|n|扶壁 v.支持
bypass|v|绕过
cabal|n|阴谋集团
cache|n|隐藏处
cajole|v|哄骗
calamity|n|灾难
caliber|n|才干
callous|a|冷酷的
camaraderie|n|友情
camouflage|n|伪装
candid|a|坦率的
candor|n|坦率
canny|a|精明的
canvas|n|帆布
capitulate|v|投降
capricious|a|反复无常的
captivate|v|迷住
cardinal|a|主要的
caress|v|爱抚
caricature|n|漫画
carnage|n|大屠杀
carve|v|雕刻
cascade|n|瀑布
caste|n|种姓
cataclysm|n|大灾难
catalyst|n|催化剂
catastrophe|n|大灾难
categorical|a|绝对的
caustic|a|腐蚀性的
caveat|n|警告
cease|v|停止
cede|v|割让
celestial|a|天上的
censure|v|责难
cerebral|a|大脑的
certitude|n|确信
chagrin|n|懊恼
champion|v|拥护
chaos|n|混乱
charisma|n|魅力
chasm|n|深坑
chaste|a|贞洁的
chide|v|责骂
chivalry|n|骑士精神
chronic|a|慢性的
chronicle|n|编年史
chunk|n|大块
circuitous|a|迂回的
circumscribe|v|限制
circumspect|a|谨慎的
circumvent|v|规避
cite|v|引用
civil|a|公民的；文明的
clairvoyant|a|有洞察力的
clamor|n|喧闹
clandestine|a|秘密的
clarity|n|清晰
clash|n|冲突
cleave|v|劈开
clemency|n|仁慈
clientele|n|客户
climax|n|高潮
cling|v|粘住
clip|v|剪
cloak|v|掩盖
clog|v|阻塞
clone|n|克隆
clumsy|a|笨拙的
coalition|n|联盟
coax|v|哄骗
coerce|v|强迫
cogent|a|有说服力的
cognitive|a|认知的
coherent|a|连贯的
coincide|v|同时发生
collaborate|v|合作
collateral|n|抵押品
colloquial|a|口语的
collusion|n|勾结
colossal|a|巨大的
combat|v|战斗
combustion|n|燃烧
commemorate|v|纪念
commence|v|开始
commend|v|赞扬
commensurate|a|相称的
commodity|n|商品
commonplace|a|平凡的
communal|a|公共的
compact|a|紧凑的
compassion|n|同情
compatible|a|兼容的
compel|v|强迫
compendium|n|概要
complacent|a|自满的
complement|v|补充 n.补足物
compliant|a|顺从的
complicity|n|共谋
composure|n|镇定
compound|n|化合物 a.复合的
comprehend|v|理解
compulsory|a|强制性的
concede|v|承认
conceit|n|自负
conceive|v|构想
concession|n|让步
conciliate|v|安抚
concise|a|简洁的
concur|v|同意
condemn|v|谴责
condone|v|宽恕
conducive|a|有益的
confess|v|坦白
confide|v|倾诉
configuration|n|配置
confiscate|v|没收
conform|v|遵守
confound|v|混淆
congenial|a|意气相投的
congestion|n|拥堵
congregate|v|聚集
conjecture|n|推测
conjure|v|变魔术
connive|v|密谋
connoisseur|n|鉴赏家
conscientious|a|认真的
consensus|n|共识
console|v|安慰
conspicuous|a|显眼的
conspire|v|密谋
constituent|n|成分
construe|v|解释
contagious|a|传染的
contaminate|v|污染
contemplate|v|沉思
contempt|n|轻视
contend|v|竞争；主张
contentious|a|有争议的
contingent|a|依情况而定的
contrive|v|发明
convene|v|召集
converge|v|汇聚
converse|v|交谈
conviction|n|定罪；坚信
copious|a|丰富的
cordial|a|热诚的
correlate|v|关联
corroborate|v|证实
corrode|v|腐蚀
corrupt|a|腐败的
cosmopolitan|a|世界性的
counsel|n|劝告 v.建议
counteract|v|抵消
counterfeit|a|伪造的
counterpart|n|对应的人或物
covert|a|隐蔽的
covet|v|垂涎
cradle|n|摇篮
craft|n|手艺 v.精心制作
crave|v|渴望
credential|n|凭证
credible|a|可信的
creed|n|信条
cringe|v|畏缩
criterion|n|标准
crouch|v|蹲伏
crucial|a|关键性的
crude|a|粗糙的；天然的
crumble|v|崩溃
crusade|n|改革运动
culminate|v|达到顶点
culprit|n|罪犯
cumulative|a|累积的
cunning|a|狡猾的
curb|v|抑制
curtail|v|缩短
custodian|n|保管人
cynical|a|愤世嫉俗的
dabble|v|涉猎
dainty|a|精致的
dangle|v|悬挂
dearth|n|缺乏
debacle|n|崩溃
debilitate|v|使虚弱
debut|n|首次亮相
decadence|n|颓废
deceit|n|欺骗
decipher|v|破译
decisive|a|决定性的
decorum|n|礼仪
decree|n|法令 v.颁布
decrepit|a|衰老的
dedicate|v|致力于
deduce|v|推断
deem|v|认为
default|n|默认 v.违约
defer|v|推迟；遵从
defiance|n|违抗
deficit|n|赤字
definitive|a|决定性的
deflect|v|使偏转
deft|a|灵巧的
defunct|a|已不存在的
defy|v|违抗
delegate|n|代表 v.委派
delete|v|删除
deleterious|a|有害的
deliberate|a|故意的
delicacy|n|精致
delinquent|a|违法的
delirious|a|神志不清的
delude|v|欺骗
deluge|n|洪水
delve|v|探究
demise|n|死亡
demographic|a|人口统计的
demolish|v|拆除
demure|a|端庄的
denounce|v|谴责
depict|v|描绘
deplete|v|耗尽
deplore|v|谴责
deploy|v|部署
depose|v|罢免
depreciate|v|贬值
deprive|v|剥夺
derelict|a|弃置的
deride|v|嘲笑
descend|v|下降
desecrate|v|亵渎
designate|v|指定
desist|v|停止
desolate|a|荒凉的
despise|v|鄙视
destitute|a|赤贫的
detach|v|分离
detain|v|拘留
deter|v|阻止
detergent|n|清洁剂
deteriorate|v|恶化
detest|v|憎恶
detriment|n|损害
devastate|v|毁灭
deviate|v|偏离
devious|a|狡猾的
devise|v|设计
devoid|a|缺乏的
devour|v|吞食
dexterity|n|灵巧
diagnose|v|诊断
didactic|a|说教的
differentiate|v|区分
diffuse|v|扩散
digress|v|离题
dilapidated|a|破旧的
dilate|v|扩大
dilemma|n|困境
diligent|a|勤奋的
dilute|v|稀释
diminish|v|减少
diplomatic|a|外交的
dire|a|可怕的
discern|v|辨别
disclose|v|揭露
discord|n|不和
discreet|a|谨慎的
discrepancy|n|差异
disdain|v|鄙视
dismantle|v|拆除
dismay|n|沮丧
dispatch|v|派遣
dispel|v|驱散
dispense|v|分配
disperse|v|分散
displace|v|取代
dispose|v|处理
dispute|n/v|争论
disrupt|v|扰乱
disseminate|v|传播
dissent|v|不同意
dissipate|v|消散
dissolve|v|溶解
dissonance|n|不和谐
distill|v|蒸馏；提炼
distort|v|扭曲
divert|v|转移
divest|v|剥夺
divulge|v|泄露
docile|a|温顺的
doctrine|n|教条
dogma|n|教条
domain|n|领域
domestic|a|国内的；家庭的
donate|v|捐赠
dormant|a|休眠的
drastic|a|激烈的
dread|v|恐惧
drought|n|干旱
dubious|a|可疑的
duplicate|v|复制
dwarf|v|使相形见绌
dwell|v|居住
dwindle|v|缩小
dynamic|a|动态的；有活力的
earnest|a|认真的
eccentric|a|古怪的
eclipse|v|使黯然失色
ecstasy|n|狂喜
edifice|n|大厦
efface|v|抹去
efficacious|a|有效的
egalitarian|a|平等主义的
elaborate|a|精心制作的
elapse|v|流逝
elated|a|兴高采烈的
elegant|a|优雅的
elicit|v|引出
eligible|a|有资格的
elite|n|精英
eloquent|a|雄辩的
elucidate|v|阐明
elude|v|躲避
emaciated|a|消瘦的
emanate|v|散发
embargo|n|禁运
embark|v|开始
embed|v|嵌入
embellish|v|装饰
embezzle|v|挪用
embody|v|体现
embrace|v|拥抱；包含
embryo|n|胚胎
eminent|a|杰出的
empathy|n|同理心
empirical|a|经验主义的
empower|v|授权
emulate|v|模仿
enact|v|颁布
enchant|v|使着迷
encompass|v|包含
endanger|v|危及
endorse|v|支持
endow|v|赋予
endure|v|忍受
enigma|n|谜
enlighten|v|启发
enmity|n|敌意
enormity|n|巨大
enrage|v|激怒
enrich|v|使丰富
ensue|v|继而发生
entail|v|需要
entangle|v|缠住
enthrall|v|迷住
entice|v|诱惑
entity|n|实体
entrench|v|确立
entrepreneur|n|企业家
envision|v|想象
ephemeral|a|短暂的
epitome|n|典范
equitable|a|公平的
equivocal|a|模棱两可的
eradicate|v|根除
erode|v|侵蚀
erratic|a|不稳定的
escalate|v|升级
eschew|v|回避
espionage|n|间谍活动
essence|n|本质
esteem|v|尊重
eternal|a|永恒的
ethereal|a|缥缈的
ethical|a|伦理的
ethnic|a|民族的
evacuate|v|疏散
evade|v|逃避
evoke|v|唤起
exacerbate|v|恶化
exalt|v|赞扬
exasperate|v|激怒
excavate|v|挖掘
excel|v|擅长
excerpt|n|摘录
exclaim|v|呼喊
exempt|v|免除
exert|v|施加
exhilarate|v|使兴奋
exonerate|v|免除责任
exorbitant|a|过高的
expedite|v|加速
expel|v|驱逐
expertise|n|专长
expire|v|到期
explicit|a|明确的
exquisite|a|精致的
extemporize|v|即兴发言
extol|v|赞美
extort|v|勒索
extract|v|提取 n.摘录
extraneous|a|无关的
extravagant|a|奢侈的
extricate|v|解救
exuberant|a|热情洋溢的
fabricate|v|制造；捏造
facet|n|方面
facsimile|n|复制品
fallacy|n|谬误
falter|v|犹豫
famine|n|饥荒
fanatic|n|狂热者
fascinate|v|使着迷
fathom|v|理解
fatigue|n|疲劳
fatuous|a|愚蠢的
feasible|a|可行的
feat|n|功绩
fecund|a|多产的
feign|v|假装
ferocious|a|凶猛的
fervent|a|热情的
fiasco|n|惨败
fickle|a|易变的
fidelity|n|忠诚
fiery|a|火热的
fiscal|a|财政的
flagrant|a|公然的
flamboyant|a|华丽的
flaunt|v|炫耀
flaw|n|缺陷
fledgling|n|新手
flimsy|a|脆弱的
flock|n|群 v.聚集
fluctuate|v|波动
fluent|a|流利的
foe|n|敌人
forbear|v|克制
ford|v|涉水
foremost|a|最重要的
forfeit|v|丧失
forge|v|锻造；伪造
formidable|a|可怕的
forsake|v|抛弃
forthcoming|a|即将到来的
fortify|v|加强
fortitude|n|坚韧
foster|v|培养
fracture|n|骨折
fragile|a|脆弱的
fragment|n|碎片
franchise|n|特许经营权
frantic|a|疯狂的
fraud|n|欺诈
fraught|a|充满的
friction|n|摩擦
fringe|n|边缘
frugal|a|节俭的
fruitful|a|富有成效的
frustrate|v|使沮丧
fugitive|n|逃犯
fumble|v|摸索
furious|a|暴怒的
furnish|v|提供
futile|a|徒劳的
gait|n|步态
galvanize|v|激励
gamble|v|赌博
garment|n|衣服
garnish|v|装饰
gauge|v|测量
gaze|v|凝视
generic|a|通用的
genesis|n|起源
genial|a|友好的
genuine|a|真正的
gesture|n|手势
gigantic|a|巨大的
gist|n|要点
glamour|n|魅力
glare|v|怒视
glean|v|收集
glib|a|口齿伶俐的
glimpse|n|一瞥
gloat|v|幸灾乐祸
gloom|n|忧郁
gloss|n|光泽
glut|n|过剩
gnaw|v|啃
gorge|n|峡谷
gossip|n|流言蜚语
gracious|a|亲切的
graft|n|嫁接
grandeur|n|壮丽
grapple|v|扭打
grateful|a|感激的
gratify|v|使满足
gravity|n|重力；严重性
graze|v|放牧；擦伤
gregarious|a|群居的
grief|n|悲伤
grievance|n|不平
grim|a|严酷的
grin|v|咧嘴笑
grip|v|紧握
grit|n|毅力
groan|v|呻吟
grope|v|摸索
gross|a|总的；毛的
grotesque|a|怪异的
grove|n|小树林
grudge|n|怨恨
gruesome|a|可怕的
gruff|a|粗鲁的
guile|n|狡猾
gullible|a|易受骗的
gush|v|涌出
gust|n|阵风
habitat|n|栖息地
hackneyed|a|陈腐的
hail|v|欢呼
hallmark|n|标志
halt|v|停止
hamper|v|阻碍
handicap|n|障碍
haphazard|a|随意的
harass|v|骚扰
harbinger|n|预兆
harbor|v|窝藏
hardy|a|耐寒的
harmonious|a|和谐的
harness|v|利用
harsh|a|严厉的
hasten|v|加速
hatch|v|孵化
haunt|v|萦绕
havoc|n|浩劫
hazard|n|危险
headstrong|a|任性的
heal|v|治愈
hectic|a|繁忙的
heed|v|注意
heighten|v|提高
heinous|a|极恶的
heir|n|继承人
herald|v|预报
hereditary|a|遗传的
heresy|n|异端
heritage|n|遗产
hibernate|v|冬眠
hideous|a|丑陋的
hierarchy|n|等级制度
hike|v/n|远足；涨价
hinder|v|阻碍
hitherto|adv|迄今
hoard|v|囤积
hoax|n|骗局
holistic|a|整体的
homage|n|敬意
homicide|n|杀人
homogeneous|a|同质的
horizon|n|地平线
horrendous|a|可怕的
hostile|a|敌对的
hub|n|中心
humane|a|人道的
humble|a|谦逊的
humid|a|潮湿的
humiliate|v|羞辱
hurl|v|猛投
hustle|v|催促
hybrid|n|混合物
hygiene|n|卫生
hype|n|炒作
hypocrisy|n|虚伪
hypothesis|n|假设
hysterical|a|歇斯底里的
icon|n|偶像
idealize|v|理想化
ideology|n|意识形态
idiosyncrasy|n|特质
idle|a|空闲的
ignite|v|点燃
illicit|a|非法的
illuminate|v|照亮
illusion|n|幻觉
immaculate|a|完美的
immense|a|巨大的
immerse|v|沉浸
imminent|a|即将发生的
immune|a|免疫的
impair|v|损害
impart|v|传授
impartial|a|公正的
impasse|n|僵局
impeach|v|弹劾
impeccable|a|无瑕疵的
impede|v|阻碍
impending|a|逼近的
imperative|a|必要的
imperial|a|帝国的
impervious|a|不受影响的
impetus|n|推动力
implant|v|植入
implicit|a|含蓄的
implore|v|恳求
impoverish|v|使贫穷
impregnable|a|坚不可摧的
improvise|v|即兴创作
imprudent|a|不谨慎的
impudent|a|无礼的
impulse|n|冲动
inadvertent|a|无意的
inaugurate|v|就职；开创
incense|v|激怒
inception|n|开端
incessant|a|不断的
incite|v|煽动
inclination|n|倾向
inclusive|a|包容的
incognito|a|隐姓埋名的
incoherent|a|不连贯的
increment|n|增加
incumbent|a|有义务的
incur|v|招致
indelible|a|不可磨灭的
indict|v|起诉
indifferent|a|漠不关心的
indigenous|a|本土的
indignant|a|愤慨的
indispensable|a|不可或缺的
indolent|a|懒惰的
indulge|v|沉溺
industrious|a|勤劳的
inept|a|无能的
inert|a|惰性的
infamous|a|臭名昭著的
infiltrate|v|渗透
infinite|a|无限的
inflate|v|膨胀
inflict|v|造成
influx|n|涌入
infringe|v|侵犯
ingenious|a|精巧的
inhabit|v|居住
inherent|a|固有的
inhibit|v|抑制
inject|v|注射
innate|a|天生的
innocuous|a|无害的
innovative|a|创新的
inquisitive|a|好问的
insatiable|a|不知足的
inscribe|v|刻写
insidious|a|暗中为害的
insolent|a|无礼的
instantaneous|a|瞬间的
instigate|v|煽动
instill|v|灌输
insulate|v|隔离
insult|v/n|侮辱
insurgent|n|叛乱者
intact|a|完整的
intangible|a|无形的
integral|a|完整的；必需的
intelligible|a|可理解的
intercept|v|拦截
interim|a|暂时的 n.过渡期
intermittent|a|间歇的
intricate|a|复杂的
intrinsic|a|固有的
intuition|n|直觉
inundate|v|淹没
invade|v|入侵
inventory|n|库存
invoke|v|调用
irony|n|讽刺
irreverent|a|不敬的
irrevocable|a|不可撤销的
itinerant|a|流动的
jargon|n|行话
jeopardize|v|危及
jerk|v|猛拉
jolt|v|震动
jovial|a|快活的
jubilant|a|欢欣鼓舞的
judicious|a|明智的
juncture|n|时刻
jurisdiction|n|管辖权
juxtapose|v|并列
keen|a|热衷的；敏锐的
kindle|v|点燃
kinship|n|亲属关系
knack|n|诀窍
laborious|a|费力的
labyrinth|n|迷宫
lackluster|a|无光泽的
lament|v|哀悼
languish|v|憔悴
lapse|n|失误
latent|a|潜在的
laud|v|赞美
lavish|a|奢侈的
lax|a|松懈的
legacy|n|遗产
legible|a|清晰的
legislate|v|立法
legitimate|a|合法的
lenient|a|宽大的
lethal|a|致命的
lethargic|a|昏睡的
levy|v|征收
liable|a|有责任的
liberal|a|自由的；慷慨的
likelihood|n|可能性
limelight|n|公众关注
linger|v|逗留
linguistic|a|语言学的
litigation|n|诉讼
loathe|v|厌恶
lofty|a|崇高的
loll|v|懒洋洋
loom|v|逼近
loot|v|抢劫
lucid|a|清晰的
lucrative|a|有利可图的
lull|v|使安静
luminous|a|发光的
lunatic|n|疯子
lure|v|诱惑
lurk|v|潜伏
luscious|a|甘美的
lush|a|茂盛的
lust|n|强烈欲望
luxurious|a|豪华的
magnanimous|a|宽宏大量的
magnate|n|大亨
magnificent|a|壮丽的
magnitude|n|大小；重要性
makeshift|a|临时的
malady|n|疾病
malice|n|恶意
malignant|a|恶性的
malleable|a|可塑的
malpractice|n|渎职
mandate|n|授权 v.强制执行
mandatory|a|强制的
manifest|v|显示 a.明显的
manifold|a|多种的
marine|a|海洋的
marvel|n|奇迹
massacre|n|大屠杀
masterpiece|n|杰作
materialize|v|实现
meager|a|贫乏的
mediate|v|调解
medieval|a|中世纪的
mediocre|a|平庸的
melancholy|n|忧郁
menace|n|威胁
mentor|n|导师
mercenary|a|唯利是图的
merge|v|合并
merit|n|优点 v.值得
meticulous|a|一丝不苟的
metropolis|n|大都市
militant|a|好战的
mingle|v|混合
miniature|n|缩影 a.微型的
minimal|a|最小的
mirage|n|海市蜃楼
mischievous|a|恶作剧的
misconception|n|误解
misery|n|痛苦
mitigate|v|减轻
mock|v|嘲笑
modest|a|谦虚的；适度的
molest|v|骚扰
momentum|n|动力
monetary|a|货币的
monopoly|n|垄断
monotonous|a|单调的
monumental|a|巨大的
morbid|a|病态的
moribund|a|垂死的
mortal|a|致命的
mortgage|n|抵押贷款
mundane|a|平凡的
municipal|a|市政的
muse|v|沉思
muster|v|召集
mystify|v|使困惑
myth|n|神话
naive|a|天真的
narcissist|n|自恋者
narrative|n|叙述
nasty|a|肮脏的；令人不快的
negate|v|否定
neglect|v/n|忽视
negligible|a|可忽略的
nemesis|n|报应
nostalgia|n|怀旧
notorious|a|臭名昭著的
novel|a|新颖的
novice|n|新手
nuance|n|细微差别
nucleus|n|核心
nurture|v|培养
oath|n|誓言
obese|a|肥胖的
obituary|n|讣告
obligatory|a|强制性的
oblige|v|迫使
obliterate|v|抹去
oblivious|a|未察觉的
obscene|a|淫秽的
obscure|a|模糊的
obsess|v|使着迷
obsolete|a|过时的
obstinate|a|固执的
obstruct|v|阻碍
odds|n|可能性
offend|v|冒犯
ominous|a|不祥的
onset|n|开始
opaque|a|不透明的
oppress|v|压迫
optimistic|a|乐观的
optimum|a|最优的
opulent|a|富裕的
ordeal|n|磨难
orient|v|使朝向
ornament|n|装饰品
orthodox|a|正统的
oscillate|v|摆动
ostensible|a|表面的
oust|v|驱逐
outrage|n|愤怒
oversee|v|监督
overt|a|公开的
overwhelm|v|压倒
pacify|v|使平静
palatable|a|可口的
pamper|v|纵容
panacea|n|万能药
pandemic|n|大流行病
panic|n|恐慌
paradigm|n|范例
paradox|n|悖论
paramount|a|至关重要的
parasite|n|寄生虫
partisan|a|偏袒的
patent|n|专利 a.专利的
pathetic|a|可怜的
patron|n|赞助人
paucity|n|缺乏
peasant|n|农民
peculiar|a|特有的；奇怪的
pedestrian|a|平淡的
peel|v|剥皮
peer|n|同龄人 v.凝视
penalize|v|处罚
pending|a|未决定的
penetrate|v|穿透
penitent|a|悔过的
perceive|v|感知
perennial|a|常年的
peril|n|危险
peripheral|a|外围的
perish|v|死亡
permeate|v|弥漫
perpetrate|v|犯（罪）
perpetual|a|永久的
perplex|v|使困惑
persecute|v|迫害
persevere|v|坚持
persist|v|坚持
pertain|v|关于
pertinent|a|相关的
perturb|v|使不安
pervasive|a|普遍的
pessimistic|a|悲观的
petition|n|请愿书
petty|a|琐碎的
phase|n|阶段
philanthropy|n|慈善
phobia|n|恐惧症
piety|n|虔诚
pillar|n|支柱
pinnacle|n|顶峰
pioneer|n|先驱
pious|a|虔诚的
pivotal|a|关键的
placate|v|安抚
placid|a|平静的
plague|n|瘟疫
plausible|a|似乎合理的
plead|v|恳求
pledge|n|誓言 v.保证
plentiful|a|丰富的
plight|n|困境
plummet|v|暴跌
plunder|v|掠夺
poignant|a|辛酸的
poise|n|镇静
polarize|v|两极化
ponder|v|沉思
portray|v|描绘
posterity|n|后代
potent|a|有效的
pragmatic|a|务实的
preamble|n|序言
precarious|a|不稳定的
precaution|n|预防措施
precede|v|在...之前
precedent|n|先例
precipitate|v|促成
preclude|v|排除
predecessor|n|前任
predicament|n|困境
predominant|a|主要的
preeminent|a|卓越的
preface|n|前言
premise|n|前提
premium|n|保险费 a.高级的
preoccupy|v|使全神贯注
prerequisite|n|先决条件
prerogative|n|特权
prescribe|v|规定；开药方
prestige|n|声望
presume|v|假定
pretentious|a|做作的
prevail|v|盛行
prevalent|a|普遍的
primitive|a|原始的
probe|v/n|探测
proclaim|v|宣布
prodigy|n|奇才
proficient|a|熟练的
prolific|a|多产的
prolong|v|延长
prominent|a|突出的
prone|a|有...倾向的
propagate|v|传播
propel|v|推进
prophet|n|先知
proponent|n|支持者
prosecute|v|起诉
protagonist|n|主角
protocol|n|协议
provoke|v|激怒
proximity|n|接近
prudent|a|谨慎的
pseudonym|n|笔名
punctual|a|准时的
pungent|a|辛辣的
punitive|a|惩罚性的
quaint|a|古雅的
qualm|n|疑虑
quandary|n|困境
quarantine|n|隔离
quell|v|镇压
query|n/v|查询
quest|n/v|探索
quirk|n|怪癖
quota|n|配额
rabid|a|狂热的
radiant|a|光芒四射的
rampant|a|猖獗的
rancor|n|怨恨
rapport|n|融洽关系
ratify|v|批准
raucous|a|喧闹的
ravenous|a|贪婪的
ravine|n|山谷
realm|n|领域
reap|v|收获
rebate|n|回扣
rebuke|v|指责
rebut|v|反驳
recede|v|后退
reckless|a|鲁莽的
reckon|v|认为
reclaim|v|收回
reconcile|v|调和
redundant|a|多余的
refrain|v|克制
refute|v|驳斥
regimen|n|养生法
rehabilitate|v|康复
reimburse|v|偿还
reiterate|v|重申
rejuvenate|v|使年轻
relentless|a|无情的
relinquish|v|放弃
relish|v|享受
remedy|n|补救办法 v.补救
reminiscent|a|怀旧的
remnant|n|残余
remorse|n|懊悔
render|v|使成为；提供
renown|n|名望
repeal|v|废除
repercussion|n|反响
replenish|v|补充
replicate|v|复制
reproach|v|责备
repudiate|v|否认
resent|v|怨恨
resilient|a|有弹性的
resonant|a|洪亮的
respite|n|暂缓
restitution|n|归还
resume|v|重新开始
retaliate|v|报复
retard|v|延迟
reticent|a|沉默的
retort|v|反驳
retract|v|撤回
retrospect|n|回顾
revere|v|尊敬
revitalize|v|使恢复元气
revoke|v|撤销
rhetoric|n|修辞
rigid|a|僵硬的
rigorous|a|严格的
rite|n|仪式
rivalry|n|竞争
robust|a|健壮的
rudimentary|a|基本的
rue|v|后悔
ruffle|v|弄皱
rupture|v/n|破裂
rustic|a|乡村的
ruthless|a|无情的
sabotage|v/n|破坏
sacred|a|神圣的
sagacious|a|睿智的
salient|a|突出的
salvage|v|打捞；挽救
sanction|n/v|制裁；批准
sarcastic|a|讽刺的
saturate|v|浸透
savage|a|野蛮的
scandal|n|丑闻
scarce|a|稀缺的
scathing|a|严厉的
sceptic|n|怀疑者
scorn|v/n|轻蔑
scrutinize|v|仔细检查
secrete|v|分泌
sector|n|部门；行业
sedate|a|安静的
sediment|n|沉淀物
segment|n|部分 v.分割
segregate|v|隔离
seminar|n|研讨会
sentiment|n|情绪；观点
sequel|n|续集
serene|a|宁静的
sever|v|切断
shrewd|a|精明的
shrink|v|收缩
shroud|v|遮蔽
siege|n|围攻
simile|n|明喻
sinister|a|邪恶的
skeptical|a|怀疑的
skim|v|略读
slack|a|松弛的
slander|v|诽谤
slash|v|砍
slaughter|v/n|屠宰
slogan|n|标语
smear|v|涂抹
smuggle|v|走私
snare|n|陷阱
soar|v|猛增
sober|a|清醒的
solicit|v|恳求
solidarity|n|团结
soluble|a|可溶的
somber|a|昏暗的
soothe|v|安慰
sophisticated|a|复杂的；世故的
souvenir|n|纪念品
sparse|a|稀疏的
spawn|v|产生
spearhead|v|带头
spectacle|n|景象
speculate|v|推测
spiral|n|螺旋
splendid|a|壮丽的
spontaneous|a|自发的
sporadic|a|零星的
squander|v|浪费
stagnant|a|停滞的
stale|a|不新鲜的
staple|n|主食 a.主要的
stark|a|鲜明的
statute|n|法规
steadfast|a|坚定的
steep|a|陡峭的
stellar|a|恒星的；杰出的
stern|a|严厉的
stigma|n|耻辱
stipulate|v|规定
strenuous|a|费力的
strife|n|冲突
stringent|a|严格的
strive|v|努力
stroll|v|散步
stubborn|a|顽固的
stun|v|使震惊
stunt|v|阻碍
subdue|v|征服
sublime|a|崇高的
submerge|v|淹没
submissive|a|顺从的
subordinate|a|下级的
subsequent|a|随后的
subside|v|平息
subsidy|n|补贴
substantiate|v|证实
subtle|a|微妙的
subvert|v|颠覆
succumb|v|屈服
sue|v|起诉
suffice|v|足够
summit|n|顶点
summon|v|召唤
superb|a|极好的
superfluous|a|多余的
supersede|v|取代
supplant|v|取代
supplement|n|补充
suppress|v|镇压
surpass|v|超越
surplus|n|过剩
surveillance|n|监视
susceptible|a|易受影响的
suspense|n|悬念
swamp|n|沼泽 v.淹没
sway|v|摇摆
swift|a|迅速的
symbolic|a|象征的
symmetry|n|对称
symptom|n|症状
syndrome|n|综合征
synopsis|n|概要
synthesis|n|综合
tacit|a|心照不宣的
tact|n|机智
tangible|a|有形的
tantalize|v|逗弄
tariff|n|关税
tedious|a|乏味的
temper|n|脾气 v.调和
temperate|a|温和的
tenacious|a|顽强的
tentative|a|试探性的
tenure|n|任期
terminal|a|末端的 n.终端
terminate|v|终止
terrain|n|地形
testament|n|证明
testify|v|作证
thaw|v|融化
therapeutic|a|治疗的
threshold|n|门槛
thrifty|a|节俭的
thrive|v|繁荣
thwart|v|阻挠
timid|a|胆小的
toil|v/n|辛苦
toll|n|通行费；代价
torment|v/n|折磨
toxic|a|有毒的
trait|n|特征
tranquil|a|宁静的
transcend|v|超越
transient|a|短暂的
transparent|a|透明的；公开的
traverse|v|穿越
treacherous|a|背叛的
tremor|n|颤抖
trespass|v|侵犯
tribute|n|致敬；贡品
trifle|n|琐事
trivial|a|琐碎的
turbulent|a|动荡的
turmoil|n|动荡
tyranny|n|暴政
ubiquitous|a|无处不在的
ulterior|a|隐秘的
unanimous|a|一致同意的
undercut|v|削弱
underestimate|v|低估
undergo|v|经历
underlying|a|潜在的
undermine|v|削弱
underscore|v|强调
unfold|v|展开
unify|v|统一
unprecedented|a|前所未有的
unravel|v|解开
unveil|v|揭开
upheaval|n|动乱
uphold|v|维持
uproar|n|骚动
usurp|v|篡夺
utilitarian|a|实用的
utmost|a|最大的
utter|a|完全的 v.发出
vacant|a|空的
vaccine|n|疫苗
vague|a|模糊的
vain|a|徒劳的
validate|v|验证
vandalism|n|故意破坏
vanguard|n|先锋
veer|v|转向
vehement|a|激烈的
velocity|n|速度
venerate|v|崇敬
vengeance|n|复仇
vent|v/n|发泄
venture|n|冒险 v.敢于
verdict|n|裁决
verify|v|核实
versatile|a|多才多艺的
veto|v/n|否决
viable|a|可行的
vice|n|恶习
vicinity|n|邻近
vicious|a|恶毒的
vigilant|a|警惕的
vindicate|v|证明正确
violate|v|违反
viral|a|病毒式的
virtue|n|美德
visceral|a|出自内心的
vivid|a|生动的
vocal|a|直言不讳的
vogue|n|时尚
void|a|空的 n.空虚
volatile|a|不稳定的
vortex|n|漩涡
vouch|v|担保
vow|n/v|誓言
vulgar|a|粗俗的
vulnerable|a|脆弱的
waive|v|放弃
wane|v|衰退
warrant|v|保证 n.搜查令
wary|a|谨慎的
weary|a|疲倦的
weave|v|编织
wedge|n|楔子
whimsical|a|异想天开的
wield|v|使用
wilt|v|枯萎
wistful|a|渴望的
withhold|v|拒绝
withstand|v|经受
witty|a|机智的
woe|n|悲痛
wreck|v/n|毁坏
wrench|v|猛扭
wretched|a|可怜的
yarn|n|纱线
yearn|v|渴望
yield|v|产出；屈服 n.产量
zeal|n|热心
zenith|n|顶点
`.trim().split('\n').filter(l=>l.trim()).map(l=>{const p=l.split('|');return{word:p[0],pos:p[1],meaning:p[2]};});
