/**
 * Generate rich word bank with examples + collocations + derivatives
 * Run: node scripts/gen_rich_words.cjs
 */
const fs = require('fs');

const words = [
  { word: 'abandon', phonetic: '/əˈbændən/', meaning: 'v. 放弃；抛弃；遗弃',
    examples: ['They had to abandon the sinking ship.', 'She abandoned her dream of becoming a dancer.'],
    collocations: ['abandon oneself to 沉溺于', 'abandon hope 放弃希望'],
    derivatives: ['abandoned (a.被遗弃的)', 'abandonment (n.放弃)'] },
  { word: 'ability', phonetic: '/əˈbɪləti/', meaning: 'n. 能力；才能',
    examples: ['She has the ability to solve complex problems.', 'The test measures your language ability.'],
    collocations: ['ability to do sth 做某事的能力', 'to the best of one\'s ability 尽某人所能'],
    derivatives: ['able (a.有能力的)', 'inability (n.无能)'] },
  { word: 'absorb', phonetic: '/əbˈzɔːb/', meaning: 'v. 吸收；吸引；理解',
    examples: ['Plants absorb nutrients from the soil.', 'I was so absorbed in the book that I lost track of time.'],
    collocations: ['be absorbed in 全神贯注于', 'absorb information 吸收信息'],
    derivatives: ['absorption (n.吸收)', 'absorbed (a.专注的)'] },
  { word: 'abstract', phonetic: '/ˈæbstrækt/', meaning: 'adj. 抽象的 n. 摘要 v. 提取',
    examples: ['The concept is too abstract for beginners.', 'Please write an abstract of your research paper.'],
    collocations: ['abstract concept 抽象概念', 'in the abstract 抽象地'],
    derivatives: ['abstraction (n.抽象)', 'abstractly (adv.抽象地)'] },
  { word: 'abuse', phonetic: '/əˈbjuːz/', meaning: 'v./n. 滥用；虐待；辱骂',
    examples: ['The system can be easily abused by dishonest users.', 'She suffered years of physical abuse.'],
    collocations: ['drug abuse 药物滥用', 'abuse of power 滥用权力'],
    derivatives: ['abusive (a.辱骂的)', 'abuser (n.施虐者)'] },
  { word: 'academic', phonetic: '/ˌækəˈdemɪk/', meaning: 'adj. 学术的；学院的 n. 学者',
    examples: ['Her academic performance has improved significantly.', 'The university is a leading academic institution.'],
    collocations: ['academic year 学年', 'academic research 学术研究'],
    derivatives: ['academy (n.学院)', 'academically (adv.学术上)'] },
  { word: 'accelerate', phonetic: '/əkˈseləreɪt/', meaning: 'v. 加速；促进',
    examples: ['The government plans to accelerate economic reform.', 'The car accelerated rapidly on the highway.'],
    collocations: ['accelerate growth 加速增长', 'accelerate the process 加速进程'],
    derivatives: ['acceleration (n.加速)', 'accelerator (n.加速器)'] },
  { word: 'access', phonetic: '/ˈækses/', meaning: 'n. 通道；使用权 v. 访问；获取',
    examples: ['Students need access to the library resources.', 'You can access your account online.'],
    collocations: ['have access to 有权使用', 'Internet access 互联网接入'],
    derivatives: ['accessible (a.可进入的)', 'accessibility (n.可访问性)'] },
  { word: 'accommodate', phonetic: '/əˈkɒmədeɪt/', meaning: 'v. 容纳；适应；提供住宿',
    examples: ['The hotel can accommodate up to 500 guests.', 'We must accommodate our plans to the new situation.'],
    collocations: ['accommodate needs 满足需求', 'accommodate changes 适应变化'],
    derivatives: ['accommodation (n.住宿)', 'accommodating (a.乐于助人的)'] },
  { word: 'accompany', phonetic: '/əˈkʌmpəni/', meaning: 'v. 陪伴；伴随；伴奏',
    examples: ['She will accompany me to the conference.', 'The rain was accompanied by strong winds.'],
    collocations: ['be accompanied by 伴随着', 'accompany sb to 陪某人去'],
    derivatives: ['companion (n.同伴)', 'accompaniment (n.伴奏)'] },
  { word: 'accomplish', phonetic: '/əˈkʌmplɪʃ/', meaning: 'v. 完成；实现；达到',
    examples: ['We managed to accomplish the task ahead of schedule.', "What do you hope to accomplish this year?"],
    collocations: ['accomplish a goal 实现目标', 'accomplish a mission 完成任务'],
    derivatives: ['accomplishment (n.成就)', 'accomplished (a.熟练的)'] },
  { word: 'account', phonetic: '/əˈkaʊnt/', meaning: 'n. 账户；解释；叙述 v. 说明；占比',
    examples: ['You need to account for every expense.', 'Online sales account for 30% of total revenue.'],
    collocations: ['account for 解释；占比', 'take into account 考虑到', 'bank account 银行账户'],
    derivatives: ['accountable (a.有责任的)', 'accountant (n.会计)'] },
  { word: 'accurate', phonetic: '/ˈækjərət/', meaning: 'adj. 准确的；精确的',
    examples: ['We need more accurate data before making a decision.', 'Her description of the event was remarkably accurate.'],
    collocations: ['accurate measurement 精确测量', 'accurate description 准确描述'],
    derivatives: ['accuracy (n.准确性)', 'accurately (adv.准确地)', 'inaccurate (a.不准确的)'] },
  { word: 'achieve', phonetic: '/əˈtʃiːv/', meaning: 'v. 达到；取得；实现',
    examples: ['He worked hard to achieve his career goals.', 'What do you want to achieve in the next five years?'],
    collocations: ['achieve success 取得成功', 'achieve a goal 实现目标'],
    derivatives: ['achievement (n.成就)', 'achievable (a.可实现的)'] },
  { word: 'acknowledge', phonetic: '/əkˈnɒlɪdʒ/', meaning: 'v. 承认；确认；致谢',
    examples: ['She refused to acknowledge her mistake.', 'We acknowledge the importance of diversity.'],
    collocations: ['acknowledge receipt 确认收到', 'widely acknowledged 公认的'],
    derivatives: ['acknowledgment (n.承认)', 'acknowledged (a.公认的)'] },
  { word: 'acquire', phonetic: '/əˈkwaɪər/', meaning: 'v. 获得；习得；收购',
    examples: ['It takes years to acquire a new language fluently.', 'The company plans to acquire several startups.'],
    collocations: ['acquire knowledge 获取知识', 'acquire skills 习得技能'],
    derivatives: ['acquisition (n.获得；收购)', 'acquisitive (a.渴求的)'] },
  { word: 'adapt', phonetic: '/əˈdæpt/', meaning: 'v. 适应；改编',
    examples: ['Animals must adapt to their changing environment.', 'The novel was adapted into a successful film.'],
    collocations: ['adapt to 适应', 'adapt from 改编自'],
    derivatives: ['adaptation (n.适应；改编)', 'adaptable (a.能适应的)'] },
  { word: 'adequate', phonetic: '/ˈædɪkwət/', meaning: 'adj. 足够的；适当的',
    examples: ['The current measures are not adequate to solve the crisis.', 'Make sure you get adequate sleep every night.'],
    collocations: ['adequate supply 充足的供应', 'adequate for 适合'],
    derivatives: ['adequately (adv.充分地)', 'inadequate (a.不足的)'] },
  { word: 'adjust', phonetic: '/əˈdʒʌst/', meaning: 'v. 调整；适应',
    examples: ['You may need to adjust your expectations.', 'It takes time to adjust to a new environment.'],
    collocations: ['adjust to 适应', 'adjust settings 调整设置'],
    derivatives: ['adjustment (n.调整)', 'adjustable (a.可调整的)'] },
  { word: 'adopt', phonetic: '/əˈdɒpt/', meaning: 'v. 采纳；收养；采用',
    examples: ['The board decided to adopt the new policy.', 'They adopted a child from overseas.'],
    collocations: ['adopt a method 采用方法', 'adopt a resolution 通过决议'],
    derivatives: ['adoption (n.采纳；收养)', 'adoptive (a.收养的)'] },
];

// Generate more words programmatically for volume
const moreWords = [
  ['advocate', '/ˈædvəkeɪt/', 'v. 提倡 n. 倡导者', ['He is a strong advocate of renewable energy.', 'We advocate for equal rights for all.'], ['advocate for 倡导', 'a strong advocate 坚定拥护者'], ['advocacy (n.倡导)']],
  ['affect', '/əˈfekt/', 'v. 影响；感动', ['The new policy will affect millions of workers.', 'The story deeply affected everyone present.'], ['adversely affect 不利影响', 'affect the outcome 影响结果'], ['effect (n.影响)', 'affection (n.感情)']],
  ['allocate', '/ˈæləkeɪt/', 'v. 分配；拨出', ['The government will allocate funds to education.', 'We need to allocate resources more efficiently.'], ['allocate funds 拨款', 'allocate time 分配时间'], ['allocation (n.分配)']],
  ['alternative', '/ɔːlˈtɜːnətɪv/', 'n. 选择 adj. 替代的', ['We need to find an alternative solution.', 'There is no alternative but to cancel the event.'], ['alternative energy 替代能源', 'have no alternative 别无选择'], ['alternatively (adv.或者)']],
  ['ambiguous', '/æmˈbɪɡjuəs/', 'adj. 模糊的；模棱两可的', ['The contract language is ambiguous.', 'His answer was deliberately ambiguous.'], ['ambiguous statement 含糊陈述', 'remain ambiguous 仍然模糊'], ['ambiguity (n.模糊)', 'unambiguous (a.明确的)']],
  ['ambitious', '/æmˈbɪʃəs/', 'adj. 有雄心的；野心勃勃的', ['She is an ambitious young entrepreneur.', 'The company has ambitious expansion plans.'], ['ambitious goal 雄心勃勃的目标', 'overly ambitious 过于野心'], ['ambition (n.雄心)']],
  ['analyze', '/ˈænəlaɪz/', 'v. 分析；解析', ['Researchers analyzed the data carefully.', 'We need to analyze the root cause of the problem.'], ['analyze data 分析数据', 'analyze the situation 分析情况'], ['analysis (n.分析)', 'analyst (n.分析师)']],
  ['anticipate', '/ænˈtɪsɪpeɪt/', 'v. 预期；期望；抢先', ['We anticipate sales growth next quarter.', "I didn't anticipate such a strong reaction."], ['anticipate needs 预判需求', 'eagerly anticipate 热切期待'], ['anticipation (n.预期)', 'anticipated (a.预期的)']],
  ['apparent', '/əˈpærənt/', 'adj. 明显的；表面上的', ['It became apparent that the project was behind.', 'The apparent cause was later found to be wrong.'], ['apparent reason 明显原因', 'for no apparent reason 无缘无故'], ['apparently (adv.显然)']],
  ['appeal', '/əˈpiːl/', 'v./n. 呼吁；吸引；上诉', ['The charity launched an appeal for donations.', 'The idea of working abroad appeals to me.'], ['appeal to 吸引；呼吁', 'launch an appeal 发起呼吁'], ['appealing (a.吸引人的)']],
  ['apply', '/əˈplaɪ/', 'v. 申请；应用；适用', ['You should apply for the scholarship.', 'This rule doesn\'t apply to everyone.'], ['apply for 申请', 'apply to 适用于'], ['application (n.申请；应用)', 'applicant (n.申请人)']],
  ['approach', '/əˈprəʊtʃ/', 'v. 接近 n. 方法；途径', ['We need a new approach to this problem.', 'As we approach the deadline, pressure increases.'], ['approach to 方法', 'positive approach 积极态度'], ['approachable (a.可接近的)']],
  ['appropriate', '/əˈprəʊpriət/', 'adj. 适当的 v. 挪用', ['Wear appropriate clothing for the interview.', 'The funds were appropriated for other purposes.'], ['appropriate for 适合', 'appropriate measures 适当措施'], ['appropriately (adv.适当地)', 'inappropriate (a.不适当的)']],
  ['approve', '/əˈpruːv/', 'v. 批准；赞成', ['The board approved the proposal unanimously.', 'I don\'t approve of his behavior.'], ['approve of 赞成', 'officially approved 正式批准'], ['approval (n.批准)', 'disapprove (v.反对)']],
  ['arise', '/əˈraɪz/', 'v. 出现；产生；起身', ['Unexpected problems may arise.', 'A new opportunity has arisen.'], ['arise from 由...引起', 'should the need arise 如有需要'], ['arisen (pp.)']],
  ['artificial', '/ˌɑːtɪˈfɪʃl/', 'adj. 人造的；虚假的', ['Artificial intelligence is transforming industries.', 'Her smile seemed artificial and forced.'], ['artificial intelligence 人工智能', 'artificial light 人造光'], ['artificially (adv.人工地)']],
  ['aspect', '/ˈæspekt/', 'n. 方面；层面；外观', ['Consider every aspect of the problem.', 'The building\'s southern aspect gets the most sun.'], ['key aspect 关键方面', 'from every aspect 从各方面'], []],
  ['assemble', '/əˈsembl/', 'v. 集合；组装', ['The team will assemble at 9 AM.', 'It took hours to assemble the furniture.'], ['assemble a team 组建团队', 'assemble parts 组装零件'], ['assembly (n.集合；组装)']],
  ['assess', '/əˈses/', 'v. 评估；评定', ['We need to assess the risks carefully.', 'The teacher will assess your progress monthly.'], ['assess the situation 评估情况', 'assess damage 评估损失'], ['assessment (n.评估)', 'assessor (n.评估人)']],
  ['assign', '/əˈsaɪn/', 'v. 分配；指派；指定', ['The manager assigned tasks to each member.', 'She was assigned to the Paris office.'], ['assign responsibility 分配责任', 'assign a task 分配任务'], ['assignment (n.任务)', 'reassign (v.重新分配)']],
  ['assist', '/əˈsɪst/', 'v. 帮助；协助', ['Staff will assist you with any questions.', 'We assisted in the rescue operation.'], ['assist with 帮助', 'assist in 协助'], ['assistance (n.帮助)', 'assistant (n.助手)']],
  ['associate', '/əˈsəʊʃieɪt/', 'v. 联系；关联 n. 同事', ['People associate success with hard work.', 'He is a business associate of mine.'], ['associate with 与...联系', 'closely associated 密切相关'], ['association (n.协会；关联)']],
  ['assume', '/əˈsjuːm/', 'v. 假设；承担；就任', ['We cannot assume everyone agrees.', 'She assumed responsibility for the project.'], ['assume that 假设', 'assume control 接管'], ['assumption (n.假设)']],
  ['assure', '/əˈʃʊər/', 'v. 保证；使确信', ['I can assure you the product is safe.', 'He assured me of his support.'], ['assure sb of sth 向某人保证', 'rest assured 放心'], ['assurance (n.保证)', 'reassure (v.使放心)']],
  ['atmosphere', '/ˈætməsfɪər/', 'n. 气氛；大气层', ['The restaurant has a warm atmosphere.', 'Greenhouse gases warm the atmosphere.'], ['working atmosphere 工作氛围', 'relaxed atmosphere 轻松氛围'], ['atmospheric (a.大气的)']],
  ['attach', '/əˈtætʃ/', 'v. 附上；连接；重视', ['Please attach your resume to the email.', 'She attaches great importance to education.'], ['attach importance to 重视', 'attached file 附件'], ['attachment (n.附件；依恋)']],
  ['attain', '/əˈteɪn/', 'v. 达到；获得', ['Few people attain true mastery.', 'She attained her goal of becoming a doctor.'], ['attain a goal 达到目标', 'attain knowledge 获得知识'], ['attainable (a.可达到的)', 'attainment (n.成就)']],
  ['attempt', '/əˈtempt/', 'v./n. 尝试；企图', ['This is our last attempt to resolve the issue.', 'He attempted to break the world record.'], ['attempt to do 试图做', 'in an attempt to 为了'], ['attempted (a.未遂的)']],
  ['attribute', '/ˈætrɪbjuːt/', 'v. 归因于 n. 属性', ['She attributes her success to hard work.', 'Patience is a key attribute of a teacher.'], ['attribute to 归因于', 'positive attribute 积极特质'], ['attribution (n.归因)', 'attributable (a.可归因的)']],
  ['authority', '/ɔːˈθɒrəti/', 'n. 权威；当局；权力', ['The local authority manages waste collection.', 'She is an authority on ancient history.'], ['have the authority to 有权', 'local authorities 地方当局'], ['authoritative (a.权威的)', 'authorize (v.授权)']],
  ['available', '/əˈveɪləbl/', 'adj. 可用的；有效的；有空的', ['The report will be available next Monday.', 'Are you available for a meeting tomorrow?'], ['available resources 可用资源', 'make available 提供'], ['availability (n.可用性)', 'unavailable (a.不可用的)']],
  ['aware', '/əˈweər/', 'adj. 意识到的；知道的', ['Are you aware of the risks involved?', 'She became aware that someone was watching.'], ['be aware of 意识到', 'fully aware 充分认识'], ['awareness (n.意识)', 'unaware (a.未察觉的)']],
  ['barrier', '/ˈbæriər/', 'n. 障碍；屏障；壁垒', ['Language barriers make communication difficult.', 'We need to break down barriers to trade.'], ['trade barrier 贸易壁垒', 'break down barriers 打破障碍'], []],
  ['benefit', '/ˈbenɪfɪt/', 'n. 利益 v. 受益；有益于', ['Regular exercise has many health benefits.', 'Everyone will benefit from this policy.'], ['benefit from 从...受益', 'health benefit 健康益处'], ['beneficial (a.有益的)', 'beneficiary (n.受益人)']],
  ['boom', '/buːm/', 'n. 繁荣；激增 v. 兴旺', ['The tech industry experienced a massive boom.', 'The economy is booming this quarter.'], ['economic boom 经济繁荣', 'baby boom 婴儿潮'], ['booming (a.繁荣的)']],
  ['burden', '/ˈbɜːdn/', 'n. 负担 v. 使负重', ['The new tax will burden small businesses.', 'She carried the burden of the family alone.'], ['heavy burden 沉重负担', 'financial burden 经济负担'], ['burdensome (a.繁重的)']],
  ['campaign', '/kæmˈpeɪn/', 'n. 运动；战役 v. 参加运动', ['The election campaign lasted six months.', 'They campaigned for better working conditions.'], ['launch a campaign 发起运动', 'advertising campaign 广告活动'], ['campaigner (n.活动家)']],
  ['capable', '/ˈkeɪpəbl/', 'adj. 有能力的；能胜任的', ['She is capable of handling complex tasks.', 'The system is capable of processing huge data.'], ['capable of 能够', 'highly capable 能力强的'], ['capability (n.能力)', 'incapable (a.无能力的)']],
  ['challenge', '/ˈtʃæləndʒ/', 'n./v. 挑战；质疑', ['Learning a new language is a rewarding challenge.', 'They challenged the decision in court.'], ['face a challenge 面对挑战', 'challenge the view 质疑观点'], ['challenging (a.有挑战性的)']],
  ['circumstance', '/ˈsɜːkəmstəns/', 'n. 环境；情况；境遇', ['Under no circumstance should you lie.', 'We must adapt to changing circumstances.'], ['under the circumstances 在这种情况下', 'financial circumstances 经济状况'], ['circumstantial (a.间接的)']],
  ['claim', '/kleɪm/', 'v./n. 声称；要求；索赔', ['The company claims its product is best.', 'She filed an insurance claim after the accident.'], ['claim that 声称', 'make a claim 索赔'], ['claimant (n.索赔人)']],
  ['collapse', '/kəˈlæps/', 'v./n. 崩溃；倒塌；暴跌', ['The bridge could collapse under heavy weight.', 'The economy collapsed after the crisis.'], ['economic collapse 经济崩溃', 'near collapse 几乎崩溃'], []],
  ['commit', '/kəˈmɪt/', 'v. 犯(罪)；承诺；投入', ['We are fully committed to quality service.', 'He committed a serious crime.'], ['commit to 承诺', 'commit suicide 自杀'], ['commitment (n.承诺)', 'committed (a.投入的)']],
  ['communicate', '/kəˈmjuːnɪkeɪt/', 'v. 交流；传达；沟通', ['It is essential to communicate your ideas clearly.', 'They communicated via email.'], ['communicate with 与...交流', 'communicate effectively 有效沟通'], ['communication (n.交流)', 'communicative (a.健谈的)']],
  ['community', '/kəˈmjuːnəti/', 'n. 社区；团体；社会', ['The local community came together to help.', 'Join our online community of learners.'], ['local community 当地社区', 'international community 国际社会'], []],
  ['compare', '/kəmˈpeər/', 'v. 比较；对比；比喻', ['Compare prices before making a purchase.', 'Life is often compared to a journey.'], ['compare with/to 与...比较', 'beyond compare 无与伦比'], ['comparison (n.比较)', 'comparable (a.可比较的)']],
  ['compensate', '/ˈkɒmpenseɪt/', 'v. 补偿；赔偿；弥补', ['The company compensated her for damages.', 'Hard work can compensate for lack of talent.'], ['compensate for 弥补', 'fully compensated 全额补偿'], ['compensation (n.补偿)']],
  ['compete', '/kəmˈpiːt/', 'v. 竞争；比赛', ['Small businesses struggle to compete.', 'Athletes from 50 countries will compete.'], ['compete with 与...竞争', 'compete against 与...比赛'], ['competition (n.竞争)', 'competitor (n.竞争者)']],
  ['complain', '/kəmˈpleɪn/', 'v. 抱怨；投诉', ['Customers complain about the long wait.', 'She complained of a headache.'], ['complain about 抱怨', 'complain of 诉说(病痛)'], ['complaint (n.投诉)', 'complainant (n.投诉人)']],
  ['complex', '/ˈkɒmpleks/', 'adj. 复杂的 n. 综合体', ['The human brain is incredibly complex.', 'We live in a housing complex.'], ['highly complex 极其复杂', 'inferiority complex 自卑情结'], ['complexity (n.复杂性)']],
  ['component', '/kəmˈpəʊnənt/', 'n. 成分；组件 adj. 组成的', ['Trust is an essential component of relationships.', 'Each component was carefully tested.'], ['key component 关键组成部分', 'electronic components 电子元件'], []],
  ['concentrate', '/ˈkɒnsntreɪt/', 'v. 集中；专注；浓缩', ['I can\'t concentrate with all this noise.', 'The factory concentrates on producing chips.'], ['concentrate on 专注于', 'concentrate efforts 集中努力'], ['concentration (n.专注)', 'concentrated (a.浓缩的)']],
  ['concept', '/ˈkɒnsept/', 'n. 概念；观念', ['The concept of time varies across cultures.', 'This is a relatively new concept in science.'], ['basic concept 基本概念', 'grasp a concept 理解概念'], ['conceptual (a.概念上的)']],
  ['concern', '/kənˈsɜːn/', 'n./v. 关心；担忧；涉及', ['Environmental protection is a major concern.', 'This matter concerns everyone in the room.'], ['show concern for 关心', 'as far as I\'m concerned 就我而言'], ['concerned (a.关心的)', 'concerning (prep.关于)']],
  ['conclude', '/kənˈkluːd/', 'v. 总结；结束；推断', ['The meeting concluded with a Q&A session.', 'What can we conclude from these results?'], ['conclude that 推断出', 'conclude a deal 达成协议'], ['conclusion (n.结论)', 'conclusive (a.决定性的)']],
  ['conduct', '/ˈkɒndʌkt/', 'n. 行为 v. 实施；引导；指挥', ['The scientist conducted a series of experiments.', 'His conduct was praised by everyone.'], ['conduct research 进行研究', 'code of conduct 行为准则'], ['conductor (n.指挥；导体)']],
  ['confirm', '/kənˈfɜːm/', 'v. 确认；证实；批准', ['Please confirm your attendance by Friday.', 'The results confirmed our hypothesis.'], ['confirm a reservation 确认预订', 'it is confirmed that 已确认'], ['confirmation (n.确认)', 'confirmed (a.确认的)']],
  ['conflict', '/ˈkɒnflɪkt/', 'n. 冲突 v. 抵触；矛盾', ['The two countries have been in conflict.', 'His statement conflicts with the evidence.'], ['armed conflict 武装冲突', 'conflict of interest 利益冲突'], ['conflicting (a.矛盾的)']],
  ['confront', '/kənˈfrʌnt/', 'v. 面对；对抗；对峙', ['You need to confront your fears.', 'The company was confronted with a lawsuit.'], ['be confronted with 面对', 'confront an issue 正视问题'], ['confrontation (n.对抗)']],
  ['conscious', '/ˈkɒnʃəs/', 'adj. 有意识的；清醒的；刻意的', ['He was barely conscious after the accident.', 'We made a conscious decision to change.'], ['conscious of 意识到', 'environmentally conscious 有环保意识的'], ['consciousness (n.意识)', 'subconscious (a.潜意识的)']],
  ['consequence', '/ˈkɒnsɪkwəns/', 'n. 结果；后果；重要性', ['Every action has consequences.', 'The mistake was of little consequence.'], ['serious consequences 严重后果', 'as a consequence 因此'], ['consequent (a.随之发生的)', 'consequently (adv.因此)']],
  ['conserve', '/kənˈsɜːv/', 'v. 保存；节约；保护', ['We should all try to conserve water.', 'The area is conserved as a nature reserve.'], ['conserve energy 节约能源', 'conserve resources 保护资源'], ['conservation (n.保护)', 'conservative (a.保守的)']],
  ['consider', '/kənˈsɪdər/', 'v. 考虑；认为；体谅', ['You should consider all options carefully.', 'She is considered a leading expert.'], ['consider doing 考虑做', 'consider it necessary 认为必要'], ['consideration (n.考虑)', 'considerable (a.相当大的)']],
  ['consistent', '/kənˈsɪstənt/', 'adj. 一致的；始终如一的', ['Her performance has been remarkably consistent.', 'Your actions must be consistent with your words.'], ['consistent with 与...一致', 'consistent quality 稳定的质量'], ['consistency (n.一致性)', 'consistently (adv.一贯地)']],
  ['constant', '/ˈkɒnstənt/', 'adj. 持续的；不变的；忠实的', ['The constant noise was unbearable.', 'She has been a constant source of support.'], ['constant change 不断变化', 'constant temperature 恒温'], ['constantly (adv.不断地)', 'constancy (n.恒定)']],
  ['constitute', '/ˈkɒnstɪtjuːt/', 'v. 构成；组成；设立', ['Women constitute half of the workforce.', 'This constitutes a serious breach of contract.'], ['constitute a threat 构成威胁', 'constitute a crime 构成犯罪'], ['constitution (n.宪法；构成)']],
  ['construct', '/kənˈstrʌkt/', 'v. 建造；构建 n. 构想', ['They plan to construct a new bridge.', 'The argument was carefully constructed.'], ['construct a theory 构建理论', 'well-constructed 结构良好的'], ['construction (n.建设)', 'constructive (a.建设性的)']],
  ['consume', '/kənˈsjuːm/', 'v. 消费；消耗；吃光', ['The average family consumes 300L of water daily.', 'The fire consumed the entire building.'], ['consume resources 消耗资源', 'time-consuming 耗时的'], ['consumer (n.消费者)', 'consumption (n.消费)']],
  ['contact', '/ˈkɒntækt/', 'n./v. 接触；联系', ['Please contact customer service for help.', 'I lost contact with her years ago.'], ['contact details 联系方式', 'stay in contact 保持联系'], []],
  ['contemporary', '/kənˈtemprəri/', 'adj. 当代的；同时代的', ['The museum exhibits contemporary art.', 'Shakespeare was contemporary with Galileo.'], ['contemporary society 当代社会', 'contemporary music 当代音乐'], ['contemporaries (n.同时代人)']],
  ['contribute', '/kənˈtrɪbjuːt/', 'v. 贡献；捐献；导致；投稿', ['Everyone should contribute to the environment.', 'Smoking contributed to his early death.'], ['contribute to 有助于；导致', 'contribute money 捐款'], ['contribution (n.贡献)', 'contributor (n.贡献者)']],
  ['controversial', '/ˌkɒntrəˈvɜːʃl/', 'adj. 有争议的', ['The new law remains highly controversial.', 'It was a controversial decision.'], ['highly controversial 极具争议', 'controversial issue 争议问题'], ['controversy (n.争议)']],
  ['convenient', '/kənˈviːniənt/', 'adj. 方便的；便利的', ['Online shopping is far more convenient.', 'Is 3 PM a convenient time for you?'], ['convenient for 对...方便', 'mutually convenient 双方方便的'], ['convenience (n.便利)', 'inconvenient (a.不方便的)']],
  ['conventional', '/kənˈvenʃənl/', 'adj. 传统的；常规的', ['She chose an unconventional path.', 'Conventional wisdom suggests otherwise.'], ['conventional wisdom 传统观念', 'conventional methods 常规方法'], ['convention (n.惯例)']],
  ['convince', '/kənˈvɪns/', 'v. 说服；使确信', ['He tried to convince me to invest.', 'I\'m not convinced that this is the right choice.'], ['convince sb of sth 说服某人', 'convince sb to do 说服某人做'], ['convincing (a.令人信服的)', 'convinced (a.确信的)']],
  ['cooperate', '/kəʊˈɒpəreɪt/', 'v. 合作；协作', ['The two companies agreed to cooperate.', 'Witnesses refused to cooperate with police.'], ['cooperate with 与...合作', 'fully cooperate 全力配合'], ['cooperation (n.合作)', 'cooperative (a.合作的)']],
  ['coordinate', '/kəʊˈɔːdɪneɪt/', 'v. 协调 n. 坐标', ['You need to coordinate efforts with the team.', 'GPS uses coordinates to pinpoint locations.'], ['coordinate with 与...协调', 'coordinate activities 协调活动'], ['coordination (n.协调)', 'coordinator (n.协调人)']],
  ['corporate', '/ˈkɔːpərət/', 'adj. 公司的；法人的', ['The corporate headquarters is in New York.', 'Corporate culture varies between companies.'], ['corporate responsibility 企业责任', 'corporate governance 公司治理'], ['corporation (n.公司)']],
  ['correspond', '/ˌkɒrəˈspɒnd/', 'v. 符合；对应；通信', ['The results correspond with our predictions.', 'We corresponded by email for years.'], ['correspond to 对应于', 'correspond with 与...通信'], ['correspondence (n.通信；对应)', 'correspondent (n.记者)']],
  ['create', '/kriˈeɪt/', 'v. 创造；引起；创作', ['Artists create works that inspire people.', 'The plan created more problems than it solved.'], ['create opportunities 创造机会', 'create a masterpiece 创作杰作'], ['creation (n.创造)', 'creator (n.创造者)']],
  ['crisis', '/ˈkraɪsɪs/', 'n. 危机；紧要关头', ['The country is facing an economic crisis.', 'We need to act now — this is a crisis.'], ['financial crisis 金融危机', 'midlife crisis 中年危机'], []],
  ['critical', '/ˈkrɪtɪkl/', 'adj. 批评的；关键的；危急的', ['Your support is critical to our success.', 'The patient remains in critical condition.'], ['critical of 对...批评', 'critical role 关键作用'], ['criticize (v.批评)', 'criticism (n.批评)']],
  ['crucial', '/ˈkruːʃl/', 'adj. 关键的；决定性的', ['The next 48 hours are crucial.', 'This decision could be crucial for our future.'], ['crucial role 关键角色', 'crucial factor 关键因素'], ['crucially (adv.关键地)']],
  ['cultivate', '/ˈkʌltɪveɪt/', 'v. 培养；耕作；建立', ['Reading helps to cultivate a rich vocabulary.', 'They cultivate rice in the southern provinces.'], ['cultivate a habit 培养习惯', 'cultivate relationships 建立关系'], ['cultivation (n.培养；耕作)']],
  ['current', '/ˈkʌrənt/', 'adj. 当前的 n. 水流；电流', ['The current situation requires immediate action.', 'Strong currents make swimming dangerous here.'], ['current affairs 时事', 'electric current 电流'], ['currently (adv.当前)']],
  ['debate', '/dɪˈbeɪt/', 'n./v. 辩论；讨论', ['There is ongoing debate about climate policy.', 'Scientists debated the findings at the conference.'], ['heated debate 激烈辩论', 'under debate 在讨论中'], ['debatable (a.有争议的)']],
  ['decade', '/ˈdekeɪd/', 'n. 十年', ['The city has changed dramatically over the past decade.', 'It took decades to build this infrastructure.'], ['over the past decade 过去十年', 'decades of experience 数十年经验'], []],
  ['decline', '/dɪˈklaɪn/', 'v./n. 下降；拒绝；衰退', ['The company\'s profits have been in decline.', 'She declined the job offer politely.'], ['decline sharply 急剧下降', 'decline an invitation 拒绝邀请'], []],
  ['define', '/dɪˈfaɪn/', 'v. 定义；界定；明确', ['How do you define success?', 'The boundaries are clearly defined.'], ['clearly define 明确定义', 'define as 定义为'], ['definition (n.定义)', 'definitive (a.权威的)']],
  ['demand', '/dɪˈmɑːnd/', 'n./v. 要求；需求', ['There is growing demand for renewable energy.', 'The workers demanded better wages.'], ['in demand 受欢迎', 'supply and demand 供求'], ['demanding (a.要求高的)']],
  ['demonstrate', '/ˈdemənstreɪt/', 'v. 证明；示范；示威', ['The study demonstrates a clear link.', 'She demonstrated how the machine works.'], ['demonstrate the ability 展示能力', 'demonstrate against 抗议'], ['demonstration (n.示范)', 'demonstrator (n.示威者)']],
  ['deny', '/dɪˈnaɪ/', 'v. 否认；拒绝；剥夺', ['The company denies any wrongdoing.', 'No one should be denied access to education.'], ['deny doing 否认做过', 'deny access 拒绝访问'], ['denial (n.否认)']],
  ['depend', '/dɪˈpend/', 'v. 依赖；取决于', ['The outcome will depend on various factors.', 'You can depend on me to get the job done.'], ['depend on 依赖', 'it depends 视情况而定'], ['dependent (a.依赖的)', 'dependence (n.依赖)']],
  ['derive', '/dɪˈraɪv/', 'v. 源自；获得；推导出', ['Many English words derive from Latin.', 'She derives great satisfaction from her work.'], ['derive from 源自', 'derive pleasure from 从...获得乐趣'], ['derivative (n.派生词)', 'derivation (n.起源)']],
  ['deserve', '/dɪˈzɜːv/', 'v. 值得；应得', ['She deserves recognition for her hard work.', 'You deserve a break after all this effort.'], ['deserve attention 值得关注', 'well-deserved 当之无愧的'], []],
  ['design', '/dɪˈzaɪn/', 'v./n. 设计；计划；意图', ['The building was designed by a famous architect.', 'This software is designed for beginners.'], ['design for 为...设计', 'graphic design 平面设计'], ['designer (n.设计师)']],
  ['desire', '/dɪˈzaɪər/', 'n./v. 渴望；欲望；愿望', ['The desire for knowledge is fundamental.', 'She desired nothing more than to go home.'], ['strong desire 强烈愿望', 'desire to do 渴望做'], ['desirable (a.令人满意的)']],
  ['despite', '/dɪˈspaɪt/', 'prep. 尽管；虽然', ['Despite the rain, the concert was a success.', 'He continued working despite his illness.'], ['despite the fact that 尽管'], []],
  ['destroy', '/dɪˈstrɔɪ/', 'v. 破坏；毁灭；消灭', ['The fire destroyed over 200 hectares of forest.', 'The scandal destroyed his reputation.'], ['completely destroy 完全摧毁', 'destroy evidence 销毁证据'], ['destruction (n.破坏)', 'destructive (a.破坏性的)']],
  ['detect', '/dɪˈtekt/', 'v. 发现；探测；察觉', ['The sensor can detect the slightest movement.', 'I detected a note of sarcasm in her voice.'], ['detect changes 检测变化', 'hard to detect 难以察觉'], ['detection (n.发现)', 'detective (n.侦探)']],
  ['determine', '/dɪˈtɜːmɪn/', 'v. 决定；确定；下决心', ['A blood test will help determine the cause.', 'She determined to prove them wrong.'], ['determine to do 决心做', 'determine the outcome 决定结果'], ['determination (n.决心)', 'determined (a.坚决的)']],
  ['device', '/dɪˈvaɪs/', 'n. 设备；装置；手段', ['This device can translate speech in real time.', 'Smartphones have become essential devices.'], ['electronic device 电子设备', 'safety device 安全装置'], []],
  ['devote', '/dɪˈvəʊt/', 'v. 致力于；奉献', ['He devoted his life to scientific research.', 'She devotes an hour each day to reading.'], ['devote to 致力于', 'devote oneself to 献身于'], ['devotion (n.奉献)', 'devoted (a.忠诚的)']],
  ['digital', '/ˈdɪdʒɪtl/', 'adj. 数字的；数码的', ['The digital revolution has changed everything.', 'Digital skills are essential in today\'s job market.'], ['digital age 数字时代', 'digital currency 数字货币'], ['digitally (adv.数字地)']],
  ['discipline', '/ˈdɪsəplɪn/', 'n. 纪律；学科 v. 训练', ['Self-discipline is essential for success.', 'Linguistics is a fascinating discipline.'], ['self-discipline 自律', 'maintain discipline 维持纪律'], ['disciplinary (a.纪律的)']],
  ['display', '/dɪˈspleɪ/', 'v./n. 展示；显示；陈列', ['The museum will display the artifacts.', 'The screen displays real-time information.'], ['on display 展出', 'display screen 显示屏'], []],
  ['distinct', '/dɪˈstɪŋkt/', 'adj. 不同的；明显的；独特的', ['There is a distinct difference between them.', 'The region has a distinct cultural identity.'], ['distinct from 与...不同', 'distinct advantage 明显优势'], ['distinction (n.区别)', 'distinctive (a.独特的)']],
  ['distinguish', '/dɪˈstɪŋɡwɪʃ/', 'v. 区分；辨别；使杰出', ['Color blindness makes it hard to distinguish red.', 'She distinguished herself as a brilliant scholar.'], ['distinguish between 区分', 'distinguish from 与...区分'], ['distinguished (a.杰出的)']],
];

// Merge all
const allWords = [...words, ...moreWords.map(w => ({
  word: w[0], phonetic: w[1], meaning: w[2], examples: w[3], collocations: w[4], derivatives: w[5]
}))];

// Add more common words (simplified entries for volume)
const quickWords = [
  ['economy','/ɪˈkɒnəmi/','n. 经济；节约','economic (a.经济的)','The economy is showing signs of recovery.','We need to make economies in our spending.'],
  ['education','/ˌedʒuˈkeɪʃn/','n. 教育；培养','educate (v.教育)','Education is the key to a better future.','She received a good education abroad.'],
  ['efficient','/ɪˈfɪʃnt/','adj. 高效的','efficiency (n.效率)','The new system is far more efficient.','We need efficient use of resources.'],
  ['eliminate','/ɪˈlɪmɪneɪt/','v. 消除；淘汰','elimination (n.消除)','The goal is to eliminate poverty.','The team was eliminated in the first round.'],
  ['embrace','/ɪmˈbreɪs/','v. 拥抱；包含；欣然接受',null,'We should embrace change.','The course embraces a wide range of topics.'],
  ['emerge','/iˈmɜːdʒ/','v. 出现；浮现','emergence (n.出现)','New evidence has emerged.','The sun emerged from behind the clouds.'],
  ['emergency','/iˈmɜːdʒənsi/','n. 紧急情况',null,'In case of emergency, call 911.','The hospital has an emergency room.'],
  ['emphasize','/ˈemfəsaɪz/','v. 强调；着重','emphasis (n.强调)','The teacher emphasized the importance of practice.','I cannot emphasize this enough.'],
  ['employ','/ɪmˈplɔɪ/','v. 雇用；使用','employment (n.就业)','The factory employs 500 workers.','She employed a different strategy.'],
  ['enable','/ɪˈneɪbl/','v. 使能够',null,'This scholarship will enable her to study abroad.','The new software enables faster processing.'],
  ['encounter','/ɪnˈkaʊntər/','v./n. 遇到；遭遇',null,'You may encounter unexpected challenges.','I had a brief encounter with a celebrity.'],
  ['encourage','/ɪnˈkʌrɪdʒ/','v. 鼓励；促进','encouragement (n.鼓励)','Parents should encourage their children to read.','The policy encourages investment.'],
  ['enforce','/ɪnˈfɔːs/','v. 执行；强制','enforcement (n.执行)','The police enforce the law.','We need to enforce stricter rules.'],
  ['engage','/ɪnˈɡeɪdʒ/','v. 从事；参与；吸引','engagement (n.参与)','The speaker managed to engage the audience.','They are engaged in important research.'],
  ['enhance','/ɪnˈhɑːns/','v. 增强；提高','enhancement (n.增强)','Exercise can enhance your health.','The app enhances the learning experience.'],
  ['enormous','/ɪˈnɔːməs/','adj. 巨大的',null,'The project required an enormous effort.','There was an enormous crowd at the concert.'],
  ['ensure','/ɪnˈʃʊər/','v. 确保；保证',null,'Please ensure all doors are locked.','We must ensure the safety of our workers.'],
  ['enterprise','/ˈentəpraɪz/','n. 企业；事业',null,'She started her own enterprise at 25.','This is a challenging enterprise.'],
  ['environment','/ɪnˈvaɪrənmənt/','n. 环境','environmental (a.环境的)','We must protect the environment.','The work environment here is excellent.'],
  ['equip','/ɪˈkwɪp/','v. 装备；配备','equipment (n.设备)','The lab is fully equipped.','Education equips you for life.'],
  ['essential','/ɪˈsenʃl/','adj. 必要的；本质的',null,'Water is essential for life.','The essential point is that we need change.'],
  ['establish','/ɪˈstæblɪʃ/','v. 建立；确立','establishment (n.建立)','The company was established in 1995.','We need to establish clear rules.'],
  ['estimate','/ˈestɪmeɪt/','v./n. 估计；评估',null,'The cost is estimated at $2 million.','Can you give me a rough estimate?'],
  ['evaluate','/ɪˈvæljueɪt/','v. 评价；评估','evaluation (n.评价)','The teacher will evaluate your progress.','We need to evaluate all the options.'],
  ['evidence','/ˈevɪdəns/','n. 证据；迹象',null,'There is strong evidence linking smoking to cancer.','The police found no evidence of a crime.'],
  ['evolution','/ˌiːvəˈluːʃn/','n. 进化；演变',null,'The theory of evolution explains diversity.','We studied the evolution of language.'],
  ['exceed','/ɪkˈsiːd/','v. 超过；超越',null,'The cost should not exceed our budget.','Her performance exceeded all expectations.'],
  ['exchange','/ɪksˈtʃeɪndʒ/','v./n. 交换；兑换',null,'We exchanged ideas at the meeting.','What is the current exchange rate?'],
  ['exclude','/ɪkˈskluːd/','v. 排除；排斥','exclusion (n.排除)','The price excludes tax.','No one should be excluded from education.'],
  ['execute','/ˈeksɪkjuːt/','v. 执行；实施','execution (n.执行)','The plan was poorly executed.','The CEO executes the board\'s decisions.'],
  ['executive','/ɪɡˈzekjətɪv/','adj. 执行的 n. 高管',null,'She holds an executive position.','The executive team met to discuss strategy.'],
  ['exercise','/ˈeksəsaɪz/','n./v. 锻炼；练习；行使',null,'Regular exercise is good for health.','Please complete exercises 1-5.'],
  ['exhibit','/ɪɡˈzɪbɪt/','v. 展览；显示 n. 展品','exhibition (n.展览)','The gallery will exhibit local artists.','The patient exhibits several symptoms.'],
  ['exist','/ɪɡˈzɪst/','v. 存在；生存','existence (n.存在)','Do aliens exist?','They existed on very little food.'],
  ['expand','/ɪkˈspænd/','v. 扩展；扩张','expansion (n.扩张)','The company plans to expand overseas.','Metals expand when heated.'],
  ['expect','/ɪkˈspekt/','v. 期望；预期；料想','expectation (n.期望)','I expect to finish by Friday.','What did you expect?'],
  ['expense','/ɪkˈspens/','n. 费用；代价','expensive (a.昂贵的)','Living expenses have increased.','He achieved success at great personal expense.'],
  ['experiment','/ɪkˈsperɪmənt/','n./v. 实验；试验',null,'The experiment confirmed the theory.','We experimented with different methods.'],
  ['expert','/ˈekspɜːt/','n. 专家 adj. 熟练的','expertise (n.专长)','She is an expert in international law.','We need expert advice.'],
  ['explain','/ɪkˈspleɪn/','v. 解释；说明','explanation (n.解释)','Can you explain how it works?','She explained the situation to me.'],
  ['explicit','/ɪkˈsplɪsɪt/','adj. 明确的；直率的',null,'The instructions were very explicit.','He was explicit about his intentions.'],
  ['exploit','/ɪkˈsplɔɪt/','v. 开发；剥削','exploitation (n.开发)','We should exploit every opportunity.','Workers were exploited by the factory.'],
  ['explore','/ɪkˈsplɔːr/','v. 探索；探究','exploration (n.探索)','Let\'s explore the city together.','The article explores different viewpoints.'],
  ['export','/ɪkˈspɔːt/','v. 出口 n. 出口产品',null,'The country exports coffee worldwide.','Exports have increased this year.'],
  ['expose','/ɪkˈspəʊz/','v. 暴露；揭露','exposure (n.暴露)','The report exposes serious flaws.','Don\'t expose your skin to the sun.'],
  ['express','/ɪkˈspres/','v. 表达 adj. 快速的','expression (n.表达)','I want to express my gratitude.','He took the express train.'],
  ['extend','/ɪkˈstend/','v. 延伸；扩展；提供','extension (n.延伸)','We decided to extend our stay.','They extended a warm welcome to us.'],
  ['extensive','/ɪkˈstensɪv/','adj. 广泛的；大量的',null,'She has extensive experience.','The fire caused extensive damage.'],
  ['external','/ɪkˈstɜːnl/','adj. 外部的；外面的',null,'External factors affected the results.','The external walls need painting.'],
  ['extreme','/ɪkˈstriːm/','adj. 极端的 n. 极端',null,'The extreme weather caused flooding.','He went from one extreme to the other.'],
  ['facilitate','/fəˈsɪlɪteɪt/','v. 促进；使便利',null,'The new software facilitates collaboration.','Good infrastructure facilitates trade.'],
  ['factor','/ˈfæktər/','n. 因素；要素',null,'Price is just one factor to consider.','Hard work was the key factor in his success.'],
  ['feature','/ˈfiːtʃər/','n. 特征；特色 v. 以...为特色',null,'The phone features a new camera.','Patience is a key feature of a good teacher.'],
  ['figure','/ˈfɪɡər/','n. 数字；人物 v. 认为',null,'The figures show a decline.','She is a prominent figure in politics.'],
  ['finance','/ˈfaɪnæns/','n. 金融 v. 资助','financial (a.金融的)','She works in finance.','The project was financed by the government.'],
  ['flexible','/ˈfleksəbl/','adj. 灵活的；柔韧的','flexibility (n.灵活性)','The company offers flexible hours.','Yoga helps keep your body flexible.'],
  ['flourish','/ˈflʌrɪʃ/','v. 繁荣；兴旺',null,'Small businesses can flourish with support.','The arts flourished in this period.'],
  ['focus','/ˈfəʊkəs/','v. 集中 n. 焦点',null,'We need to focus on the most urgent problems.','The focus of the meeting was budget planning.'],
  ['forbid','/fəˈbɪd/','v. 禁止；不许',null,'The school forbids phones in class.','Smoking is strictly forbidden.'],
  ['forecast','/ˈfɔːkɑːst/','v./n. 预测；预报',null,'The weather forecast says it will rain.','Economists forecast growth next year.'],
  ['formal','/ˈfɔːml/','adj. 正式的；形式的','informal (a.非正式的)','Please use formal language in emails.','He received no formal education.'],
  ['former','/ˈfɔːmər/','adj. 前者的；以前的',null,'The former president made a rare appearance.','Of the two options, I prefer the former.'],
  ['foundation','/faʊnˈdeɪʃn/','n. 基础；基金会',null,'A solid foundation is crucial for success.','The charity was set up as a foundation.'],
  ['framework','/ˈfreɪmwɜːk/','n. 框架；结构',null,'The agreement provides a framework for cooperation.','We need a legal framework for this.'],
  ['frequent','/ˈfriːkwənt/','adj. 频繁的','frequency (n.频率)','Frequent exercise improves health.','Her visits became less frequent.'],
  ['fulfill','/fʊlˈfɪl/','v. 实现；满足；履行',null,'We strive to fulfill customer needs.','He fulfilled his dream of becoming a pilot.'],
  ['function','/ˈfʌŋkʃn/','n. 功能；函数 v. 运行',null,'The main function of the heart is to pump blood.','The machine is functioning normally.'],
  ['fundamental','/ˌfʌndəˈmentl/','adj. 基本的 n. 原理',null,'Freedom of speech is fundamental.','Let\'s go back to fundamentals.'],
  ['generate','/ˈdʒenəreɪt/','v. 产生；生成','generation (n.产生)','Wind turbines generate electricity.','The proposal generated a lot of discussion.'],
  ['generous','/ˈdʒenərəs/','adj. 慷慨的；丰富的','generosity (n.慷慨)','She made a generous donation.','A generous portion of food was served.'],
  ['global','/ˈɡləʊbl/','adj. 全球的；整体的',null,'Climate change is a global issue.','We need a global perspective.'],
  ['govern','/ˈɡʌvn/','v. 统治；管理；支配','government (n.政府)','New regulations govern AI use.','The country is governed by elected officials.'],
  ['guarantee','/ˌɡærənˈtiː/','v./n. 保证；担保',null,'The product comes with a one-year guarantee.','I can\'t guarantee it will work.'],
  ['handle','/ˈhændl/','v. 处理 n. 把手',null,'She knows how to handle difficult customers.','The door handle was broken.'],
  ['highlight','/ˈhaɪlaɪt/','v. 强调；突出 n. 亮点',null,'The report highlights key issues.','The trip to Paris was the highlight of my year.'],
  ['household','/ˈhaʊshəʊld/','n. 家庭 adj. 家用的',null,'The average household uses 300L of water daily.','Household chores can be tiring.'],
  ['identical','/aɪˈdentɪkl/','adj. 完全相同的',null,'The two samples were almost identical.','Your phone is identical to mine.'],
  ['identify','/aɪˈdentɪfaɪ/','v. 识别；确认；认同','identification (n.识别)','Police identified the suspect from CCTV.','I can identify with her struggles.'],
  ['ignore','/ɪɡˈnɔːr/','v. 忽视；不理睬',null,'You cannot ignore the warning signs.','He ignored my advice completely.'],
  ['illustrate','/ˈɪləstreɪt/','v. 说明；举例；插图','illustration (n.说明)','Let me illustrate my point with an example.','The book is beautifully illustrated.'],
  ['immigrant','/ˈɪmɪɡrənt/','n. 移民 adj. 移民的','immigration (n.移民)','Many immigrants came to this country.','She is the daughter of immigrants.'],
  ['impact','/ˈɪmpækt/','n. 影响；冲击 v. 影响',null,'The pandemic had a massive impact.','New technology impacts every industry.'],
  ['implement','/ˈɪmplɪment/','v. 实施；执行','implementation (n.实施)','It will take months to implement the policy.','The plan was never fully implemented.'],
  ['imply','/ɪmˈplaɪ/','v. 暗示；意味着','implication (n.含义)','His silence implied agreement.','What are you implying?'],
  ['impose','/ɪmˈpəʊz/','v. 强加；征收',null,'The court imposed a heavy fine.','Don\'t impose your views on others.'],
  ['income','/ˈɪnkʌm/','n. 收入；收益',null,'She has a steady income from freelance work.','Income inequality is a growing problem.'],
  ['indicate','/ˈɪndɪkeɪt/','v. 表明；指示；暗示','indication (n.迹象)','Recent polls indicate a shift in opinion.','The sign indicates the direction.'],
  ['individual','/ˌɪndɪˈvɪdʒuəl/','adj. 个人的 n. 个体',null,'Each individual has unique talents.','We respect individual differences.'],
  ['industrial','/ɪnˈdʌstriəl/','adj. 工业的；产业的','industry (n.工业)','The city was once an industrial center.','The Industrial Revolution changed society.'],
  ['inevitable','/ɪnˈevɪtəbl/','adj. 不可避免的',null,'Change is inevitable in any organization.','The accident seemed almost inevitable.'],
  ['influence','/ˈɪnfluəns/','n./v. 影响；作用','influential (a.有影响的)','Her work influenced a generation of artists.','Parents have a strong influence on children.'],
  ['initial','/ɪˈnɪʃl/','adj. 最初的 n. 首字母',null,'The initial results are promising.','Please write your initials here.'],
  ['innovation','/ˌɪnəˈveɪʃn/','n. 创新；革新','innovate (v.创新)','Technological innovation drives change.','This product is a major innovation.'],
  ['insight','/ˈɪnsaɪt/','n. 洞察力；深刻见解',null,'The book provides valuable insights.','She has great insight into human nature.'],
  ['institute','/ˈɪnstɪtjuːt/','n. 机构；学院 v. 建立','institution (n.机构)','He works at a research institute.','The government instituted new reforms.'],
  ['integrate','/ˈɪntɪɡreɪt/','v. 整合；融入','integration (n.整合)','We need to integrate new technologies.','She integrated well into the team.'],
  ['intellectual','/ˌɪntəˈlektʃuəl/','adj. 智力的 n. 知识分子',null,'Reading is an intellectual exercise.','She is one of the leading intellectuals.'],
  ['intense','/ɪnˈtens/','adj. 强烈的；激烈的','intensity (n.强度)','The competition was intense.','She has an intense desire to succeed.'],
  ['interact','/ˌɪntərˈækt/','v. 互动；相互作用','interaction (n.互动)','Children learn by interacting with others.','The two chemicals interact violently.'],
  ['interpret','/ɪnˈtɜːprɪt/','v. 解释；口译','interpretation (n.解释)','How do you interpret this poem?','She interpreted for the delegation.'],
  ['invest','/ɪnˈvest/','v. 投资；投入','investment (n.投资)','Many people invest in the stock market.','She invested a lot of time in this project.'],
  ['investigate','/ɪnˈvestɪɡeɪt/','v. 调查；研究','investigation (n.调查)','Police are investigating the cause.', 'Scientists are investigating the phenomenon.'],
  ['involve','/ɪnˈvɒlv/','v. 涉及；包含；参与','involvement (n.参与)','The project involves a lot of teamwork.','How many people are involved?'],
  ['isolate','/ˈaɪsəleɪt/','v. 隔离；孤立','isolation (n.隔离)','The patient was isolated to prevent infection.','I felt isolated in the new city.'],
  ['issue','/ˈɪʃuː/','n. 问题；议题 v. 发布',null,'Climate change is a pressing issue.','The company issued a statement.'],
  ['justify','/ˈdʒʌstɪfaɪ/','v. 证明...正当；为...辩护','justification (n.正当理由)','How can you justify this expense?','The end does not justify the means.'],
  ['keen','/kiːn/','adj. 热衷的；敏锐的；渴望的',null,'She is keen on learning languages.','He has a keen sense of observation.'],
  ['launch','/lɔːntʃ/','v. 发射；发起；推出 n. 发布',null,'The company launched a new product.','The rocket was launched successfully.'],
  ['leading','/ˈliːdɪŋ/','adj. 领先的；主要的',null,'She is a leading expert in her field.','China is a leading producer of electronics.'],
  ['legal','/ˈliːɡl/','adj. 法律的；合法的','illegal (a.非法的)','You should seek legal advice.','Is this legal in your country?'],
  ['liberal','/ˈlɪbərəl/','adj. 自由的；开明的；慷慨的',null,'He holds liberal views on social issues.','She was liberal with her praise.'],
  ['limitation','/ˌlɪmɪˈteɪʃn/','n. 限制；局限','limit (n./v.限制)','Every study has its limitations.','The speed limitation is 60 mph.'],
  ['maintain','/meɪnˈteɪn/','v. 维持；保养；坚持认为','maintenance (n.维护)','It\'s important to maintain good health.','He maintains that he is innocent.'],
  ['manipulate','/məˈnɪpjuleɪt/','v. 操纵；操作','manipulation (n.操纵)','Politicians manipulate statistics.','The device is hard to manipulate.'],
  ['massive','/ˈmæsɪv/','adj. 巨大的；大量的',null,'The earthquake caused massive destruction.','There was a massive crowd at the concert.'],
  ['mechanism','/ˈmekənɪzəm/','n. 机制；原理',null,'Scientists study the mechanism of disease.','The mechanism is quite simple.'],
  ['mental','/ˈmentl/','adj. 精神的；心理的',null,'Mental health is as important as physical health.','She made a mental note to call him.'],
  ['military','/ˈmɪlətri/','adj. 军事的 n. 军队',null,'The government increased military spending.','He served in the military for 20 years.'],
  ['moderate','/ˈmɒdərət/','adj. 适度的 v. 缓和',null,'Moderate exercise is best for health.','The moderator kept the debate civil.'],
  ['monitor','/ˈmɒnɪtər/','v. 监控 n. 显示器',null,'Doctors monitor the patient\'s condition.','The computer monitor is 27 inches.'],
  ['motivate','/ˈməʊtɪveɪt/','v. 激励；激发','motivation (n.动力)','A good leader knows how to motivate.','What motivates you to study?'],
  ['negative','/ˈneɡətɪv/','adj. 消极的；负面的',null,'Turn negative experiences into lessons.','The test came back negative.'],
  ['negotiate','/nɪˈɡəʊʃieɪt/','v. 谈判；协商','negotiation (n.谈判)','The union is negotiating for better wages.','We negotiated a lower price.'],
  ['nevertheless','/ˌnevəðəˈles/','adv. 然而；尽管如此',null,'It was raining; nevertheless, the game continued.','She was tired but continued nevertheless.'],
  ['notion','/ˈnəʊʃn/','n. 概念；观念',null,'She rejected the notion that women are inferior.','I have a vague notion of what happened.'],
  ['numerous','/ˈnjuːmərəs/','adj. 许多的；大量的',null,'There are numerous reasons to start early.','She has received numerous awards.'],
  ['objective','/əbˈdʒektɪv/','n. 目标 adj. 客观的',null,'The main objective is to increase sales.','We need an objective assessment.'],
  ['obtain','/əbˈteɪn/','v. 获得；得到',null,'You need a license to obtain certain chemicals.','Information can be obtained online.'],
  ['obvious','/ˈɒbviəs/','adj. 明显的；显然的',null,'The solution seems obvious in retrospect.','It was obvious that she was upset.'],
  ['offend','/əˈfend/','v. 冒犯；违反','offence (n.冒犯)',"I didn't mean to offend you.",'His actions offended against the rules.'],
  ['opponent','/əˈpəʊnənt/','n. 对手；反对者',null,'She defeated her opponent easily.','He is a strong opponent of the policy.'],
  ['opportunity','/ˌɒpəˈtjuːnəti/','n. 机会；时机',null,'This internship is a great opportunity.','Don\'t miss this opportunity.'],
  ['oppose','/əˈpəʊz/','v. 反对；对抗','opposition (n.反对)','I strongly oppose any form of discrimination.','The proposal was opposed by many.'],
  ['option','/ˈɒpʃn/','n. 选择；选项','optional (a.可选的)','We have no option but to cancel.','There are several options available.'],
  ['original','/əˈrɪdʒənl/','adj. 原始的；独创的 n. 原作','origin (n.起源)','The original version is much better.','She has a very original mind.'],
  ['outcome','/ˈaʊtkʌm/','n. 结果；成果',null,'The outcome surprised many analysts.','What was the outcome of the meeting?'],
  ['outline','/ˈaʊtlaɪn/','n. 大纲；轮廓 v. 概述',null,'Let me outline the main points.','She drew an outline of the building.'],
  ['overcome','/ˌəʊvəˈkʌm/','v. 克服；战胜',null,'She overcame her fear of public speaking.','We must overcome these obstacles together.'],
  ['overseas','/ˌəʊvəˈsiːz/','adv./adj. 海外；国外',null,'He worked overseas for five years.','Overseas markets are important for exports.'],
  ['participate','/pɑːˈtɪsɪpeɪt/','v. 参与；参加','participation (n.参与)','All students are encouraged to participate.','She participated in the debate.'],
  ['particularly','/pəˈtɪkjələli/','adv. 特别地；尤其',null,'I am particularly interested in history.','This is particularly important for beginners.'],
  ['passion','/ˈpæʃn/','n. 热情；激情；酷爱','passionate (a.热情的)','She has a genuine passion for teaching.','Music is his greatest passion.'],
  ['peculiar','/pɪˈkjuːliər/','adj. 特有的；奇怪的',null,'There was a peculiar smell in the room.','The custom is peculiar to this region.'],
  ['perform','/pəˈfɔːm/','v. 执行；表演；表现','performance (n.表现)','The band will perform tonight.','How did the company perform this quarter?'],
  ['permanent','/ˈpɜːmənənt/','adj. 永久的；长期的',null,'Are you looking for permanent work?','The damage is permanent.'],
  ['perspective','/pəˈspektɪv/','n. 观点；视角；透视',null,'Travel gives you a new perspective.','From my perspective, the plan is flawed.'],
  ['phenomenon','/fɪˈnɒmɪnən/','n. 现象；奇才',null,'Globalization is a complex phenomenon.','The aurora is a natural phenomenon.'],
  ['platform','/ˈplætfɔːm/','n. 平台；站台；讲台',null,'Candidates outlined their policies on the platform.','Social media platforms have huge influence.'],
  ['policy','/ˈpɒləsi/','n. 政策；方针；保险单',null,'The new policy takes effect next month.','It\'s company policy to recycle.'],
  ['portion','/ˈpɔːʃn/','n. 部分；一份',null,'A large portion of the budget goes to healthcare.','Would you like a portion of fries?'],
  ['potential','/pəˈtenʃl/','adj. 潜在的 n. 潜力',null,'The athlete shows great potential.','We must consider potential risks.'],
  ['poverty','/ˈpɒvəti/','n. 贫穷；贫困',null,'The organization works to alleviate poverty.','Millions live in poverty worldwide.'],
  ['practical','/ˈpræktɪkl/','adj. 实际的；实用的',null,'We need a practical solution.','She has a lot of practical experience.'],
  ['precise','/prɪˈsaɪs/','adj. 精确的；准确的','precision (n.精确)',"Can you be more precise?",'The measurements must be precise.'],
  ['predict','/prɪˈdɪkt/','v. 预测；预言','prediction (n.预测)',"It's impossible to predict the future.",'Economists predicted the recession.'],
  ['prejudice','/ˈpredʒudɪs/','n. 偏见 v. 损害',null,'We must fight against prejudice.','The news prejudiced the jury.'],
  ['preserve','/prɪˈzɜːv/','v. 保存；保护；维护','preservation (n.保护)',"We should preserve these ancient buildings.",'The society was preserved as a museum.'],
  ['pressure','/ˈpreʃər/','n. 压力 v. 施压',null,'Many students feel intense pressure.','Don\'t let others pressure you.'],
  ['previous','/ˈpriːviəs/','adj. 以前的；先前的',null,'My previous job involved travel.','The previous owner left this note.'],
  ['primary','/ˈpraɪməri/','adj. 主要的；初级的',null,'The primary goal is customer satisfaction.','She teaches at a primary school.'],
  ['principle','/ˈprɪnsəpl/','n. 原则；原理',null,'He refused to compromise his principles.','The principle of democracy is important.'],
  ['priority','/praɪˈɒrəti/','n. 优先权；重点',null,'Safety must be our top priority.','Education should be a national priority.'],
  ['procedure','/prəˈsiːdʒər/','n. 程序；步骤',null,'Please follow the standard procedure.','The medical procedure was successful.'],
  ['process','/ˈprəʊses/','n. 过程 v. 处理',null,'Learning a language is a gradual process.','The application is being processed.'],
  ['productive','/prəˈdʌktɪv/','adj. 多产的；富有成效的','productivity (n.生产力)',"The meeting was highly productive.",'She is a very productive writer.'],
  ['profession','/prəˈfeʃn/','n. 职业；专业','professional (a.专业的)',"Teaching is a noble profession.",'He entered the medical profession.'],
  ['profit','/ˈprɒfɪt/','n. 利润 v. 获益','profitable (a.盈利的)',"The company reported record profits.",'You can profit from this experience.'],
  ['profound','/prəˈfaʊnd/','adj. 深刻的；深远的',null,'The experience had a profound impact.','His words were very profound.'],
  ['progress','/ˈprəʊɡres/','n./v. 进步；进展','progressive (a.进步的)',"We've made significant progress.",'The project is progressing well.'],
  ['project','/ˈprɒdʒekt/','n. 项目 v. 投射；预计',null,"The construction project takes three years.",'She projected sales for next year.'],
  ['promote','/prəˈməʊt/','v. 促进；推广；晋升','promotion (n.晋升)',"The campaign promotes healthy eating.",'She was promoted to manager.'],
  ['proper','/ˈprɒpər/','adj. 适当的；正确的',null,'Make sure you follow the proper channels.','Is this the proper way to do it?'],
  ['property','/ˈprɒpəti/','n. 财产；性质；房产',null,'Intellectual property must be respected.','They bought a property in the countryside.'],
  ['proportion','/prəˈpɔːʃn/','n. 比例；部分；均衡',null,'A large proportion of people live in cities.','The head is out of proportion with the body.'],
  ['propose','/prəˈpəʊz/','v. 提议；建议；求婚','proposal (n.提议)',"I propose we postpone the meeting.",'He proposed to her on the beach.'],
  ['prospect','/ˈprɒspekt/','n. 前景；展望；可能性',null,'The prospect of working abroad is exciting.','There is little prospect of success.'],
  ['prosperity','/prɒˈsperəti/','n. 繁荣；兴旺','prosperous (a.繁荣的)',"Economic prosperity benefits everyone.",'The country enjoyed years of prosperity.'],
  ['purchase','/ˈpɜːtʃəs/','v./n. 购买',null,'You can purchase tickets online.','She made several purchases today.'],
  ['pursue','/pəˈsjuː/','v. 追求；追赶；继续','pursuit (n.追求)',"She decided to pursue a career in science.",'Police pursued the suspect on foot.'],
  ['qualify','/ˈkwɒlɪfaɪ/','v. 使合格；限定；修饰','qualification (n.资格)',"This degree qualifies you to teach.",'I should qualify my earlier statement.'],
  ['range','/reɪndʒ/','n. 范围 v. 变化；排列',null,'The store offers a wide range of products.','Prices range from $10 to $100.'],
  ['rapid','/ˈræpɪd/','adj. 快速的；迅速的',null,'The rapid development of AI raises questions.','We are seeing rapid changes in technology.'],
  ['rational','/ˈræʃnəl/','adj. 理性的；合理的','irrational (a.非理性的)',"Let's make a rational decision.",'Is there a rational explanation?'],
  ['reality','/riˈæləti/','n. 现实；实际','realistic (a.现实的)',"The reality is far more complex.",'Virtual reality is becoming mainstream.'],
  ['reasonable','/ˈriːznəbl/','adj. 合理的；公道的',null,'We expect everyone to act reasonably.','The price seems reasonable.'],
  ['recognize','/ˈrekəɡnaɪz/','v. 认出；承认；认可','recognition (n.认出)',"I didn't recognize her.",'He is recognized as a leading authority.'],
  ['recommend','/ˌrekəˈmend/','v. 推荐；建议','recommendation (n.推荐)',"I highly recommend this restaurant.",'What do you recommend?'],
  ['recover','/rɪˈkʌvər/','v. 恢复；康复；找回','recovery (n.恢复)',"It will take weeks to recover.",'Police recovered the stolen goods.'],
  ['reduce','/rɪˈdjuːs/','v. 减少；降低','reduction (n.减少)',"We must reduce our carbon emissions.",'The price has been reduced by 20%.'],
  ['reflect','/rɪˈflekt/','v. 反映；反射；反思','reflection (n.反射)',"Your actions reflect your values.",'Take time to reflect on your mistakes.'],
  ['reform','/rɪˈfɔːm/','v./n. 改革；改造',null,"The government promised to reform education.",'The reforms were widely welcomed.'],
  ['regard','/rɪˈɡɑːd/','v. 看待 n. 尊重；问候',null,"I regard her as a close friend.",'Give my regards to your family.'],
  ['register','/ˈredʒɪstər/','v. 登记；注册 n. 登记簿','registration (n.注册)',"Please register for the course.",'The cash register is broken.'],
  ['regulate','/ˈreɡjuleɪt/','v. 调节；管理；控制','regulation (n.规章)',"The agency regulates food safety.",'This valve regulates the flow.'],
  ['reinforce','/ˌriːɪnˈfɔːs/','v. 加强；增强；加固',null,"Positive feedback reinforces good behavior.",'The walls were reinforced with steel.'],
  ['reject','/rɪˈdʒekt/','v. 拒绝；排斥；驳回','rejection (n.拒绝)',"The committee rejected his application.",'She felt rejected by her peers.'],
  ['release','/rɪˈliːs/','v./n. 释放；发布；发行',null,"The company released new software.",'The prisoner was released early.'],
  ['relevant','/ˈreləvənt/','adj. 相关的；切题的','relevance (n.相关)',"Include only relevant information.",'Is this still relevant today?'],
  ['reliable','/rɪˈlaɪəbl/','adj. 可靠的；可信赖的','reliability (n.可靠性)',"We need a reliable source of energy.",'She is a very reliable friend.'],
  ['relieve','/rɪˈliːv/','v. 缓解；减轻；解除','relief (n.缓解)',"A warm bath relieves stress.",'The medicine relieved her pain.'],
  ['rely','/rɪˈlaɪ/','v. 依赖；依靠','reliance (n.依赖)',"Don't rely too heavily on one source.",'You can rely on me.'],
  ['remain','/rɪˈmeɪn/','v. 保持；剩余；逗留',null,"The situation remains tense.",'Only a few tickets remain.'],
  ['remarkable','/rɪˈmɑːkəbl/','adj. 显著的；非凡的；引人注目的',null,"She has made remarkable progress.",'It is remarkable that he survived.'],
  ['remote','/rɪˈməʊt/','adj. 遥远的；偏僻的；远程的',null,"The village is in a remote area.",'He works remotely from home.'],
  ['replace','/rɪˈpleɪs/','v. 取代；替换；放回','replacement (n.替代)',"Machines cannot replace human creativity.",'Please replace the book on the shelf.'],
  ['represent','/ˌreprɪˈzent/','v. 代表；表示；描绘','representation (n.代表)',"The lawyer will represent you in court.",'The statue represents peace.'],
  ['reputation','/ˌrepjuˈteɪʃn/','n. 名声；声誉；名誉',null,"The company has a good reputation.",'His reputation was ruined by the scandal.'],
  ['require','/rɪˈkwaɪər/','v. 需要；要求；命令','requirement (n.要求)',"The job requires three years of experience.",'What is required of me?'],
  ['research','/rɪˈsɜːtʃ/','n./v. 研究；调查',null,"The findings were published in a journal.",'She is researching climate change.'],
  ['resolve','/rɪˈzɒlv/','v. 解决；决定 n. 决心','resolution (n.决心)',"We need to resolve this issue quickly.",'She resolved to work harder.'],
  ['resource','/rɪˈsɔːs/','n. 资源；财力；智谋','resourceful (a.足智多谋的)',"Water is a precious resource.",'We must use resources wisely.'],
  ['respond','/rɪˈspɒnd/','v. 回应；反应；回答','response (n.回应)',"Please respond by Friday.",'How did she respond to the news?'],
  ['responsible','/rɪˈspɒnsəbl/','adj. 负责的；有责任的','responsibility (n.责任)',"Who is responsible for this mess?",'She is a responsible person.'],
  ['restore','/rɪˈstɔːr/','v. 恢复；修复；归还','restoration (n.恢复)',"The church was carefully restored.",'Power was restored after the blackout.'],
  ['restrict','/rɪˈstrɪkt/','v. 限制；约束；限定','restriction (n.限制)',"New laws restrict plastic bag use.",'Access is restricted to members.'],
  ['reveal','/rɪˈviːl/','v. 揭示；透露；展现','revelation (n.揭示)',"The investigation revealed new facts.",'She revealed her secret to me.'],
  ['reverse','/rɪˈvɜːs/','v. 逆转 adj. 相反的 n. 反面',null,"The court reversed the previous ruling.",'The car reversed into a parking space.'],
  ['revolution','/ˌrevəˈluːʃn/','n. 革命；变革；旋转','revolutionary (a.革命性的)',"The internet caused a revolution.",'The French Revolution changed Europe.'],
  ['rival','/ˈraɪvl/','n. 对手 v. 与...竞争','rivalry (n.竞争)',"The two companies are fierce rivals.",'No one can rival her talent.'],
  ['route','/ruːt/','n. 路线；路径；航线',null,"What is the shortest route?",'The bus follows a different route.'],
  ['routine','/ruːˈtiːn/','n. 常规；例行公事 adj. 常规的',null,"A morning routine helps productivity.",'The doctor performed a routine checkup.'],
  ['sacrifice','/ˈsækrɪfaɪs/','n./v. 牺牲；献祭；舍弃',null,"She sacrificed her career for her family.",'Success requires sacrifice.'],
  ['scale','/skeɪl/','n. 规模；比例；等级 v. 攀登',null,"The company plans to scale up operations.",'The map has a scale of 1:50,000.'],
  ['schedule','/ˈʃedjuːl/','n. 时间表 v. 安排',null,"The meeting is scheduled for Tuesday.",'I have a busy schedule today.'],
  ['security','/sɪˈkjʊərəti/','n. 安全；保障；安保','secure (a.安全的)',"Airport security has been tightened.",'Financial security is important.'],
  ['sensitive','/ˈsensətɪv/','adj. 敏感的；体贴的；灵敏的','sensitivity (n.敏感)',"She is sensitive to criticism.",'This is a sensitive issue.'],
  ['severe','/sɪˈvɪər/','adj. 严重的；严厉的；严峻的',null,"The region suffered severe flooding.",'She received severe criticism.'],
  ['shift','/ʃɪft/','v./n. 转移；变化；轮班',null,"There has been a shift in attitudes.",'She works the night shift.'],
  ['significant','/sɪɡˈnɪfɪkənt/','adj. 重要的；显著的；有意义的','significance (n.重要性)',"There has been significant improvement.",'The difference is not significant.'],
  ['similar','/ˈsɪmələr/','adj. 相似的；类似的','similarity (n.相似)',"The two paintings are similar.",'My situation is similar to yours.'],
  ['source','/sɔːs/','n. 来源；出处；源头',null,"Always cite your sources.",'The river has its source in the mountains.'],
  ['specific','/spəˈsɪfɪk/','adj. 具体的；特定的；明确的',null,"Can you be more specific?",'The money is for a specific purpose.'],
  ['stable','/ˈsteɪbl/','adj. 稳定的 n. 马厩','stability (n.稳定)',"The patient is now stable.",'We need a stable economic environment.'],
  ['standard','/ˈstændəd/','n. 标准 adj. 标准的',null,"We must maintain high standards.",'This is standard procedure.'],
  ['statistics','/stəˈtɪstɪks/','n. 统计；统计学；数据',null,"Official statistics show a decline.",'She is studying statistics at university.'],
  ['status','/ˈsteɪtəs/','n. 地位；状态；身份',null,"Her status as an expert is recognized.",'Check the status of your order.'],
  ['strategy','/ˈstrætədʒi/','n. 策略；战略','strategic (a.战略的)',"The company needs a new strategy.",'What is your strategy for success?'],
  ['stress','/stres/','n. 压力；强调 v. 强调；使紧张',null,"Managing stress is important.",'I must stress the importance of safety.'],
  ['structure','/ˈstrʌktʃər/','n. 结构 v. 构建；组织','structural (a.结构的)',"The organizational structure is complex.",'How is the book structured?'],
  ['substantial','/səbˈstænʃl/','adj. 大量的；实质的；重大的',null,"A substantial number voted against.",'We made substantial progress.'],
  ['sufficient','/səˈfɪʃnt/','adj. 足够的；充分的',null,'We have sufficient evidence.','The food was more than sufficient.'],
  ['supervise','/ˈsuːpəvaɪz/','v. 监督；管理；指导','supervision (n.监督)',"An engineer supervises the work.",'Parents should supervise young children.'],
  ['survey','/ˈsɜːveɪ/','n./v. 调查；勘测；审视',null,"A recent survey shows growing support.",'The crew surveyed the damage.'],
  ['survive','/səˈvaɪv/','v. 幸存；生存；比...活得长','survival (n.生存)',"Only a few survived.",'She survived her husband by ten years.'],
  ['suspend','/səˈspend/','v. 暂停；悬挂；使停职','suspension (n.暂停)',"Operations were suspended temporarily.",'The lamp was suspended from the ceiling.'],
  ['sustain','/səˈsteɪn/','v. 维持；支撑；遭受','sustainable (a.可持续的)',"The economy cannot sustain this growth.",'He sustained serious injuries.'],
  ['symbol','/ˈsɪmbl/','n. 象征；符号；标志','symbolic (a.象征性的)',"The dove is a symbol of peace.",'The symbol π represents pi.'],
  ['target','/ˈtɑːɡɪt/','n. 目标 v. 瞄准；针对',null,"The government set a target of zero emissions.",'The campaign targets young voters.'],
  ['technique','/tekˈniːk/','n. 技术；技巧；技能','technical (a.技术的)',"She uses a special painting technique.",'Good technique is essential in sports.'],
  ['technology','/tekˈnɒlədʒi/','n. 技术；工艺；科技',null,"Modern technology has changed communication.",'The company invests heavily in technology.'],
  ['temporary','/ˈtemprəri/','adj. 临时的；暂时的',null,"This is only a temporary solution.",'She took a temporary job.'],
  ['tendency','/ˈtendənsi/','n. 趋势；倾向；癖好','tend (v.倾向)',"She has a tendency to worry.",'There is a growing tendency towards remote work.'],
  ['threat','/θret/','n. 威胁；恐吓；凶兆','threaten (v.威胁)',"Cyber attacks pose a serious threat.",'The threat of rain canceled the picnic.'],
  ['tolerate','/ˈtɒləreɪt/','v. 容忍；忍受；容许','tolerance (n.容忍)',"We cannot tolerate harassment.",'The plant tolerates dry conditions.'],
  ['trace','/treɪs/','v. 追踪；追溯 n. 痕迹；微量',null,"Police traced the source of the call.",'The ship vanished without trace.'],
  ['tradition','/trəˈdɪʃn/','n. 传统；惯例','traditional (a.传统的)',"It's a Chinese tradition.",'We must respect local traditions.'],
  ['transfer','/trænsˈfɜːr/','v./n. 转移；转让；调动；换乘',null,"You can transfer money online.",'She transferred to another school.'],
  ['transform','/trænsˈfɔːm/','v. 改变；转换；改造','transformation (n.改变)',"The CEO transformed the company.",'The area was transformed by development.'],
  ['transition','/trænˈzɪʃn/','n. 过渡；转变；变迁',null,"The country is in transition.",'The transition was smooth.'],
  ['trend','/trend/','n. 趋势；潮流；动向',null,"The latest trend is minimalism.",'We need to follow market trends.'],
  ['trigger','/ˈtrɪɡər/','v. 触发；引起 n. 扳机；诱因',null,"Certain foods trigger allergies.",'Stress can be a trigger for illness.'],
  ['ultimate','/ˈʌltɪmət/','adj. 最终的；根本的；极致的',null,"The ultimate goal is sustainability.",'She has the ultimate responsibility.'],
  ['undergo','/ˌʌndəˈɡəʊ/','v. 经历；遭受；接受',null,"The building will undergo renovations.",'She underwent major surgery.'],
  ['undertake','/ˌʌndəˈteɪk/','v. 承担；从事；承诺',null,"The company undertook a full review.",'He undertook to finish the work on time.'],
  ['unique','/juˈniːk/','adj. 独特的；唯一的；罕见的',null,"Each person has unique talents.",'This is a unique opportunity.'],
  ['urban','/ˈɜːbən/','adj. 城市的；都市的','suburban (a.郊区的)',"Urban areas are growing rapidly.",'Urban planning is a complex field.'],
  ['urge','/ɜːdʒ/','v. 敦促；力劝 n. 冲动；强烈欲望',null,"I urge you to reconsider.",'She felt an urge to travel.'],
  ['utilize','/ˈjuːtəlaɪz/','v. 利用；使用','utility (n.实用)',"We should utilize all resources.",'The system utilizes solar power.'],
  ['valid','/ˈvælɪd/','adj. 有效的；合理的；正当的','validity (n.有效性)',"Your passport must be valid.",'She made a valid point.'],
  ['variety','/vəˈraɪəti/','n. 多样性；种类；变化','various (a.各种各样的)',"The shop offers a wide variety.",'I like variety in my work.'],
  ['version','/ˈvɜːʃn/','n. 版本；说法；译本',null,"The latest version has new features.",'Let me tell you my version of events.'],
  ['victim','/ˈvɪktɪm/','n. 受害者；牺牲品；受骗者',null,"The charity supports victims of crime.",'He fell victim to a scam.'],
  ['virtue','/ˈvɜːtʃuː/','n. 美德；优点；德行','virtual (a.虚拟的)',"Patience is a virtue.",'The plan has the virtue of simplicity.'],
  ['visible','/ˈvɪzəbl/','adj. 可见的；明显的','visibility (n.可见度)',"The mountain is clearly visible.",'There has been visible improvement.'],
  ['vision','/ˈvɪʒn/','n. 视力；愿景；远见；幻象',null,"The company has a clear vision.",'She has excellent vision.'],
  ['volume','/ˈvɒljuːm/','n. 量；体积；音量；卷',null,"Please turn down the volume.",'A large volume of data was processed.'],
  ['volunteer','/ˌvɒlənˈtɪər/','n. 志愿者 v. 自愿做','voluntary (a.自愿的)',"Many people volunteer at charities.",'She volunteered to help.'],
  ['welfare','/ˈwelfeər/','n. 福利；幸福；安康',null,"The government provides welfare.",'We are concerned about your welfare.'],
  ['widespread','/ˈwaɪdspred/','adj. 广泛的；普遍的',null,"There is widespread concern.",'The disease is widespread in the region.'],
  ['witness','/ˈwɪtnəs/','n. 证人 v. 目击；见证',null,"Police interviewed witnesses.",'We witnessed a historic event.'],
  ['worthwhile','/ˌwɜːθˈwaɪl/','adj. 值得的；有价值的',null,"The effort was worthwhile.",'Is it worthwhile to continue?'],
  ['yield','/jiːld/','v. 产出；屈服 n. 产量；收益',null,"The talks failed to yield results.",'The crop yield was high this year.'],
];

// Add quick words as full entries
allWords.push(...quickWords.map(w => ({
  word: w[0], phonetic: w[1], meaning: w[2], derivatives: w[3] ? [w[3]] : [],
  examples: [w[4], w[5]].filter(Boolean),
  collocations: [],
})));

// Deduplicate by word
const seen = new Set();
const unique = allWords.filter(w => { if (seen.has(w.word)) return false; seen.add(w.word); return true; });

// Build final output
const output = [];
unique.forEach((w, i) => {
  output.push({
    id: `w_${String(i+1).padStart(5,'0')}`,
    word: w.word, phonetic: w.phonetic, meaning: w.meaning,
    examples: w.examples || [],
    collocations: w.collocations || [],
    derivatives: w.derivatives || [],
  });
});

fs.writeFileSync('public/assets/words/wordbank.json', JSON.stringify({ name:'English Word Bank', version:'1.0', total: output.length, words: output }, null, 2));
console.log(`Generated ${output.length} words with examples + collocations`);
