/**
 * Generate kaoyan_basic.json — 考研英语二核心词汇 500+
 * Run: node scripts/gen_kaoyan.js
 */
const fs = require('fs');

const words = [
  // === 高频必考词 (high-frequency) ===
  ['abandon', '/əˈbændən/', 'v. 放弃；抛弃'],
  ['absorb', '/əbˈzɔːb/', 'v. 吸收；吸引'],
  ['abstract', '/ˈæbstrækt/', 'adj. 抽象的 n. 摘要'],
  ['abuse', '/əˈbjuːz/', 'v./n. 滥用；虐待'],
  ['academic', '/ˌækəˈdemɪk/', 'adj. 学术的；学院的'],
  ['accelerate', '/əkˈseləreɪt/', 'v. 加速；促进'],
  ['access', '/ˈækses/', 'n. 通道；使用权 v. 访问'],
  ['accommodate', '/əˈkɒmədeɪt/', 'v. 容纳；适应'],
  ['accompany', '/əˈkʌmpəni/', 'v. 陪伴；伴随'],
  ['accomplish', '/əˈkʌmplɪʃ/', 'v. 完成；实现'],
  ['account', '/əˈkaʊnt/', 'n. 账户；解释 v. 说明'],
  ['accumulate', '/əˈkjuːmjəleɪt/', 'v. 积累；积聚'],
  ['accurate', '/ˈækjərət/', 'adj. 准确的；精确的'],
  ['achieve', '/əˈtʃiːv/', 'v. 达到；取得'],
  ['acknowledge', '/əkˈnɒlɪdʒ/', 'v. 承认；确认'],
  ['acquire', '/əˈkwaɪər/', 'v. 获得；习得'],
  ['adapt', '/əˈdæpt/', 'v. 适应；改编'],
  ['adequate', '/ˈædɪkwət/', 'adj. 足够的；适当的'],
  ['adjust', '/əˈdʒʌst/', 'v. 调整；适应'],
  ['administer', '/ədˈmɪnɪstər/', 'v. 管理；执行'],
  ['adopt', '/əˈdɒpt/', 'v. 采纳；收养'],
  ['advocate', '/ˈædvəkeɪt/', 'v. 提倡；拥护 n. 倡导者'],
  ['affect', '/əˈfekt/', 'v. 影响；感动'],
  ['aggressive', '/əˈɡresɪv/', 'adj. 侵略的；好斗的'],
  ['allocate', '/ˈæləkeɪt/', 'v. 分配；拨出'],
  ['alternative', '/ɔːlˈtɜːnətɪv/', 'adj. 替代的 n. 选择'],
  ['ambiguous', '/æmˈbɪɡjuəs/', 'adj. 模糊的；模棱两可的'],
  ['ambitious', '/æmˈbɪʃəs/', 'adj. 有雄心的'],
  ['analysis', '/əˈnæləsɪs/', 'n. 分析；解析'],
  ['anticipate', '/ænˈtɪsɪpeɪt/', 'v. 预期；期望'],
  ['apparent', '/əˈpærənt/', 'adj. 明显的；表面上的'],
  ['appeal', '/əˈpiːl/', 'v./n. 呼吁；吸引'],
  ['appliance', '/əˈplaɪəns/', 'n. 电器；器具'],
  ['apply', '/əˈplaɪ/', 'v. 申请；应用'],
  ['approach', '/əˈprəʊtʃ/', 'v. 接近 n. 方法'],
  ['appropriate', '/əˈprəʊpriət/', 'adj. 适当的 v. 挪用'],
  ['approve', '/əˈpruːv/', 'v. 批准；赞成'],
  ['arise', '/əˈraɪz/', 'v. 出现；产生'],
  ['artificial', '/ˌɑːtɪˈfɪʃl/', 'adj. 人造的；虚假的'],
  ['aspect', '/ˈæspekt/', 'n. 方面；层面'],
  ['assemble', '/əˈsembl/', 'v. 集合；组装'],
  ['assess', '/əˈses/', 'v. 评估；评定'],
  ['assign', '/əˈsaɪn/', 'v. 分配；指派'],
  ['assist', '/əˈsɪst/', 'v. 帮助；协助'],
  ['associate', '/əˈsəʊʃieɪt/', 'v. 联系；关联 n. 同事'],
  ['assume', '/əˈsjuːm/', 'v. 假设；承担'],
  ['assure', '/əˈʃʊər/', 'v. 保证；使确信'],
  ['atmosphere', '/ˈætməsfɪər/', 'n. 气氛；大气层'],
  ['attach', '/əˈtætʃ/', 'v. 附上；连接'],
  ['attain', '/əˈteɪn/', 'v. 达到；获得'],
  ['attempt', '/əˈtempt/', 'v./n. 尝试；企图'],
  ['attribute', '/ˈætrɪbjuːt/', 'v. 归因于 n. 属性'],
  ['authority', '/ɔːˈθɒrəti/', 'n. 权威；当局'],
  ['available', '/əˈveɪləbl/', 'adj. 可用的；有效的'],
  ['aware', '/əˈweər/', 'adj. 意识到的；知道的'],
  ['barrier', '/ˈbæriər/', 'n. 障碍；屏障'],
  ['behalf', '/bɪˈhɑːf/', 'n. 代表；利益'],
  ['behave', '/bɪˈheɪv/', 'v. 表现；行为'],
  ['benefit', '/ˈbenɪfɪt/', 'n. 利益 v. 受益'],
  ['boom', '/buːm/', 'n. 繁荣 v. 激增'],
  ['bound', '/baʊnd/', 'adj. 一定的；受约束的'],
  ['budget', '/ˈbʌdʒɪt/', 'n. 预算 v. 安排'],
  ['burden', '/ˈbɜːdn/', 'n. 负担 v. 使负重'],
  ['campaign', '/kæmˈpeɪn/', 'n. 运动；战役'],
  ['capacity', '/kəˈpæsəti/', 'n. 能力；容量'],
  ['capture', '/ˈkæptʃər/', 'v. 捕获；吸引'],
  ['career', '/kəˈrɪər/', 'n. 职业；生涯'],
  ['challenge', '/ˈtʃæləndʒ/', 'n./v. 挑战；质疑'],
  ['channel', '/ˈtʃænl/', 'n. 渠道；频道'],
  ['characteristic', '/ˌkærəktəˈrɪstɪk/', 'n. 特征 adj. 典型的'],
  ['circumstance', '/ˈsɜːkəmstəns/', 'n. 环境；情况'],
  ['claim', '/kleɪm/', 'v./n. 声称；要求；索赔'],
  ['classify', '/ˈklæsɪfaɪ/', 'v. 分类；归类'],
  ['collapse', '/kəˈlæps/', 'v./n. 崩溃；倒塌'],
  ['combine', '/kəmˈbaɪn/', 'v. 结合；联合'],
  ['comment', '/ˈkɒment/', 'n./v. 评论；意见'],
  ['commission', '/kəˈmɪʃn/', 'n. 委员会；佣金'],
  ['commit', '/kəˈmɪt/', 'v. 犯（罪）；承诺；投入'],
  ['communicate', '/kəˈmjuːnɪkeɪt/', 'v. 交流；传达'],
  ['community', '/kəˈmjuːnəti/', 'n. 社区；团体'],
  ['companion', '/kəmˈpæniən/', 'n. 同伴；伙伴'],
  ['compare', '/kəmˈpeər/', 'v. 比较；对比'],
  ['compensate', '/ˈkɒmpenseɪt/', 'v. 补偿；赔偿'],
  ['compete', '/kəmˈpiːt/', 'v. 竞争；比赛'],
  ['competitive', '/kəmˈpetətɪv/', 'adj. 竞争的；有竞争力的'],
  ['complain', '/kəmˈpleɪn/', 'v. 抱怨；投诉'],
  ['complex', '/ˈkɒmpleks/', 'adj. 复杂的 n. 综合体'],
  ['component', '/kəmˈpəʊnənt/', 'n. 成分；组件'],
  ['comprehensive', '/ˌkɒmprɪˈhensɪv/', 'adj. 全面的；综合的'],
  ['concentrate', '/ˈkɒnsntreɪt/', 'v. 集中；专注'],
  ['concept', '/ˈkɒnsept/', 'n. 概念；观念'],
  ['concern', '/kənˈsɜːn/', 'n./v. 关心；担忧；涉及'],
  ['conclude', '/kənˈkluːd/', 'v. 总结；结束'],
  ['conduct', '/ˈkɒndʌkt/', 'n. 行为 v. 实施；引导'],
  ['conference', '/ˈkɒnfərəns/', 'n. 会议；讨论会'],
  ['confident', '/ˈkɒnfɪdənt/', 'adj. 自信的；确信的'],
  ['confirm', '/kənˈfɜːm/', 'v. 确认；证实'],
  ['conflict', '/ˈkɒnflɪkt/', 'n. 冲突 v. 抵触'],
  ['confront', '/kənˈfrʌnt/', 'v. 面对；对抗'],
  ['conscious', '/ˈkɒnʃəs/', 'adj. 有意识的；清醒的'],
  ['consequence', '/ˈkɒnsɪkwəns/', 'n. 结果；后果'],
  ['conserve', '/kənˈsɜːv/', 'v. 保存；节约'],
  ['considerable', '/kənˈsɪdərəbl/', 'adj. 相当大的；可观的'],
  ['consistent', '/kənˈsɪstənt/', 'adj. 一致的；始终如一的'],
  ['constant', '/ˈkɒnstənt/', 'adj. 持续的；不变的'],
  ['constitute', '/ˈkɒnstɪtjuːt/', 'v. 构成；组成'],
  ['construct', '/kənˈstrʌkt/', 'v. 建造；构建'],
  ['consume', '/kənˈsjuːm/', 'v. 消费；消耗'],
  ['contact', '/ˈkɒntækt/', 'n./v. 接触；联系'],
  ['contemporary', '/kənˈtemprəri/', 'adj. 当代的；同时代的'],
  ['contribute', '/kənˈtrɪbjuːt/', 'v. 贡献；捐献；导致'],
  ['controversial', '/ˌkɒntrəˈvɜːʃl/', 'adj. 有争议的'],
  ['convenient', '/kənˈviːniənt/', 'adj. 方便的'],
  ['conventional', '/kənˈvenʃənl/', 'adj. 传统的；常规的'],
  ['convince', '/kənˈvɪns/', 'v. 说服；使确信'],
  ['cooperate', '/kəʊˈɒpəreɪt/', 'v. 合作；协作'],
  ['coordinate', '/kəʊˈɔːdɪneɪt/', 'v. 协调 n. 坐标'],
  ['corporation', '/ˌkɔːpəˈreɪʃn/', 'n. 公司；企业'],
  ['correspond', '/ˌkɒrəˈspɒnd/', 'v. 符合；对应；通信'],
  ['council', '/ˈkaʊnsl/', 'n. 委员会；理事会'],
  ['countless', '/ˈkaʊntləs/', 'adj. 无数的'],
  ['crash', '/kræʃ/', 'v./n. 碰撞；崩溃'],
  ['create', '/kriˈeɪt/', 'v. 创造；引起'],
  ['criminal', '/ˈkrɪmɪnl/', 'adj. 犯罪的 n. 罪犯'],
  ['crisis', '/ˈkraɪsɪs/', 'n. 危机；紧要关头'],
  ['critical', '/ˈkrɪtɪkl/', 'adj. 批评的；关键的'],
  ['crucial', '/ˈkruːʃl/', 'adj. 关键的；决定性的'],
  ['cultivate', '/ˈkʌltɪveɪt/', 'v. 培养；耕作'],
  ['curiosity', '/ˌkjʊəriˈɒsəti/', 'n. 好奇心；珍品'],
  ['current', '/ˈkʌrənt/', 'adj. 当前的 n. 水流；电流'],
  ['debate', '/dɪˈbeɪt/', 'n./v. 辩论；讨论'],
  ['decade', '/ˈdekeɪd/', 'n. 十年'],
  ['decline', '/dɪˈklaɪn/', 'v./n. 下降；拒绝'],
  ['defend', '/dɪˈfend/', 'v. 防御；辩护'],
  ['define', '/dɪˈfaɪn/', 'v. 定义；界定'],
  ['definitely', '/ˈdefɪnətli/', 'adv. 肯定地；明确地'],
  ['deliver', '/dɪˈlɪvər/', 'v. 递送；发表；接生'],
  ['demand', '/dɪˈmɑːnd/', 'n./v. 要求；需求'],
  ['demonstrate', '/ˈdemənstreɪt/', 'v. 证明；示范；示威'],
  ['deny', '/dɪˈnaɪ/', 'v. 否认；拒绝'],
  ['depart', '/dɪˈpɑːt/', 'v. 离开；出发'],
  ['depend', '/dɪˈpend/', 'v. 依赖；取决于'],
  ['deposit', '/dɪˈpɒzɪt/', 'v. 存放 n. 存款；押金'],
  ['depression', '/dɪˈpreʃn/', 'n. 沮丧；萧条'],
  ['derive', '/dɪˈraɪv/', 'v. 源自；获得'],
  ['deserve', '/dɪˈzɜːv/', 'v. 值得；应得'],
  ['desire', '/dɪˈzaɪər/', 'n./v. 渴望；欲望'],
  ['desperate', '/ˈdespərət/', 'adj. 绝望的；不顾一切的'],
  ['despite', '/dɪˈspaɪt/', 'prep. 尽管；虽然'],
  ['destination', '/ˌdestɪˈneɪʃn/', 'n. 目的地'],
  ['destroy', '/dɪˈstrɔɪ/', 'v. 破坏；毁灭'],
  ['detect', '/dɪˈtekt/', 'v. 发现；探测'],
  ['determine', '/dɪˈtɜːmɪn/', 'v. 决定；确定'],
  ['device', '/dɪˈvaɪs/', 'n. 设备；装置'],
  ['devote', '/dɪˈvəʊt/', 'v. 致力于；奉献'],
  ['digital', '/ˈdɪdʒɪtl/', 'adj. 数字的'],
  ['discipline', '/ˈdɪsəplɪn/', 'n. 纪律；学科 v. 训练'],
  ['discrimination', '/dɪˌskrɪmɪˈneɪʃn/', 'n. 歧视；辨别'],
  ['display', '/dɪˈspleɪ/', 'v./n. 展示；显示'],
  ['dispute', '/dɪˈspjuːt/', 'n./v. 争论；纠纷'],
  ['dissolve', '/dɪˈzɒlv/', 'v. 溶解；解散'],
  ['distinct', '/dɪˈstɪŋkt/', 'adj. 不同的；明显的'],
  ['distinguish', '/dɪˈstɪŋɡwɪʃ/', 'v. 区分；辨别'],
  ['distribute', '/dɪˈstrɪbjuːt/', 'v. 分配；分布'],
  ['diverse', '/daɪˈvɜːs/', 'adj. 多样的；不同的'],
  ['domestic', '/dəˈmestɪk/', 'adj. 国内的；家庭的'],
  ['dominate', '/ˈdɒmɪneɪt/', 'v. 支配；主导'],
  ['draft', '/drɑːft/', 'n. 草稿 v. 起草'],
  ['dramatic', '/drəˈmætɪk/', 'adj. 戏剧性的；巨大的'],
  ['durable', '/ˈdjʊərəbl/', 'adj. 持久的；耐用的'],
  ['economic', '/ˌiːkəˈnɒmɪk/', 'adj. 经济的；经济学的'],
  ['efficient', '/ɪˈfɪʃnt/', 'adj. 高效的；有能力的'],
  ['elaborate', '/ɪˈlæbərət/', 'adj. 精心制作的 v. 详细说明'],
  ['eliminate', '/ɪˈlɪmɪneɪt/', 'v. 消除；淘汰'],
  ['embrace', '/ɪmˈbreɪs/', 'v. 拥抱；包含；欣然接受'],
  ['emerge', '/iˈmɜːdʒ/', 'v. 出现；浮现'],
  ['emergency', '/iˈmɜːdʒənsi/', 'n. 紧急情况'],
  ['emission', '/iˈmɪʃn/', 'n. 排放；散发'],
  ['emphasize', '/ˈemfəsaɪz/', 'v. 强调；着重'],
  ['employ', '/ɪmˈplɔɪ/', 'v. 雇用；使用'],
  ['enable', '/ɪˈneɪbl/', 'v. 使能够；启用'],
  ['encounter', '/ɪnˈkaʊntər/', 'v./n. 遇到；遭遇'],
  ['encourage', '/ɪnˈkʌrɪdʒ/', 'v. 鼓励；促进'],
  ['enforce', '/ɪnˈfɔːs/', 'v. 执行；强制'],
  ['engage', '/ɪnˈɡeɪdʒ/', 'v. 从事；参与；吸引'],
  ['enhance', '/ɪnˈhɑːns/', 'v. 增强；提高'],
  ['enormous', '/ɪˈnɔːməs/', 'adj. 巨大的；庞大的'],
  ['ensure', '/ɪnˈʃʊər/', 'v. 确保；保证'],
  ['enterprise', '/ˈentəpraɪz/', 'n. 企业；事业'],
  ['enthusiasm', '/ɪnˈθjuːziæzəm/', 'n. 热情；热心'],
  ['environment', '/ɪnˈvaɪrənmənt/', 'n. 环境'],
  ['equip', '/ɪˈkwɪp/', 'v. 装备；配备'],
  ['essential', '/ɪˈsenʃl/', 'adj. 必要的；本质的'],
  ['establish', '/ɪˈstæblɪʃ/', 'v. 建立；确立'],
  ['estimate', '/ˈestɪmeɪt/', 'v./n. 估计；评估'],
  ['evaluate', '/ɪˈvæljueɪt/', 'v. 评价；评估'],
  ['evidence', '/ˈevɪdəns/', 'n. 证据；迹象'],
  ['evolution', '/ˌiːvəˈluːʃn/', 'n. 进化；演变'],
  ['exceed', '/ɪkˈsiːd/', 'v. 超过；超越'],
  ['exception', '/ɪkˈsepʃn/', 'n. 例外；除外'],
  ['excessive', '/ɪkˈsesɪv/', 'adj. 过度的；过多的'],
  ['exchange', '/ɪksˈtʃeɪndʒ/', 'v./n. 交换；兑换'],
  ['exclude', '/ɪkˈskluːd/', 'v. 排除；排斥'],
  ['execute', '/ˈeksɪkjuːt/', 'v. 执行；实施'],
  ['executive', '/ɪɡˈzekjətɪv/', 'adj. 执行的 n. 高管'],
  ['exert', '/ɪɡˈzɜːt/', 'v. 施加；运用'],
  ['exhibit', '/ɪɡˈzɪbɪt/', 'v. 展览；显示 n. 展品'],
  ['exist', '/ɪɡˈzɪst/', 'v. 存在；生存'],
  ['expand', '/ɪkˈspænd/', 'v. 扩展；扩张'],
  ['expectation', '/ˌekspekˈteɪʃn/', 'n. 期望；预期'],
  ['expense', '/ɪkˈspens/', 'n. 费用；代价'],
  ['expertise', '/ˌekspɜːˈtiːz/', 'n. 专长；专业知识'],
  ['exploit', '/ɪkˈsplɔɪt/', 'v. 开发；剥削'],
  ['explore', '/ɪkˈsplɔːr/', 'v. 探索；探究'],
  ['export', '/ɪkˈspɔːt/', 'v. 出口 n. 出口产品'],
  ['expose', '/ɪkˈspəʊz/', 'v. 暴露；揭露'],
  ['extend', '/ɪkˈstend/', 'v. 延伸；扩展'],
  ['extensive', '/ɪkˈstensɪv/', 'adj. 广泛的；大量的'],
  ['external', '/ɪkˈstɜːnl/', 'adj. 外部的；外面的'],
  ['extraordinary', '/ɪkˈstrɔːdnri/', 'adj. 非凡的；特别的'],
  ['extreme', '/ɪkˈstriːm/', 'adj. 极端的 n. 极端'],
  ['facilitate', '/fəˈsɪlɪteɪt/', 'v. 促进；使便利'],
  ['facility', '/fəˈsɪləti/', 'n. 设施；设备'],
  ['factor', '/ˈfæktər/', 'n. 因素；要素'],
  ['feature', '/ˈfiːtʃər/', 'n. 特征；特色 v. 以...为特色'],
  ['federal', '/ˈfedərəl/', 'adj. 联邦的'],
  ['figure', '/ˈfɪɡər/', 'n. 数字；人物 v. 计算；认为'],
  ['finance', '/ˈfaɪnæns/', 'n. 金融 v. 资助'],
  ['flexible', '/ˈfleksəbl/', 'adj. 灵活的；柔韧的'],
  ['flourish', '/ˈflʌrɪʃ/', 'v. 繁荣；兴旺'],
  ['focus', '/ˈfəʊkəs/', 'v. 集中 n. 焦点'],
  ['forbid', '/fəˈbɪd/', 'v. 禁止；不许'],
  ['forecast', '/ˈfɔːkɑːst/', 'v./n. 预测；预报'],
  ['formal', '/ˈfɔːml/', 'adj. 正式的；形式的'],
  ['former', '/ˈfɔːmər/', 'adj. 前者的；以前的'],
  ['foundation', '/faʊnˈdeɪʃn/', 'n. 基础；基金会'],
  ['framework', '/ˈfreɪmwɜːk/', 'n. 框架；结构'],
  ['frequent', '/ˈfriːkwənt/', 'adj. 频繁的'],
  ['fulfill', '/fʊlˈfɪl/', 'v. 实现；满足'],
  ['function', '/ˈfʌŋkʃn/', 'n. 功能 v. 运行'],
  ['fundamental', '/ˌfʌndəˈmentl/', 'adj. 基本的 n. 原理'],
  ['generate', '/ˈdʒenəreɪt/', 'v. 产生；生成'],
  ['generous', '/ˈdʒenərəs/', 'adj. 慷慨的；丰富的'],
  ['global', '/ˈɡləʊbl/', 'adj. 全球的；整体的'],
  ['govern', '/ˈɡʌvn/', 'v. 统治；管理'],
  ['guarantee', '/ˌɡærənˈtiː/', 'v./n. 保证；担保'],
  ['handle', '/ˈhændl/', 'v. 处理 n. 把手'],
  ['hardship', '/ˈhɑːdʃɪp/', 'n. 困难；艰苦'],
  ['highlight', '/ˈhaɪlaɪt/', 'v. 强调；突出 n. 亮点'],
  ['household', '/ˈhaʊshəʊld/', 'n. 家庭 adj. 家用的'],
  ['identical', '/aɪˈdentɪkl/', 'adj. 完全相同的'],
  ['identify', '/aɪˈdentɪfaɪ/', 'v. 识别；确认'],
  ['ignore', '/ɪɡˈnɔːr/', 'v. 忽视；不理睬'],
  ['illustrate', '/ˈɪləstreɪt/', 'v. 说明；举例'],
  ['immigrant', '/ˈɪmɪɡrənt/', 'n. 移民'],
  ['impact', '/ˈɪmpækt/', 'n. 影响 v. 冲击'],
  ['implement', '/ˈɪmplɪment/', 'v. 实施；执行'],
  ['imply', '/ɪmˈplaɪ/', 'v. 暗示；意味着'],
  ['impose', '/ɪmˈpəʊz/', 'v. 强加；征收'],
  ['incentive', '/ɪnˈsentɪv/', 'n. 激励；动机'],
  ['incident', '/ˈɪnsɪdənt/', 'n. 事件；事故'],
  ['income', '/ˈɪnkʌm/', 'n. 收入；收益'],
  ['indicate', '/ˈɪndɪkeɪt/', 'v. 表明；指示'],
  ['individual', '/ˌɪndɪˈvɪdʒuəl/', 'adj. 个人的 n. 个体'],
  ['industrial', '/ɪnˈdʌstriəl/', 'adj. 工业的；产业的'],
  ['inevitable', '/ɪnˈevɪtəbl/', 'adj. 不可避免的'],
  ['influence', '/ˈɪnfluəns/', 'n./v. 影响；作用'],
  ['initial', '/ɪˈnɪʃl/', 'adj. 最初的 n. 首字母'],
  ['initiative', '/ɪˈnɪʃətɪv/', 'n. 主动性；倡议'],
  ['innovation', '/ˌɪnəˈveɪʃn/', 'n. 创新；革新'],
  ['insight', '/ˈɪnsaɪt/', 'n. 洞察力；深刻见解'],
  ['institute', '/ˈɪnstɪtjuːt/', 'n. 机构；学院 v. 建立'],
  ['institution', '/ˌɪnstɪˈtjuːʃn/', 'n. 制度；机构'],
  ['insurance', '/ɪnˈʃʊərəns/', 'n. 保险'],
  ['integrate', '/ˈɪntɪɡreɪt/', 'v. 整合；融入'],
  ['intellectual', '/ˌɪntəˈlektʃuəl/', 'adj. 智力的 n. 知识分子'],
  ['intense', '/ɪnˈtens/', 'adj. 强烈的；激烈的'],
  ['interact', '/ˌɪntərˈækt/', 'v. 互动；相互作用'],
  ['interpret', '/ɪnˈtɜːprɪt/', 'v. 解释；口译'],
  ['invest', '/ɪnˈvest/', 'v. 投资；投入'],
  ['investigate', '/ɪnˈvestɪɡeɪt/', 'v. 调查；研究'],
  ['involve', '/ɪnˈvɒlv/', 'v. 涉及；包含；参与'],
  ['isolate', '/ˈaɪsəleɪt/', 'v. 隔离；孤立'],
  ['issue', '/ˈɪʃuː/', 'n. 问题；议题 v. 发布'],
  ['justify', '/ˈdʒʌstɪfaɪ/', 'v. 证明...正当'],
  ['keen', '/kiːn/', 'adj. 热衷的；敏锐的'],
  ['label', '/ˈleɪbl/', 'n. 标签 v. 标注'],
  ['launch', '/lɔːntʃ/', 'v. 发射；发起 n. 发布'],
  ['leading', '/ˈliːdɪŋ/', 'adj. 领先的；主要的'],
  ['legislation', '/ˌledʒɪsˈleɪʃn/', 'n. 立法；法规'],
  ['liability', '/ˌlaɪəˈbɪləti/', 'n. 责任；负债'],
  ['liberal', '/ˈlɪbərəl/', 'adj. 自由的；开明的'],
  ['limitation', '/ˌlɪmɪˈteɪʃn/', 'n. 限制；局限'],
  ['literal', '/ˈlɪtərəl/', 'adj. 字面的；逐字的'],
  ['logical', '/ˈlɒdʒɪkl/', 'adj. 逻辑的；合理的'],
  ['maintain', '/meɪnˈteɪn/', 'v. 维持；保养'],
  ['manipulate', '/məˈnɪpjuleɪt/', 'v. 操纵；操作'],
  ['manufacture', '/ˌmænjuˈfæktʃər/', 'v. 制造 n. 制造业'],
  ['massive', '/ˈmæsɪv/', 'adj. 巨大的；大量的'],
  ['mechanism', '/ˈmekənɪzəm/', 'n. 机制；原理'],
  ['mental', '/ˈmentl/', 'adj. 精神的；心理的'],
  ['military', '/ˈmɪlətri/', 'adj. 军事的 n. 军队'],
  ['moderate', '/ˈmɒdərət/', 'adj. 适度的 v. 缓和'],
  ['monitor', '/ˈmɒnɪtər/', 'v. 监控 n. 显示器'],
  ['motivate', '/ˈməʊtɪveɪt/', 'v. 激励；激发'],
  ['negative', '/ˈneɡətɪv/', 'adj. 消极的；负面的'],
  ['negotiate', '/nɪˈɡəʊʃieɪt/', 'v. 谈判；协商'],
  ['nevertheless', '/ˌnevəðəˈles/', 'adv. 然而；尽管如此'],
  ['notion', '/ˈnəʊʃn/', 'n. 概念；观念'],
  ['numerous', '/ˈnjuːmərəs/', 'adj. 许多的；大量的'],
  ['objective', '/əbˈdʒektɪv/', 'n. 目标 adj. 客观的'],
  ['obtain', '/əbˈteɪn/', 'v. 获得；得到'],
  ['obvious', '/ˈɒbviəs/', 'adj. 明显的'],
  ['occupation', '/ˌɒkjuˈpeɪʃn/', 'n. 职业；占领'],
  ['offend', '/əˈfend/', 'v. 冒犯；违反'],
  ['opponent', '/əˈpəʊnənt/', 'n. 对手；反对者'],
  ['opportunity', '/ˌɒpəˈtjuːnəti/', 'n. 机会；时机'],
  ['oppose', '/əˈpəʊz/', 'v. 反对；对抗'],
  ['option', '/ˈɒpʃn/', 'n. 选择；选项'],
  ['orient', '/ˈɔːrient/', 'v. 使朝向；定位'],
  ['original', '/əˈrɪdʒənl/', 'adj. 原始的；独创的 n. 原作'],
  ['outcome', '/ˈaʊtkʌm/', 'n. 结果；成果'],
  ['outline', '/ˈaʊtlaɪn/', 'n. 大纲 v. 概述'],
  ['overcome', '/ˌəʊvəˈkʌm/', 'v. 克服；战胜'],
  ['overlook', '/ˌəʊvəˈlʊk/', 'v. 忽视；俯瞰'],
  ['overseas', '/ˌəʊvəˈsiːz/', 'adv./adj. 海外；国外'],
  ['panel', '/ˈpænl/', 'n. 专门小组；面板'],
  ['participate', '/pɑːˈtɪsɪpeɪt/', 'v. 参与；参加'],
  ['particularly', '/pəˈtɪkjələli/', 'adv. 特别地；尤其'],
  ['passion', '/ˈpæʃn/', 'n. 热情；激情'],
  ['patent', '/ˈpætnt/', 'n. 专利 adj. 专利的'],
  ['peculiar', '/pɪˈkjuːliər/', 'adj. 特有的；奇怪的'],
  ['pension', '/ˈpenʃn/', 'n. 养老金；退休金'],
  ['perform', '/pəˈfɔːm/', 'v. 执行；表演'],
  ['permanent', '/ˈpɜːmənənt/', 'adj. 永久的；长期的'],
  ['personnel', '/ˌpɜːsəˈnel/', 'n. 人员；人事部门'],
  ['perspective', '/pəˈspektɪv/', 'n. 观点；视角'],
  ['phenomenon', '/fɪˈnɒmɪnən/', 'n. 现象；奇才'],
  ['philosophy', '/fɪˈlɒsəfi/', 'n. 哲学；人生观'],
  ['platform', '/ˈplætfɔːm/', 'n. 平台；站台'],
  ['policy', '/ˈpɒləsi/', 'n. 政策；方针'],
  ['portion', '/ˈpɔːʃn/', 'n. 部分；一份'],
  ['potential', '/pəˈtenʃl/', 'adj. 潜在的 n. 潜力'],
  ['poverty', '/ˈpɒvəti/', 'n. 贫穷；贫困'],
  ['practical', '/ˈpræktɪkl/', 'adj. 实际的；实用的'],
  ['precise', '/prɪˈsaɪs/', 'adj. 精确的；准确的'],
  ['predict', '/prɪˈdɪkt/', 'v. 预测；预言'],
  ['prejudice', '/ˈpredʒudɪs/', 'n. 偏见 v. 损害'],
  ['preserve', '/prɪˈzɜːv/', 'v. 保存；保护'],
  ['pressure', '/ˈpreʃər/', 'n. 压力 v. 施压'],
  ['previous', '/ˈpriːviəs/', 'adj. 以前的；先前的'],
  ['primary', '/ˈpraɪməri/', 'adj. 主要的；初级的'],
  ['principle', '/ˈprɪnsəpl/', 'n. 原则；原理'],
  ['priority', '/praɪˈɒrəti/', 'n. 优先权；重点'],
  ['procedure', '/prəˈsiːdʒər/', 'n. 程序；步骤'],
  ['proceed', '/prəˈsiːd/', 'v. 继续进行'],
  ['process', '/ˈprəʊses/', 'n. 过程 v. 处理'],
  ['productive', '/prəˈdʌktɪv/', 'adj. 多产的；富有成效的'],
  ['profession', '/prəˈfeʃn/', 'n. 职业；专业'],
  ['profit', '/ˈprɒfɪt/', 'n. 利润 v. 获益'],
  ['profound', '/prəˈfaʊnd/', 'adj. 深刻的；深远的'],
  ['progress', '/ˈprəʊɡres/', 'n./v. 进步；进展'],
  ['project', '/ˈprɒdʒekt/', 'n. 项目 v. 投射；预计'],
  ['promote', '/prəˈməʊt/', 'v. 促进；推广；晋升'],
  ['proper', '/ˈprɒpər/', 'adj. 适当的；正确的'],
  ['property', '/ˈprɒpəti/', 'n. 财产；性质'],
  ['proportion', '/prəˈpɔːʃn/', 'n. 比例；部分'],
  ['propose', '/prəˈpəʊz/', 'v. 提议；建议；求婚'],
  ['prospect', '/ˈprɒspekt/', 'n. 前景；展望'],
  ['prosperity', '/prɒˈsperəti/', 'n. 繁荣；兴旺'],
  ['purchase', '/ˈpɜːtʃəs/', 'v./n. 购买'],
  ['pursue', '/pəˈsjuː/', 'v. 追求；追赶'],
  ['qualify', '/ˈkwɒlɪfaɪ/', 'v. 使合格；限定'],
  ['random', '/ˈrændəm/', 'adj. 随机的；任意的'],
  ['range', '/reɪndʒ/', 'n. 范围 v. 变化；排列'],
  ['rapid', '/ˈræpɪd/', 'adj. 快速的；迅速的'],
  ['rational', '/ˈræʃnəl/', 'adj. 理性的；合理的'],
  ['readily', '/ˈredɪli/', 'adv. 容易地；乐意地'],
  ['reality', '/riˈæləti/', 'n. 现实；实际'],
  ['reasonable', '/ˈriːznəbl/', 'adj. 合理的；公道的'],
  ['recession', '/rɪˈseʃn/', 'n. 衰退；后退'],
  ['recognize', '/ˈrekəɡnaɪz/', 'v. 认出；承认'],
  ['recommend', '/ˌrekəˈmend/', 'v. 推荐；建议'],
  ['recover', '/rɪˈkʌvər/', 'v. 恢复；康复'],
  ['reduce', '/rɪˈdjuːs/', 'v. 减少；降低'],
  ['reflect', '/rɪˈflekt/', 'v. 反映；反射；反思'],
  ['reform', '/rɪˈfɔːm/', 'v./n. 改革；改造'],
  ['regard', '/rɪˈɡɑːd/', 'v. 看待 n. 尊重'],
  ['register', '/ˈredʒɪstər/', 'v. 登记；注册'],
  ['regulate', '/ˈreɡjuleɪt/', 'v. 调节；管理'],
  ['reinforce', '/ˌriːɪnˈfɔːs/', 'v. 加强；增强'],
  ['reject', '/rɪˈdʒekt/', 'v. 拒绝；排斥'],
  ['release', '/rɪˈliːs/', 'v./n. 释放；发布'],
  ['relevant', '/ˈreləvənt/', 'adj. 相关的；切题的'],
  ['reliable', '/rɪˈlaɪəbl/', 'adj. 可靠的；可信赖的'],
  ['relieve', '/rɪˈliːv/', 'v. 缓解；减轻'],
  ['rely', '/rɪˈlaɪ/', 'v. 依赖；依靠'],
  ['remain', '/rɪˈmeɪn/', 'v. 保持；剩余'],
  ['remarkable', '/rɪˈmɑːkəbl/', 'adj. 显著的；非凡的'],
  ['remote', '/rɪˈməʊt/', 'adj. 遥远的；偏僻的'],
  ['replace', '/rɪˈpleɪs/', 'v. 取代；替换'],
  ['represent', '/ˌreprɪˈzent/', 'v. 代表；表示'],
  ['reputation', '/ˌrepjuˈteɪʃn/', 'n. 名声；声誉'],
  ['require', '/rɪˈkwaɪər/', 'v. 需要；要求'],
  ['research', '/rɪˈsɜːtʃ/', 'n./v. 研究；调查'],
  ['resolve', '/rɪˈzɒlv/', 'v. 解决；决定'],
  ['resource', '/rɪˈsɔːs/', 'n. 资源；财力'],
  ['respond', '/rɪˈspɒnd/', 'v. 回应；反应'],
  ['responsible', '/rɪˈspɒnsəbl/', 'adj. 负责的；有责任的'],
  ['restore', '/rɪˈstɔːr/', 'v. 恢复；修复'],
  ['restrict', '/rɪˈstrɪkt/', 'v. 限制；约束'],
  ['reveal', '/rɪˈviːl/', 'v. 揭示；透露'],
  ['revenue', '/ˈrevənjuː/', 'n. 收入；税收'],
  ['reverse', '/rɪˈvɜːs/', 'v. 逆转 adj. 相反的'],
  ['revolution', '/ˌrevəˈluːʃn/', 'n. 革命；变革'],
  ['rival', '/ˈraɪvl/', 'n. 对手 v. 竞争'],
  ['route', '/ruːt/', 'n. 路线；路径'],
  ['routine', '/ruːˈtiːn/', 'n. 常规；例行公事'],
  ['salary', '/ˈsæləri/', 'n. 薪水；工资'],
  ['satellite', '/ˈsætəlaɪt/', 'n. 卫星；人造卫星'],
  ['scale', '/skeɪl/', 'n. 规模；比例 v. 攀登'],
  ['schedule', '/ˈʃedjuːl/', 'n. 时间表 v. 安排'],
  ['scheme', '/skiːm/', 'n. 计划；方案'],
  ['security', '/sɪˈkjʊərəti/', 'n. 安全；保障'],
  ['senator', '/ˈsenətər/', 'n. 参议员'],
  ['sensitive', '/ˈsensətɪv/', 'adj. 敏感的；体贴的'],
  ['series', '/ˈsɪəriːz/', 'n. 系列；连续'],
  ['severe', '/sɪˈvɪər/', 'adj. 严重的；严厉的'],
  ['shift', '/ʃɪft/', 'v./n. 转移；变化'],
  ['significant', '/sɪɡˈnɪfɪkənt/', 'adj. 重要的；显著的'],
  ['similar', '/ˈsɪmələr/', 'adj. 相似的；类似的'],
  ['somewhat', '/ˈsʌmwɒt/', 'adv. 有点；稍微'],
  ['source', '/sɔːs/', 'n. 来源；出处'],
  ['specific', '/spəˈsɪfɪk/', 'adj. 具体的；特定的'],
  ['stable', '/ˈsteɪbl/', 'adj. 稳定的 n. 马厩'],
  ['standard', '/ˈstændəd/', 'n. 标准 adj. 标准的'],
  ['statistics', '/stəˈtɪstɪks/', 'n. 统计；统计学'],
  ['status', '/ˈsteɪtəs/', 'n. 地位；状态'],
  ['strategy', '/ˈstrætədʒi/', 'n. 策略；战略'],
  ['stress', '/stres/', 'n. 压力 v. 强调'],
  ['structure', '/ˈstrʌktʃər/', 'n. 结构 v. 构建'],
  ['substantial', '/səbˈstænʃl/', 'adj. 大量的；实质的'],
  ['sufficient', '/səˈfɪʃnt/', 'adj. 足够的；充分的'],
  ['supervise', '/ˈsuːpəvaɪz/', 'v. 监督；管理'],
  ['surgery', '/ˈsɜːdʒəri/', 'n. 外科手术'],
  ['survey', '/ˈsɜːveɪ/', 'n./v. 调查；勘测'],
  ['survive', '/səˈvaɪv/', 'v. 幸存；生存'],
  ['suspend', '/səˈspend/', 'v. 暂停；悬挂'],
  ['sustain', '/səˈsteɪn/', 'v. 维持；支撑'],
  ['symbol', '/ˈsɪmbl/', 'n. 象征；符号'],
  ['target', '/ˈtɑːɡɪt/', 'n. 目标 v. 瞄准'],
  ['technique', '/tekˈniːk/', 'n. 技术；技巧'],
  ['technology', '/tekˈnɒlədʒi/', 'n. 技术；工艺'],
  ['temporary', '/ˈtemprəri/', 'adj. 临时的；暂时的'],
  ['tendency', '/ˈtendənsi/', 'n. 趋势；倾向'],
  ['terminal', '/ˈtɜːmɪnl/', 'adj. 末端的 n. 终端'],
  ['threat', '/θret/', 'n. 威胁；恐吓'],
  ['tolerate', '/ˈtɒləreɪt/', 'v. 容忍；忍受'],
  ['trace', '/treɪs/', 'v. 追踪 n. 痕迹'],
  ['tradition', '/trəˈdɪʃn/', 'n. 传统；惯例'],
  ['transfer', '/trænsˈfɜːr/', 'v./n. 转移；转让'],
  ['transform', '/trænsˈfɔːm/', 'v. 改变；转换'],
  ['transition', '/trænˈzɪʃn/', 'n. 过渡；转变'],
  ['transport', '/ˈtrænspɔːt/', 'v. 运输 n. 交通'],
  ['trend', '/trend/', 'n. 趋势；潮流'],
  ['trigger', '/ˈtrɪɡər/', 'v. 触发 n. 扳机'],
  ['ultimate', '/ˈʌltɪmət/', 'adj. 最终的；根本的'],
  ['undergo', '/ˌʌndəˈɡəʊ/', 'v. 经历；遭受'],
  ['underline', '/ˌʌndəˈlaɪn/', 'v. 强调；在...下划线'],
  ['undertake', '/ˌʌndəˈteɪk/', 'v. 承担；从事'],
  ['unique', '/juˈniːk/', 'adj. 独特的；唯一的'],
  ['urban', '/ˈɜːbən/', 'adj. 城市的；都市的'],
  ['urge', '/ɜːdʒ/', 'v. 敦促 n. 冲动'],
  ['utilize', '/ˈjuːtəlaɪz/', 'v. 利用；使用'],
  ['valid', '/ˈvælɪd/', 'adj. 有效的；合理的'],
  ['variety', '/vəˈraɪəti/', 'n. 多样性；种类'],
  ['version', '/ˈvɜːʃn/', 'n. 版本；说法'],
  ['veteran', '/ˈvetərən/', 'n. 老手；退伍军人'],
  ['victim', '/ˈvɪktɪm/', 'n. 受害者；牺牲品'],
  ['virtue', '/ˈvɜːtʃuː/', 'n. 美德；优点'],
  ['visible', '/ˈvɪzəbl/', 'adj. 可见的；明显的'],
  ['vision', '/ˈvɪʒn/', 'n. 视力；愿景'],
  ['volume', '/ˈvɒljuːm/', 'n. 量；体积；音量'],
  ['volunteer', '/ˌvɒlənˈtɪər/', 'n. 志愿者 v. 自愿'],
  ['welfare', '/ˈwelfeər/', 'n. 福利；幸福'],
  ['widespread', '/ˈwaɪdspred/', 'adj. 广泛的；普遍的'],
  ['witness', '/ˈwɪtnəs/', 'n. 证人 v. 目击'],
  ['worthwhile', '/ˌwɜːθˈwaɪl/', 'adj. 值得的'],
  ['yield', '/jiːld/', 'v. 产出；屈服 n. 产量'],
  // === 进阶词汇 (intermediate) ===
  ['abolish', '/əˈbɒlɪʃ/', 'v. 废除；取消'],
  ['abrupt', '/əˈbrʌpt/', 'adj. 突然的；唐突的'],
  ['absolute', '/ˈæbsəluːt/', 'adj. 绝对的；完全的'],
  ['abundance', '/əˈbʌndəns/', 'n. 丰富；充裕'],
  ['accuracy', '/ˈækjərəsi/', 'n. 准确性；精确度'],
  ['acknowledgment', '/əkˈnɒlɪdʒmənt/', 'n. 承认；感谢'],
  ['acquisition', '/ˌækwɪˈzɪʃn/', 'n. 获得；收购'],
  ['activation', '/ˌæktɪˈveɪʃn/', 'n. 激活；启动'],
  ['acute', '/əˈkjuːt/', 'adj. 严重的；急性的；敏锐的'],
  ['addiction', '/əˈdɪkʃn/', 'n. 上瘾；沉迷'],
  ['adolescent', '/ˌædəˈlesnt/', 'n. 青少年 adj. 青春期的'],
  ['adverse', '/ˈædvɜːs/', 'adj. 不利的；相反的'],
  ['affection', '/əˈfekʃn/', 'n. 喜爱；感情'],
  ['agenda', '/əˈdʒendə/', 'n. 议程；议事日程'],
  ['aggravate', '/ˈæɡrəveɪt/', 'v. 加重；使恶化'],
  ['aggregate', '/ˈæɡrɪɡət/', 'n. 总计 v. 聚集'],
  ['agony', '/ˈæɡəni/', 'n. 极大的痛苦'],
  ['alien', '/ˈeɪliən/', 'adj. 外国的；陌生的 n. 外星人'],
  ['allegation', '/ˌæləˈɡeɪʃn/', 'n. 指控；断言'],
  ['alliance', '/əˈlaɪəns/', 'n. 联盟；同盟'],
  ['allowance', '/əˈlaʊəns/', 'n. 津贴；零用钱'],
  ['alteration', '/ˌɔːltəˈreɪʃn/', 'n. 改变；修改'],
  ['amendment', '/əˈmendmənt/', 'n. 修正；修正案'],
  ['amusement', '/əˈmjuːzmənt/', 'n. 娱乐；消遣'],
  ['anniversary', '/ˌænɪˈvɜːsəri/', 'n. 周年纪念日'],
  ['annual', '/ˈænjuəl/', 'adj. 每年的 n. 年刊'],
  ['apparatus', '/ˌæpəˈreɪtəs/', 'n. 设备；仪器'],
  ['appetite', '/ˈæpɪtaɪt/', 'n. 食欲；胃口'],
  ['applicant', '/ˈæplɪkənt/', 'n. 申请人'],
  ['appraisal', '/əˈpreɪzl/', 'n. 评价；评估'],
  ['appreciation', '/əˌpriːʃiˈeɪʃn/', 'n. 欣赏；感激；升值'],
  ['approval', '/əˈpruːvl/', 'n. 批准；赞成'],
  ['arbitrary', '/ˈɑːbɪtrəri/', 'adj. 任意的；武断的'],
  ['architecture', '/ˈɑːkɪtektʃər/', 'n. 建筑；架构'],
  ['argument', '/ˈɑːɡjumənt/', 'n. 争论；论点'],
  ['assault', '/əˈsɔːlt/', 'n./v. 攻击；袭击'],
  ['assembly', '/əˈsembli/', 'n. 集会；组装'],
  ['assert', '/əˈsɜːt/', 'v. 断言；主张'],
  ['asset', '/ˈæset/', 'n. 资产；优点'],
  ['assignment', '/əˈsaɪnmənt/', 'n. 任务；分配'],
  ['assumption', '/əˈsʌmpʃn/', 'n. 假设；承担'],
  ['assurance', '/əˈʃʊərəns/', 'n. 保证；保险'],
  ['attainable', '/əˈteɪnəbl/', 'adj. 可达到的'],
  ['attendance', '/əˈtendəns/', 'n. 出席；参加'],
  ['attorney', '/əˈtɜːni/', 'n. 律师；代理人'],
  ['auction', '/ˈɔːkʃn/', 'n./v. 拍卖'],
  ['authentication', '/ɔːˌθentɪˈkeɪʃn/', 'n. 认证；验证'],
  ['automatic', '/ˌɔːtəˈmætɪk/', 'adj. 自动的'],
  ['autonomy', '/ɔːˈtɒnəmi/', 'n. 自治；自主权'],
  ['backup', '/ˈbækʌp/', 'n. 备份；支持'],
  ['bankruptcy', '/ˈbæŋkrʌptsi/', 'n. 破产'],
  ['bargain', '/ˈbɑːɡɪn/', 'n. 便宜货 v. 讨价还价'],
  ['batch', '/bætʃ/', 'n. 一批；一组'],
  ['bearing', '/ˈbeərɪŋ/', 'n. 关系；方位；轴承'],
  ['behavioral', '/bɪˈheɪvjərəl/', 'adj. 行为的'],
  ['bias', '/ˈbaɪəs/', 'n. 偏见 v. 使有偏见'],
  ['bidding', '/ˈbɪdɪŋ/', 'n. 投标；命令'],
  ['biodiversity', '/ˌbaɪəʊdaɪˈvɜːsəti/', 'n. 生物多样性'],
  ['blueprint', '/ˈbluːprɪnt/', 'n. 蓝图；计划'],
  ['bond', '/bɒnd/', 'n. 债券；纽带 v. 结合'],
  ['bonus', '/ˈbəʊnəs/', 'n. 奖金；红利'],
  ['breach', '/briːtʃ/', 'n./v. 违反；破坏'],
  ['breakdown', '/ˈbreɪkdaʊn/', 'n. 故障；崩溃；分解'],
  ['breed', '/briːd/', 'v. 繁殖；导致 n. 品种'],
  ['broadband', '/ˈbrɔːdbænd/', 'n. 宽带'],
  ['bubble', '/ˈbʌbl/', 'n. 泡沫 v. 冒泡'],
  ['bulk', '/bʌlk/', 'n. 大量；主体'],
  ['bureaucracy', '/bjʊəˈrɒkrəsi/', 'n. 官僚机构'],
  ['cabinet', '/ˈkæbɪnət/', 'n. 橱柜；内阁'],
  ['cable', '/ˈkeɪbl/', 'n. 电缆；缆绳'],
  ['candidate', '/ˈkændɪdət/', 'n. 候选人；应试者'],
  ['capability', '/ˌkeɪpəˈbɪləti/', 'n. 能力；才能'],
  ['cement', '/sɪˈment/', 'n. 水泥 v. 巩固'],
  ['certificate', '/səˈtɪfɪkət/', 'n. 证书；执照'],
  ['chancellor', '/ˈtʃɑːnsələr/', 'n. 大臣；总理；校长'],
  ['charity', '/ˈtʃærəti/', 'n. 慈善；慈善机构'],
  ['chronic', '/ˈkrɒnɪk/', 'adj. 慢性的；长期的'],
  ['circulate', '/ˈsɜːkjəleɪt/', 'v. 循环；流通'],
  ['civilian', '/sɪˈvɪliən/', 'n. 平民 adj. 民用的'],
  ['clarify', '/ˈklærɪfaɪ/', 'v. 澄清；阐明'],
  ['clash', '/klæʃ/', 'v./n. 冲突；碰撞'],
  ['client', '/ˈklaɪənt/', 'n. 客户；委托人'],
  ['clue', '/kluː/', 'n. 线索；提示'],
  ['coalition', '/ˌkəʊəˈlɪʃn/', 'n. 联盟；联合'],
  ['cognitive', '/ˈkɒɡnətɪv/', 'adj. 认知的'],
  ['collaborate', '/kəˈlæbəreɪt/', 'v. 合作；协作'],
  ['colonial', '/kəˈləʊniəl/', 'adj. 殖民地的'],
  ['commence', '/kəˈmens/', 'v. 开始；着手'],
  ['commercial', '/kəˈmɜːʃl/', 'adj. 商业的 n. 广告'],
  ['commodity', '/kəˈmɒdəti/', 'n. 商品；日用品'],
  ['compassion', '/kəmˈpæʃn/', 'n. 同情；怜悯'],
  ['compel', '/kəmˈpel/', 'v. 强迫；迫使'],
  ['competence', '/ˈkɒmpɪtəns/', 'n. 能力；胜任'],
  ['compile', '/kəmˈpaɪl/', 'v. 编译；汇编'],
  ['complement', '/ˈkɒmplɪment/', 'v. 补充 n. 补足物'],
  ['compliance', '/kəmˈplaɪəns/', 'n. 服从；遵守'],
  ['comply', '/kəmˈplaɪ/', 'v. 遵守；服从'],
  ['compound', '/ˈkɒmpaʊnd/', 'n. 化合物 adj. 复合的'],
  ['compromise', '/ˈkɒmprəmaɪz/', 'v./n. 妥协；折中'],
  ['conceive', '/kənˈsiːv/', 'v. 构想；怀孕'],
  ['conception', '/kənˈsepʃn/', 'n. 概念；构想'],
  ['condemn', '/kənˈdem/', 'v. 谴责；判刑'],
  ['confer', '/kənˈfɜːr/', 'v. 授予；商议'],
  ['confine', '/kənˈfaɪn/', 'v. 限制；禁闭'],
  ['congress', '/ˈkɒŋɡres/', 'n. 国会；代表大会'],
  ['conquest', '/ˈkɒŋkwest/', 'n. 征服；占领'],
  ['conscience', '/ˈkɒnʃəns/', 'n. 良心；良知'],
  ['consent', '/kənˈsent/', 'v./n. 同意；许可'],
  ['consolidate', '/kənˈsɒlɪdeɪt/', 'v. 巩固；合并'],
  ['conspiracy', '/kənˈspɪrəsi/', 'n. 阴谋；共谋'],
  ['constitution', '/ˌkɒnstɪˈtjuːʃn/', 'n. 宪法；构成'],
  ['constraint', '/kənˈstreɪnt/', 'n. 约束；限制'],
  ['consult', '/kənˈsʌlt/', 'v. 咨询；查阅'],
  ['consumption', '/kənˈsʌmpʃn/', 'n. 消费；消耗'],
  ['contend', '/kənˈtend/', 'v. 竞争；主张'],
  ['context', '/ˈkɒntekst/', 'n. 上下文；背景'],
  ['contract', '/ˈkɒntrækt/', 'n. 合同 v. 收缩；订约'],
  ['contradiction', '/ˌkɒntrəˈdɪkʃn/', 'n. 矛盾；反驳'],
  ['contrast', '/ˈkɒntrɑːst/', 'n. 对比 v. 形成对比'],
  ['contribution', '/ˌkɒntrɪˈbjuːʃn/', 'n. 贡献；捐款'],
  ['controversy', '/ˈkɒntrəvɜːsi/', 'n. 争论；争议'],
  ['convention', '/kənˈvenʃn/', 'n. 大会；惯例；公约'],
  ['convict', '/kənˈvɪkt/', 'v. 定罪 n. 罪犯'],
  ['conviction', '/kənˈvɪkʃn/', 'n. 定罪；坚信'],
  ['copyright', '/ˈkɒpiraɪt/', 'n. 版权'],
  ['core', '/kɔːr/', 'n. 核心；要点'],
  ['corporate', '/ˈkɔːpərət/', 'adj. 公司的；法人的'],
  ['corrupt', '/kəˈrʌpt/', 'adj. 腐败的 v. 使腐化'],
  ['counterpart', '/ˈkaʊntəpɑːt/', 'n. 对应的人或物'],
  ['crackdown', '/ˈkrækdaʊn/', 'n. 镇压；严厉打击'],
  ['craft', '/krɑːft/', 'n. 手艺；工艺 v. 精心制作'],
  ['creativity', '/ˌkriːeɪˈtɪvəti/', 'n. 创造力'],
  ['credential', '/krɪˈdenʃl/', 'n. 凭证；资历'],
  ['criterion', '/kraɪˈtɪəriən/', 'n. 标准；准则'],
  ['crude', '/kruːd/', 'adj. 粗糙的；天然的'],
  ['currency', '/ˈkʌrənsi/', 'n. 货币；通货'],
  ['curriculum', '/kəˈrɪkjələm/', 'n. 课程'],
  ['database', '/ˈdeɪtəbeɪs/', 'n. 数据库'],
  ['deadline', '/ˈdedlaɪn/', 'n. 截止日期'],
  ['dealer', '/ˈdiːlər/', 'n. 经销商；交易员'],
  ['deception', '/dɪˈsepʃn/', 'n. 欺骗；骗局'],
  ['declaration', '/ˌdekləˈreɪʃn/', 'n. 宣言；声明'],
  ['dedicate', '/ˈdedɪkeɪt/', 'v. 致力于；奉献'],
  ['deem', '/diːm/', 'v. 认为；视为'],
  ['defect', '/ˈdiːfekt/', 'n. 缺陷 v. 叛变'],
  ['deficit', '/ˈdefɪsɪt/', 'n. 赤字；亏损'],
  ['delegate', '/ˈdelɪɡət/', 'n. 代表 v. 委派'],
  ['deliberate', '/dɪˈlɪbərət/', 'adj. 故意的；深思熟虑的'],
  ['democracy', '/dɪˈmɒkrəsi/', 'n. 民主；民主制度'],
  ['demographic', '/ˌdeməˈɡræfɪk/', 'adj. 人口统计的'],
  ['density', '/ˈdensəti/', 'n. 密度；浓度'],
  ['depict', '/dɪˈpɪkt/', 'v. 描绘；描述'],
  ['deploy', '/dɪˈplɔɪ/', 'v. 部署；调动'],
  ['depress', '/dɪˈpres/', 'v. 使沮丧；按下'],
  ['deputy', '/ˈdepjuti/', 'n. 副手；代表'],
  ['descend', '/dɪˈsend/', 'v. 下降；遗传'],
  ['designate', '/ˈdezɪɡneɪt/', 'v. 指定；任命'],
  ['desirable', '/dɪˈzaɪərəbl/', 'adj. 令人满意的；可取的'],
  ['detain', '/dɪˈteɪn/', 'v. 拘留；耽搁'],
  ['deteriorate', '/dɪˈtɪəriəreɪt/', 'v. 恶化；退化'],
  ['devastate', '/ˈdevəsteɪt/', 'v. 毁灭；使震惊'],
  ['diagnose', '/ˈdaɪəɡnəʊz/', 'v. 诊断；判断'],
  ['dialogue', '/ˈdaɪəlɒɡ/', 'n. 对话；对白'],
  ['differentiate', '/ˌdɪfəˈrenʃieɪt/', 'v. 区分；区别'],
  ['dignity', '/ˈdɪɡnəti/', 'n. 尊严；高贵'],
  ['dilemma', '/dɪˈlemə/', 'n. 困境；进退两难'],
  ['diminish', '/dɪˈmɪnɪʃ/', 'v. 减少；缩小'],
  ['diplomatic', '/ˌdɪpləˈmætɪk/', 'adj. 外交的；有策略的'],
  ['discharge', '/dɪsˈtʃɑːdʒ/', 'v./n. 排放；解雇'],
  ['disclose', '/dɪsˈkləʊz/', 'v. 揭露；公开'],
  ['discourse', '/ˈdɪskɔːs/', 'n. 话语；论述'],
  ['discrepancy', '/dɪsˈkrepənsi/', 'n. 差异；不符'],
  ['disorder', '/dɪsˈɔːdər/', 'n. 混乱；失调'],
  ['dispatch', '/dɪˈspætʃ/', 'v. 派遣；发送'],
  ['disposal', '/dɪˈspəʊzl/', 'n. 处理；处置'],
  ['disrupt', '/dɪsˈrʌpt/', 'v. 扰乱；中断'],
  ['distort', '/dɪˈstɔːt/', 'v. 扭曲；歪曲'],
  ['distract', '/dɪˈstrækt/', 'v. 分散；使分心'],
  ['doctrine', '/ˈdɒktrɪn/', 'n. 教条；学说'],
  ['documentary', '/ˌdɒkjuˈmentri/', 'n. 纪录片 adj. 文件的'],
  ['domain', '/dəˈmeɪn/', 'n. 领域；域名'],
  ['donation', '/dəʊˈneɪʃn/', 'n. 捐赠；捐款'],
  ['dose', '/dəʊs/', 'n. 剂量 v. 给药'],
  ['drastic', '/ˈdræstɪk/', 'adj. 激烈的；猛烈的'],
  ['drift', '/drɪft/', 'v./n. 漂流；趋势'],
  ['drought', '/draʊt/', 'n. 干旱'],
  ['duration', '/djuˈreɪʃn/', 'n. 持续时间'],
  ['dynamic', '/daɪˈnæmɪk/', 'adj. 动态的；有活力的'],
  ['ecological', '/ˌiːkəˈlɒdʒɪkl/', 'adj. 生态的'],
  ['editorial', '/ˌedɪˈtɔːriəl/', 'adj. 编辑的 n. 社论'],
  ['efficiency', '/ɪˈfɪʃnsi/', 'n. 效率；效能'],
  ['electron', '/ɪˈlektrɒn/', 'n. 电子'],
  ['elegant', '/ˈelɪɡənt/', 'adj. 优雅的；精致的'],
  ['elevate', '/ˈelɪveɪt/', 'v. 提升；举起'],
  ['eligible', '/ˈelɪdʒəbl/', 'adj. 有资格的；合适的'],
  ['embed', '/ɪmˈbed/', 'v. 嵌入；植入'],
  ['emigrate', '/ˈemɪɡreɪt/', 'v. 移居国外'],
  ['empirical', '/ɪmˈpɪrɪkl/', 'adj. 经验的；实证的'],
  ['empower', '/ɪmˈpaʊər/', 'v. 授权；赋权'],
  ['enclosure', '/ɪnˈkləʊʒər/', 'n. 附件；围墙'],
  ['endanger', '/ɪnˈdeɪndʒər/', 'v. 危及；危害'],
  ['endorse', '/ɪnˈdɔːs/', 'v. 背书；支持；代言'],
  ['enforceable', '/ɪnˈfɔːsəbl/', 'adj. 可执行的'],
  ['enlighten', '/ɪnˈlaɪtn/', 'v. 启发；启迪'],
  ['entrepreneur', '/ˌɒntrəprəˈnɜːr/', 'n. 企业家'],
  ['entry', '/ˈentri/', 'n. 进入；条目'],
  ['equation', '/ɪˈkweɪʒn/', 'n. 方程；等式'],
  ['equivalent', '/ɪˈkwɪvələnt/', 'adj. 相等的 n. 等价物'],
  ['era', '/ˈɪərə/', 'n. 时代；纪元'],
  ['essence', '/ˈesns/', 'n. 本质；精华'],
  ['estate', '/ɪˈsteɪt/', 'n. 房产；庄园'],
  ['ethical', '/ˈeθɪkl/', 'adj. 伦理的；道德的'],
  ['ethnic', '/ˈeθnɪk/', 'adj. 民族的；种族的'],
  ['evoke', '/ɪˈvəʊk/', 'v. 唤起；引起'],
  ['exaggerate', '/ɪɡˈzædʒəreɪt/', 'v. 夸大；夸张'],
  ['excellence', '/ˈeksələns/', 'n. 卓越；优秀'],
  ['exceptional', '/ɪkˈsepʃənl/', 'adj. 例外的；杰出的'],
  ['excursion', '/ɪkˈskɜːʃn/', 'n. 远足；短途旅行'],
  ['execution', '/ˌeksɪˈkjuːʃn/', 'n. 执行；处决'],
  ['exempt', '/ɪɡˈzempt/', 'v. 免除 adj. 被免除的'],
  ['exhaust', '/ɪɡˈzɔːst/', 'v. 耗尽 n. 废气'],
  ['expedition', '/ˌekspəˈdɪʃn/', 'n. 远征；探险'],
  ['expenditure', '/ɪkˈspendɪtʃər/', 'n. 支出；花费'],
  ['experimental', '/ɪkˌsperɪˈmentl/', 'adj. 实验的'],
  ['explicit', '/ɪkˈsplɪsɪt/', 'adj. 明确的；直率的'],
  ['explosive', '/ɪkˈspləʊsɪv/', 'adj. 爆炸的 n. 炸药'],
  ['extension', '/ɪkˈstenʃn/', 'n. 延伸；扩展'],
  ['extract', '/ˈekstrækt/', 'v. 提取 n. 摘录'],
  ['fabric', '/ˈfæbrɪk/', 'n. 织物；结构'],
  ['faculty', '/ˈfæklti/', 'n. 才能；全体教员'],
  ['fascinate', '/ˈfæsɪneɪt/', 'v. 使着迷；吸引'],
  ['fatigue', '/fəˈtiːɡ/', 'n. 疲劳 v. 使疲劳'],
  ['feasible', '/ˈfiːzəbl/', 'adj. 可行的；可能的'],
  ['feedback', '/ˈfiːdbæk/', 'n. 反馈；回馈'],
  ['fertile', '/ˈfɜːtaɪl/', 'adj. 肥沃的；多产的'],
  ['fiscal', '/ˈfɪskl/', 'adj. 财政的；国库的'],
  ['flaw', '/flɔː/', 'n. 缺陷；瑕疵'],
  ['fleet', '/fliːt/', 'n. 舰队；车队'],
  ['fluctuate', '/ˈflʌktʃueɪt/', 'v. 波动；起伏'],
  ['forge', '/fɔːdʒ/', 'v. 锻造；伪造 n. 铁匠铺'],
  ['format', '/ˈfɔːmæt/', 'n. 格式 v. 格式化'],
  ['formula', '/ˈfɔːmjələ/', 'n. 公式；方案'],
  ['forthcoming', '/ˌfɔːθˈkʌmɪŋ/', 'adj. 即将到来的'],
  ['fraction', '/ˈfrækʃn/', 'n. 部分；分数'],
  ['franchise', '/ˈfræntʃaɪz/', 'n. 特许经营权；选举权'],
  ['friction', '/ˈfrɪkʃn/', 'n. 摩擦；冲突'],
  ['frontier', '/ˈfrʌntɪər/', 'n. 边界；前沿'],
  ['fruitful', '/ˈfruːtfl/', 'adj. 富有成效的'],
  ['frustrate', '/frʌˈstreɪt/', 'v. 使沮丧；挫败'],
  ['galaxy', '/ˈɡæləksi/', 'n. 星系；银河'],
  ['genius', '/ˈdʒiːniəs/', 'n. 天才；天赋'],
  ['genuine', '/ˈdʒenjuɪn/', 'adj. 真正的；真诚的'],
  ['gesture', '/ˈdʒestʃər/', 'n. 手势；姿态'],
  ['glamour', '/ˈɡlæmər/', 'n. 魅力；吸引力'],
  ['glimpse', '/ɡlɪmps/', 'n./v. 一瞥；瞥见'],
  ['grant', '/ɡrɑːnt/', 'v. 授予；允许 n. 补助金'],
  ['greenhouse', '/ˈɡriːnhaʊs/', 'n. 温室'],
  ['gross', '/ɡrəʊs/', 'adj. 总的；毛的 n. 总额'],
  ['guideline', '/ˈɡaɪdlaɪn/', 'n. 指导方针；指南'],
  ['habitat', '/ˈhæbɪtæt/', 'n. 栖息地；产地'],
  ['harassment', '/ˈhærəsmənt/', 'n. 骚扰；烦恼'],
  ['harsh', '/hɑːʃ/', 'adj. 严厉的；严酷的'],
  ['hazard', '/ˈhæzəd/', 'n. 危险 v. 冒险'],
  ['headline', '/ˈhedlaɪn/', 'n. 标题；头条新闻'],
  ['heritage', '/ˈherɪtɪdʒ/', 'n. 遗产；传统'],
  ['hierarchy', '/ˈhaɪərɑːki/', 'n. 等级制度；层次'],
  ['homogeneous', '/ˌhɒməˈdʒiːniəs/', 'adj. 同质的；相似的'],
  ['horizon', '/həˈraɪzn/', 'n. 地平线；眼界'],
  ['hostile', '/ˈhɒstaɪl/', 'adj. 敌对的；敌意的'],
  ['humanity', '/hjuːˈmænəti/', 'n. 人类；人性'],
  ['hypothesis', '/haɪˈpɒθəsɪs/', 'n. 假说；假设'],
  ['ideology', '/ˌaɪdiˈɒlədʒi/', 'n. 意识形态；思想体系'],
  ['illusion', '/ɪˈluːʒn/', 'n. 幻觉；错觉'],
  ['immense', '/ɪˈmens/', 'adj. 巨大的；广大的'],
  ['immerse', '/ɪˈmɜːs/', 'v. 沉浸；使陷入'],
  ['immune', '/ɪˈmjuːn/', 'adj. 免疫的；不受影响的'],
  ['impair', '/ɪmˈpeər/', 'v. 损害；削弱'],
  ['impartial', '/ɪmˈpɑːʃl/', 'adj. 公正的；不偏不倚的'],
  ['imperative', '/ɪmˈperətɪv/', 'adj. 必要的；命令的'],
  ['implication', '/ˌɪmplɪˈkeɪʃn/', 'n. 含义；暗示；牵连'],
  ['import', '/ɪmˈpɔːt/', 'v. 进口 n. 进口品'],
  ['impulse', '/ˈɪmpʌls/', 'n. 冲动；脉冲'],
  ['inadequate', '/ɪnˈædɪkwət/', 'adj. 不充分的'],
  ['incidence', '/ˈɪnsɪdəns/', 'n. 发生率；影响范围'],
  ['incline', '/ɪnˈklaɪn/', 'v. 倾向；倾斜'],
  ['incorporate', '/ɪnˈkɔːpəreɪt/', 'v. 合并；包含'],
  ['indicator', '/ˈɪndɪkeɪtər/', 'n. 指标；指示器'],
  ['indifferent', '/ɪnˈdɪfrənt/', 'adj. 漠不关心的'],
  ['indispensable', '/ˌɪndɪˈspensəbl/', 'adj. 不可或缺的'],
  ['induce', '/ɪnˈdjuːs/', 'v. 引起；诱导'],
  ['inferior', '/ɪnˈfɪəriər/', 'adj. 劣等的；下级的'],
  ['inflation', '/ɪnˈfleɪʃn/', 'n. 通货膨胀'],
  ['infrastructure', '/ˈɪnfrəstrʌktʃər/', 'n. 基础设施'],
  ['ingredient', '/ɪnˈɡriːdiənt/', 'n. 成分；要素'],
  ['inherent', '/ɪnˈhɪərənt/', 'adj. 固有的；内在的'],
  ['inherit', '/ɪnˈherɪt/', 'v. 继承；遗传'],
  ['inject', '/ɪnˈdʒekt/', 'v. 注射；注入'],
  ['inquiry', '/ɪnˈkwaɪəri/', 'n. 询问；调查'],
  ['insert', '/ɪnˈsɜːt/', 'v. 插入；嵌入'],
  ['inspect', '/ɪnˈspekt/', 'v. 检查；视察'],
  ['installment', '/ɪnˈstɔːlmənt/', 'n. 分期付款；部分'],
  ['instrument', '/ˈɪnstrəmənt/', 'n. 工具；乐器'],
  ['integral', '/ˈɪntɪɡrəl/', 'adj. 完整的；必需的'],
  ['integrity', '/ɪnˈteɡrəti/', 'n. 正直；完整'],
  ['intensive', '/ɪnˈtensɪv/', 'adj. 集中的；密集的'],
  ['intention', '/ɪnˈtenʃn/', 'n. 意图；目的'],
  ['interfere', '/ˌɪntəˈfɪər/', 'v. 干涉；干扰'],
  ['interior', '/ɪnˈtɪəriər/', 'n. 内部 adj. 内部的'],
  ['interpretation', '/ɪnˌtɜːprɪˈteɪʃn/', 'n. 解释；口译'],
  ['interval', '/ˈɪntəvl/', 'n. 间隔；间歇'],
  ['intervention', '/ˌɪntəˈvenʃn/', 'n. 干预；介入'],
  ['invasion', '/ɪnˈveɪʒn/', 'n. 入侵；侵略'],
  ['invisible', '/ɪnˈvɪzəbl/', 'adj. 看不见的'],
  ['irrigation', '/ˌɪrɪˈɡeɪʃn/', 'n. 灌溉'],
  ['journal', '/ˈdʒɜːnl/', 'n. 期刊；日志'],
  ['judicial', '/dʒuˈdɪʃl/', 'adj. 司法的；法庭的'],
  ['jurisdiction', '/ˌdʒʊərɪsˈdɪkʃn/', 'n. 管辖权；司法权'],
  ['lateral', '/ˈlætərəl/', 'adj. 横向的；侧面的'],
  ['lawn', '/lɔːn/', 'n. 草坪；草地'],
  ['layer', '/ˈleɪər/', 'n. 层；层次'],
  ['layout', '/ˈleɪaʊt/', 'n. 布局；设计'],
  ['lease', '/liːs/', 'n. 租约 v. 出租'],
  ['legacy', '/ˈleɡəsi/', 'n. 遗产；遗留影响'],
  ['legislative', '/ˈledʒɪslətɪv/', 'adj. 立法的'],
  ['legitimate', '/lɪˈdʒɪtɪmət/', 'adj. 合法的；正当的'],
  ['liberty', '/ˈlɪbəti/', 'n. 自由；许可'],
  ['likelihood', '/ˈlaɪklihʊd/', 'n. 可能性'],
  ['literacy', '/ˈlɪtərəsi/', 'n. 读写能力；素养'],
  ['litigation', '/ˌlɪtɪˈɡeɪʃn/', 'n. 诉讼；打官司'],
  ['loan', '/ləʊn/', 'n. 贷款 v. 借出'],
  ['lobby', '/ˈlɒbi/', 'n. 大厅 v. 游说'],
  ['longitude', '/ˈlɒŋɡɪtjuːd/', 'n. 经度'],
  ['magnitude', '/ˈmæɡnɪtjuːd/', 'n. 大小；重要性'],
  ['mainstream', '/ˈmeɪnstriːm/', 'n. 主流'],
  ['maintenance', '/ˈmeɪntənəns/', 'n. 维护；保养'],
  ['mandate', '/ˈmændeɪt/', 'n. 授权 v. 强制执行'],
  ['manifest', '/ˈmænɪfest/', 'v. 显示 adj. 明显的'],
  ['margin', '/ˈmɑːdʒɪn/', 'n. 边缘；利润；余地'],
  ['maximum', '/ˈmæksɪməm/', 'n. 最大 adj. 最大的'],
  ['medium', '/ˈmiːdiəm/', 'n. 媒介 adj. 中等的'],
  ['mercy', '/ˈmɜːsi/', 'n. 仁慈；怜悯'],
  ['merit', '/ˈmerɪt/', 'n. 优点 v. 值得'],
  ['metropolitan', '/ˌmetrəˈpɒlɪtən/', 'adj. 大都市的'],
  ['migrate', '/maɪˈɡreɪt/', 'v. 迁移；移居'],
  ['minister', '/ˈmɪnɪstər/', 'n. 部长；大臣'],
  ['minority', '/maɪˈnɒrəti/', 'n. 少数；少数民族'],
  ['misfortune', '/ˌmɪsˈfɔːtʃuːn/', 'n. 不幸；厄运'],
  ['mission', '/ˈmɪʃn/', 'n. 使命；任务'],
  ['mobility', '/məʊˈbɪləti/', 'n. 流动性；移动性'],
  ['momentum', '/məˈmentəm/', 'n. 动力；势头'],
  ['monopoly', '/məˈnɒpəli/', 'n. 垄断；独占'],
  ['moral', '/ˈmɒrəl/', 'adj. 道德的 n. 寓意'],
  ['mortality', '/mɔːˈtæləti/', 'n. 死亡率；必死'],
  ['mortgage', '/ˈmɔːɡɪdʒ/', 'n. 抵押贷款 v. 抵押'],
  ['motion', '/ˈməʊʃn/', 'n. 运动；动议'],
  ['multiple', '/ˈmʌltɪpl/', 'adj. 多重的 n. 倍数'],
  ['municipal', '/mjuːˈnɪsɪpl/', 'adj. 市政的；市的'],
  ['mutual', '/ˈmjuːtʃuəl/', 'adj. 相互的；共同的'],
  ['narrative', '/ˈnærətɪv/', 'n. 叙述 adj. 叙述的'],
  ['nasty', '/ˈnɑːsti/', 'adj. 肮脏的；令人不快的'],
  ['neglect', '/nɪˈɡlekt/', 'v./n. 忽视；疏忽'],
  ['nerve', '/nɜːv/', 'n. 神经；勇气'],
  ['network', '/ˈnetwɜːk/', 'n. 网络 v. 建立关系'],
  ['norm', '/nɔːm/', 'n. 规范；标准'],
  ['novelty', '/ˈnɒvlti/', 'n. 新奇；新颖'],
  ['nuclear', '/ˈnjuːkliər/', 'adj. 核的；核心的'],
  ['nutrition', '/njuˈtrɪʃn/', 'n. 营养'],
  ['obligation', '/ˌɒblɪˈɡeɪʃn/', 'n. 义务；责任'],
  ['observation', '/ˌɒbzəˈveɪʃn/', 'n. 观察；评论'],
  ['obsession', '/əbˈseʃn/', 'n. 痴迷；困扰'],
  ['obstacle', '/ˈɒbstəkl/', 'n. 障碍；妨碍'],
  ['occupy', '/ˈɒkjupaɪ/', 'v. 占据；占领'],
  ['offense', '/əˈfens/', 'n. 犯罪；冒犯'],
  ['offspring', '/ˈɒfsprɪŋ/', 'n. 后代；子女'],
  ['operational', '/ˌɒpəˈreɪʃənl/', 'adj. 操作的；运营的'],
  ['opt', '/ɒpt/', 'v. 选择'],
  ['optimistic', '/ˌɒptɪˈmɪstɪk/', 'adj. 乐观的'],
  ['organic', '/ɔːˈɡænɪk/', 'adj. 有机的；器官的'],
  ['organize', '/ˈɔːɡənaɪz/', 'v. 组织；安排'],
  ['overall', '/ˌəʊvərˈɔːl/', 'adj. 总的 adv. 总体上'],
  ['overlap', '/ˌəʊvəˈlæp/', 'v./n. 重叠；部分相同'],
  ['overturn', '/ˌəʊvəˈtɜːn/', 'v. 推翻；翻转'],
  ['overwhelm', '/ˌəʊvəˈwelm/', 'v. 压倒；淹没'],
  ['paradox', '/ˈpærədɒks/', 'n. 悖论；矛盾的人或事'],
  ['parliament', '/ˈpɑːləmənt/', 'n. 议会；国会'],
  ['passive', '/ˈpæsɪv/', 'adj. 被动的；消极的'],
  ['patrol', '/pəˈtrəʊl/', 'v./n. 巡逻；巡查'],
  ['peer', '/pɪər/', 'n. 同龄人 v. 凝视'],
  ['penalty', '/ˈpenəlti/', 'n. 处罚；惩罚'],
  ['perception', '/pəˈsepʃn/', 'n. 感知；理解'],
  ['peril', '/ˈperəl/', 'n. 危险；冒险'],
  ['permit', '/pəˈmɪt/', 'v. 允许 n. 许可证'],
  ['persist', '/pəˈsɪst/', 'v. 坚持；持续'],
  ['petition', '/pəˈtɪʃn/', 'n. 请愿 v. 请求'],
  ['phase', '/feɪz/', 'n. 阶段；时期'],
  ['plead', '/pliːd/', 'v. 恳求；辩护'],
  ['pledge', '/pledʒ/', 'n./v. 保证；誓言'],
  ['poll', '/pəʊl/', 'n. 投票；民意调查'],
  ['pose', '/pəʊz/', 'v. 摆姿势；造成 n. 姿势'],
  ['precede', '/prɪˈsiːd/', 'v. 在...之前；领先'],
  ['predecessor', '/ˈpriːdɪsesər/', 'n. 前任；前身'],
  ['preliminary', '/prɪˈlɪmɪnəri/', 'adj. 初步的 n. 准备工作'],
  ['premise', '/ˈpremɪs/', 'n. 前提 v. 假定'],
  ['premium', '/ˈpriːmiəm/', 'n. 保险费 adj. 高级的'],
  ['prescribe', '/prɪˈskraɪb/', 'v. 规定；开药方'],
  ['preside', '/prɪˈzaɪd/', 'v. 主持；负责'],
  ['presumably', '/prɪˈzjuːməbli/', 'adv. 大概；据推测'],
  ['prevail', '/prɪˈveɪl/', 'v. 盛行；占优势'],
  ['primitive', '/ˈprɪmɪtɪv/', 'adj. 原始的；简陋的'],
  ['probe', '/prəʊb/', 'v./n. 探测；调查'],
  ['proclaim', '/prəˈkleɪm/', 'v. 宣布；声明'],
  ['profile', '/ˈprəʊfaɪl/', 'n. 轮廓；简介 v. 概述'],
  ['prohibit', '/prəˈhɪbɪt/', 'v. 禁止；阻止'],
  ['prominent', '/ˈprɒmɪnənt/', 'adj. 突出的；著名的'],
  ['promising', '/ˈprɒmɪsɪŋ/', 'adj. 有前途的'],
  ['propel', '/prəˈpel/', 'v. 推进；驱动'],
  ['prosecute', '/ˈprɒsɪkjuːt/', 'v. 起诉；检举'],
  ['prospective', '/prəˈspektɪv/', 'adj. 预期的；未来的'],
  ['protocol', '/ˈprəʊtəkɒl/', 'n. 协议；礼仪'],
  ['provoke', '/prəˈvəʊk/', 'v. 激怒；引起'],
  ['publicity', '/pʌbˈlɪsəti/', 'n. 宣传；公众关注'],
  ['punctual', '/ˈpʌŋktʃuəl/', 'adj. 准时的'],
  ['quest', '/kwest/', 'n./v. 探索；追求'],
  ['quota', '/ˈkwəʊtə/', 'n. 配额；指标'],
  ['radical', '/ˈrædɪkl/', 'adj. 根本的；激进的'],
  ['rally', '/ˈræli/', 'v. 集会 n. 拉力赛'],
  ['rating', '/ˈreɪtɪŋ/', 'n. 评级；评分'],
  ['rebel', '/ˈrebl/', 'n. 反叛者 v. 反抗'],
  ['reception', '/rɪˈsepʃn/', 'n. 接待；招待会'],
  ['reckon', '/ˈrekən/', 'v. 认为；估算'],
  ['recruit', '/rɪˈkruːt/', 'v. 招募 n. 新成员'],
  ['refugee', '/ˌrefjuˈdʒiː/', 'n. 难民'],
  ['regime', '/reɪˈʒiːm/', 'n. 政权；制度'],
  ['reign', '/reɪn/', 'n. 统治 v. 当政'],
  ['reliance', '/rɪˈlaɪəns/', 'n. 依赖；信赖'],
  ['remedy', '/ˈremədi/', 'n. 补救办法 v. 补救'],
  ['render', '/ˈrendər/', 'v. 使成为；提供；渲染'],
  ['renewable', '/rɪˈnjuːəbl/', 'adj. 可再生的；可延长的'],
  ['renowned', '/rɪˈnaʊnd/', 'adj. 著名的；有声望的'],
  ['reproduce', '/ˌriːprəˈdjuːs/', 'v. 复制；繁殖'],
  ['resemble', '/rɪˈzembl/', 'v. 类似于；像'],
  ['resent', '/rɪˈzent/', 'v. 怨恨；愤恨'],
  ['reserve', '/rɪˈzɜːv/', 'v. 保留；预订 n. 储备'],
  ['reside', '/rɪˈzaɪd/', 'v. 居住；存在于'],
  ['resign', '/rɪˈzaɪn/', 'v. 辞职；放弃'],
  ['resistance', '/rɪˈzɪstəns/', 'n. 抵抗；阻力'],
  ['resort', '/rɪˈzɔːt/', 'n. 度假地 v. 诉诸'],
  ['retail', '/ˈriːteɪl/', 'n. 零售 v. 零售'],
  ['retain', '/rɪˈteɪn/', 'v. 保持；保留'],
  ['retreat', '/rɪˈtriːt/', 'v./n. 撤退；退隐'],
  ['revelation', '/ˌrevəˈleɪʃn/', 'n. 揭示；启示'],
  ['revenue', '/ˈrevənjuː/', 'n. 收入；税收'],
  ['revise', '/rɪˈvaɪz/', 'v. 修订；复习'],
  ['rigorous', '/ˈrɪɡərəs/', 'adj. 严格的；缜密的'],
  ['ritual', '/ˈrɪtʃuəl/', 'n. 仪式 adj. 仪式的'],
  ['robust', '/rəʊˈbʌst/', 'adj. 强健的；稳固的'],
  ['sacrifice', '/ˈsækrɪfaɪs/', 'n./v. 牺牲；献祭'],
  ['sanction', '/ˈsæŋkʃn/', 'n./v. 制裁；批准'],
  ['scatter', '/ˈskætər/', 'v. 分散；散开'],
  ['scenario', '/sɪˈnɑːriəʊ/', 'n. 场景；方案'],
  ['scope', '/skəʊp/', 'n. 范围；余地'],
  ['sculpture', '/ˈskʌlptʃər/', 'n. 雕塑 v. 雕刻'],
  ['sector', '/ˈsektər/', 'n. 部门；行业'],
  ['segment', '/ˈseɡmənt/', 'n. 部分 v. 分割'],
  ['seminar', '/ˈsemɪnɑːr/', 'n. 研讨会'],
  ['sentiment', '/ˈsentɪmənt/', 'n. 情绪；观点'],
  ['sequence', '/ˈsiːkwəns/', 'n. 顺序；一系列'],
  ['session', '/ˈseʃn/', 'n. 会议；会期'],
  ['settlement', '/ˈsetlmənt/', 'n. 解决；定居点'],
  ['shrink', '/ʃrɪŋk/', 'v. 收缩；退缩'],
  ['siege', '/siːdʒ/', 'n. 围攻；包围'],
  ['slogan', '/ˈsləʊɡən/', 'n. 标语；口号'],
  ['soar', '/sɔːr/', 'v. 猛增；高飞'],
  ['sole', '/səʊl/', 'adj. 唯一的 n. 鞋底'],
  ['solicitor', '/səˈlɪsɪtər/', 'n. 律师；法务'],
  ['solidarity', '/ˌsɒlɪˈdærəti/', 'n. 团结；一致'],
  ['sophisticated', '/səˈfɪstɪkeɪtɪd/', 'adj. 复杂的；精密的；世故的'],
  ['span', '/spæn/', 'n. 跨度 v. 跨越'],
  ['specialize', '/ˈspeʃəlaɪz/', 'v. 专攻；专门从事'],
  ['specimen', '/ˈspesɪmən/', 'n. 标本；样本'],
  ['spectacle', '/ˈspektəkl/', 'n. 景象；壮观'],
  ['sponsor', '/ˈspɒnsər/', 'n. 赞助者 v. 赞助'],
  ['stake', '/steɪk/', 'n. 利害关系；股份；赌注'],
  ['statute', '/ˈstætʃuːt/', 'n. 法规；条例'],
  ['steer', '/stɪər/', 'v. 引导；驾驶'],
  ['stimulate', '/ˈstɪmjuleɪt/', 'v. 刺激；促进'],
  ['stock', '/stɒk/', 'n. 股票；库存 v. 储备'],
  ['storage', '/ˈstɔːrɪdʒ/', 'n. 存储；仓库'],
  ['strand', '/strænd/', 'n. 股；缕 v. 搁浅'],
  ['strive', '/straɪv/', 'v. 努力；奋斗'],
  ['stun', '/stʌn/', 'v. 使震惊；击晕'],
  ['submit', '/səbˈmɪt/', 'v. 提交；屈服'],
  ['subordinate', '/səˈbɔːdɪnət/', 'adj. 下级的 n. 下属'],
  ['subsequent', '/ˈsʌbsɪkwənt/', 'adj. 随后的；后来的'],
  ['subsidize', '/ˈsʌbsɪdaɪz/', 'v. 补贴；资助'],
  ['substitute', '/ˈsʌbstɪtjuːt/', 'v. 替代 n. 替代品'],
  ['sue', '/suː/', 'v. 起诉；控告'],
  ['superficial', '/ˌsuːpəˈfɪʃl/', 'adj. 表面的；肤浅的'],
  ['supreme', '/suːˈpriːm/', 'adj. 最高的；至高的'],
  ['surge', '/sɜːdʒ/', 'v./n. 激增；汹涌'],
  ['surplus', '/ˈsɜːpləs/', 'n. 过剩 adj. 过剩的'],
  ['suspension', '/səˈspenʃn/', 'n. 暂停；悬挂'],
  ['suspicious', '/səˈspɪʃəs/', 'adj. 可疑的；怀疑的'],
  ['sustainable', '/səˈsteɪnəbl/', 'adj. 可持续的'],
  ['sympathy', '/ˈsɪmpəθi/', 'n. 同情；赞同'],
  ['symphony', '/ˈsɪmfəni/', 'n. 交响乐'],
  ['symptom', '/ˈsɪmptəm/', 'n. 症状；征兆'],
  ['synthetic', '/sɪnˈθetɪk/', 'adj. 合成的；人造的'],
  ['tackle', '/ˈtækl/', 'v. 处理；解决 n. 装备'],
  ['tactic', '/ˈtæktɪk/', 'n. 策略；战术'],
  ['tariff', '/ˈtærɪf/', 'n. 关税'],
  ['territory', '/ˈterətri/', 'n. 领土；领域'],
  ['testimony', '/ˈtestɪməni/', 'n. 证词；证明'],
  ['therapy', '/ˈθerəpi/', 'n. 治疗；疗法'],
  ['threshold', '/ˈθreʃhəʊld/', 'n. 门槛；阈值'],
  ['tissue', '/ˈtɪʃuː/', 'n. 组织；纸巾'],
  ['toll', '/təʊl/', 'n. 通行费；代价'],
  ['tournament', '/ˈtɔːnəmənt/', 'n. 锦标赛；联赛'],
  ['trait', '/treɪt/', 'n. 特征；特点'],
  ['transaction', '/trænˈzækʃn/', 'n. 交易；办理'],
  ['transcript', '/ˈtrænskrɪpt/', 'n. 抄本；成绩单'],
  ['transmission', '/trænzˈmɪʃn/', 'n. 传输；传播'],
  ['transparent', '/trænˈspærənt/', 'adj. 透明的；公开的'],
  ['tribute', '/ˈtrɪbjuːt/', 'n. 致敬；贡品'],
  ['triumph', '/ˈtraɪʌmf/', 'n. 胜利 v. 战胜'],
  ['tuition', '/tjuˈɪʃn/', 'n. 学费；教学'],
  ['turbulent', '/ˈtɜːbjələnt/', 'adj. 动荡的；混乱的'],
  ['turnover', '/ˈtɜːnəʊvər/', 'n. 营业额；人员流动'],
  ['twist', '/twɪst/', 'v./n. 扭曲；转折'],
  ['underestimate', '/ˌʌndərˈestɪmeɪt/', 'v. 低估 n. 低估'],
  ['undergraduate', '/ˌʌndəˈɡrædʒuət/', 'n. 本科生'],
  ['underlying', '/ˌʌndəˈlaɪɪŋ/', 'adj. 潜在的；根本的'],
  ['undermine', '/ˌʌndəˈmaɪn/', 'v. 削弱；破坏'],
  ['unemployment', '/ˌʌnɪmˈplɔɪmənt/', 'n. 失业'],
  ['unfold', '/ʌnˈfəʊld/', 'v. 展开；展现'],
  ['unify', '/ˈjuːnɪfaɪ/', 'v. 统一；联合'],
  ['upcoming', '/ˈʌpkʌmɪŋ/', 'adj. 即将来临的'],
  ['upgrade', '/ʌpˈɡreɪd/', 'v./n. 升级；提升'],
  ['uphold', '/ʌpˈhəʊld/', 'v. 维持；支持'],
  ['utility', '/juːˈtɪləti/', 'n. 实用；公用事业'],
  ['vacant', '/ˈveɪkənt/', 'adj. 空的；空缺的'],
  ['vague', '/veɪɡ/', 'adj. 模糊的；不明确的'],
  ['venture', '/ˈventʃər/', 'n. 冒险 v. 敢于'],
  ['verdict', '/ˈvɜːdɪkt/', 'n. 裁决；判断'],
  ['verify', '/ˈverɪfaɪ/', 'v. 核实；验证'],
  ['versus', '/ˈvɜːsəs/', 'prep. 对；与...相对'],
  ['vessel', '/ˈvesl/', 'n. 船只；容器；血管'],
  ['vibrant', '/ˈvaɪbrənt/', 'adj. 充满活力的；鲜艳的'],
  ['violate', '/ˈvaɪəleɪt/', 'v. 违反；侵犯'],
  ['virtual', '/ˈvɜːtʃuəl/', 'adj. 虚拟的；实际上的'],
  ['vital', '/ˈvaɪtl/', 'adj. 至关重要的'],
  ['vivid', '/ˈvɪvɪd/', 'adj. 生动的；鲜明的'],
  ['vulnerable', '/ˈvʌlnərəbl/', 'adj. 脆弱的；易受伤害的'],
  ['warrant', '/ˈwɒrənt/', 'n. 搜查令 v. 保证'],
  ['weapon', '/ˈwepən/', 'n. 武器'],
  ['welfare', '/ˈwelfeər/', 'n. 福利；幸福'],
  ['withdraw', '/wɪðˈdrɔː/', 'v. 撤回；退出；取款'],
  ['workforce', '/ˈwɜːkfɔːs/', 'n. 劳动力'],
  ['workshop', '/ˈwɜːkʃɒp/', 'n. 车间；研讨会'],
  ['worship', '/ˈwɜːʃɪp/', 'v./n. 崇拜；敬奉'],
  ['zone', '/zəʊn/', 'n. 区域；地带'],
];

// Build JSON
const output = words.map(([word, phonetic, meaning], i) => ({
  id: `ky_${String(i + 1).padStart(4, '0')}`,
  word,
  phonetic,
  meaning,
  tags: ['考研', '英二', '核心'],
}));

fs.writeFileSync(
  'public/assets/words/kaoyan_basic.json',
  JSON.stringify({
    name: '考研英语二核心词汇',
    description: '考研英语二高频核心词汇',
    version: '2.0',
    total: output.length,
    words: output,
  }, null, 2),
  'utf-8'
);

console.log(`Generated ${output.length} kaoyan words → public/assets/words/kaoyan_basic.json`);
